GRANT USAGE ON SCHEMA public, agent_runtime TO primoria_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public, agent_runtime TO primoria_runtime;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public, agent_runtime TO primoria_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO primoria_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO primoria_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA agent_runtime
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO primoria_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA agent_runtime
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO primoria_runtime;
