import type { ViewerLanguage } from '@/shared/i18n/locale';

export type SettingsSectionId =
  | 'profile'
  | 'study'
  | 'assistant'
  | 'support';

export type SupportPageId = 'help' | 'feedback' | 'privacy' | 'terms';

const settingsDictionary = {
  'zh-CN': {
    title: '账号设置',
    subtitle: '把资料、学习偏好、提醒和帮助整理在一起。',
    overviewEyebrow: 'Profile Settings',
    overviewRole: '当前身份',
    overviewJoined: '加入时间',
    overviewVersion: '版本信息',
    overviewActiveSection: '当前分区',
    sections: {
      profile: { label: '个人资料', description: '管理名字、头像、封面和界面语言。' },
      study: { label: '学习与提醒', description: '调整学习习惯、目标和提醒方式。' },
      assistant: { label: '学习助手', description: '决定学习助手的语气和首页陪伴方式。' },
      support: { label: '帮助与隐私', description: '查看帮助、反馈、隐私说明和退出账号。' },
    },
    common: {
      save: '保存更改',
      saving: '保存中…',
      copy: '复制',
      copied: '已复制',
      refresh: '刷新',
      enabled: '已开启',
      disabled: '已关闭',
      browserOnly: '浏览器本地保存',
      synced: '已同步到账号',
      open: '打开',
      backToSettings: '返回设置',
      sessionExpired: '登录已过期，请重新登录。',
    },
    account: {
      title: '账号与资料',
      description: '更新你的名字、头像、封面和个人简介，让别人更容易认出你。',
      username: '用户名',
      bio: '个人简介',
      avatarUrl: '头像 URL',
      coverUrl: '封面 URL',
      role: '账号角色',
      save: '保存资料',
      saveSuccess: '资料已更新。',
      saveFailed: '资料保存失败。',
      coverPreview: '封面预览',
      avatarPreview: '头像预览',
    },
    appearance: {
      title: '显示与语言',
      description: '选择你看着最舒服的主题和语言。',
      theme: '主题模式',
      language: '界面语言',
      system: '跟随系统',
      light: '浅色',
      dark: '深色',
      chinese: '中文',
      english: 'English',
      save: '保存显示设置',
      saveSuccess: '显示设置已同步。',
    },
    learning: {
      title: '学习偏好',
      description: '把学习节奏调成更适合你的方式。',
      sound: { label: '声音反馈', hint: '答题与关键操作时播放音效。' },
      haptics: { label: '震动反馈', hint: '在支持设备上启用触觉反馈。' },
      autoplay: { label: '自动播放讲解音频', hint: '进入支持音频的内容时自动播放。' },
      hints: { label: '显示学习提示', hint: '在关键步骤展示引导提示。' },
      dailyGoal: '每日学习目标（分钟）',
      dailyGoalHint: '建议范围 10 到 180 分钟。',
      minutesPerDay: '分钟 / 天',
    },
    aiTutor: {
      title: '学习助手',
      description: '调整学习助手的引导方式，让它更像你想要的陪学伙伴。',
      personalityTitle: '助手语气',
      personalityHint: '选择学习助手默认的引导风格。不同人格会影响学习助手页和首页相关文案。',
      currentMode: '当前人格',
      examplePrompt: '示例开场',
      homeCompanion: {
        label: '首页显示学习助手形象',
        hint: '关闭后只会隐藏首页里的陪伴形象，学习助手入口仍然可以使用。',
      },
      saveSuccess: '学习助手设置已更新。',
      provider: 'AI 服务商',
      providerHint: '选择使用平台默认服务，或配置自己的 API Key。',
      providerGoogle: '平台默认（Google Gemini）',
      providerOpenAI: 'OpenAI',
      providerAnthropic: 'Anthropic',
      baseUrl: '自定义 Base URL',
      baseUrlHint: '用于 OpenAI 兼容接口（如代理服务）。留空则使用默认地址。',
      apiKey: 'API Key',
      apiKeyHint: '使用你自己的 API Key，留空则使用平台默认服务。',
      apiKeyPlaceholder: 'sk-...',
    },
    notifications: {
      title: '通知与提醒',
      description: '决定什么时候提醒你回来继续学。',
      master: { label: '启用通知', hint: '关闭后不会继续接收学习推送。' },
      dailyReminder: { label: '每日学习提醒', hint: '每天固定时间提醒你继续学习。' },
      reminderTime: '提醒时间',
      streak: { label: '连击中断提醒', hint: '快要断连击时提醒你回来。' },
      achievement: { label: '成就解锁通知', hint: '解锁新成就时发送浏览器通知。' },
      save: '保存通知设置',
      permissionDenied: '通知权限被系统拒绝，请在浏览器设置中重新开启。',
      unsupported: '当前环境不支持浏览器推送通知。',
      enableSuccess: '浏览器通知已接通。',
      disableSuccess: '浏览器通知已关闭。',
      saveSuccess: '提醒设置已同步。',
    },
    privacy: {
      title: '隐私与数据',
      description: '控制谁能看到你，以及这台设备上保留哪些临时内容。',
      privateProfile: { label: '私密资料页', hint: '仅授权用户可见你的资料页。' },
      shareLearningActivity: { label: '公开学习动态', hint: '允许他人看到你的进度变化。' },
      allowFollowers: { label: '允许被关注', hint: '关闭后新用户无法关注你。' },
      wifiOnlyDownloads: { label: '仅 Wi‑Fi 下载资源', hint: '避免在移动网络拉取大资源。' },
      clearCache: '清理本地缓存',
      clearCacheHint: '清除临时缓存和 AI Key，不影响账号数据。',
      clearCacheDone: '本地缓存已清理。',
    },
    support: {
      title: '帮助与隐私',
      description: '把常用帮助、隐私说明和退出账号收在一起。',
      help: '帮助中心',
      feedback: '提交反馈',
      privacy: '隐私政策',
      terms: '服务条款',
      versionLabel: '当前版本',
      signOut: '退出账号',
      signOutHint: '退出后需要重新登录才能继续学习。',
      signOutConfirmTitle: '确认退出？',
      signOutConfirmBody: '退出后当前设备的登录状态会被清除。',
    },
    supportPages: {
      help: {
        title: '帮助中心',
        subtitle: '先从这里快速找到常见问题和下一步建议。',
        blocks: [
          { title: '先检查什么', body: '如果课程打不开、消息没同步，先确认网络、登录状态和页面是否刷新完成。' },
          { title: '还没解决怎么办', body: '把问题页面、出现时间和操作步骤记下来，再去“提交反馈”里发给我们。' },
        ],
      },
      feedback: {
        title: '提交反馈',
        subtitle: '告诉我们哪里不顺、哪里不清楚，或者你希望下一步补什么。',
        blocks: [
          { title: '建议附带信息', body: '建议附上页面名称、账号身份、出现时间，以及你刚刚做了什么。' },
          { title: '我们最想知道', body: '哪里让你犹豫、哪里信息太多、哪里不像你以为会发生的那样。' },
        ],
      },
      privacy: {
        title: '隐私政策',
        subtitle: '这里说明我们会保存什么，以及这些内容用来做什么。',
        blocks: [
          { title: '账号资料', body: '你的名字、头像、身份和提醒设置会跟着账号保存，方便你换设备后继续使用。' },
          { title: '本机数据', body: '一些学习偏好和临时缓存会留在当前浏览器里，用来帮你更快回到上次状态。' },
        ],
      },
      terms: {
        title: '服务条款',
        subtitle: '这里说明当前产品提供什么、不提供什么，以及你能期待怎样的使用方式。',
        blocks: [
          { title: '使用边界', body: '不同页面会持续改进，但不会影响你已经创建的课程、资料和学习记录。' },
          { title: '提醒说明', body: '提醒是否生效，还会受到浏览器权限和设备设置的影响。' },
        ],
      },
    },
  },
  en: {
    title: 'Account Settings',
    subtitle: 'Keep your profile, study habits, reminders, and help in one place.',
    overviewEyebrow: 'Profile Settings',
    overviewRole: 'Role',
    overviewJoined: 'Joined',
    overviewVersion: 'Version',
    overviewActiveSection: 'Active Section',
    sections: {
      profile: { label: 'Profile', description: 'Manage your name, image, cover, and interface language.' },
      study: { label: 'Study & Reminders', description: 'Adjust your habits, goals, and reminder timing.' },
      assistant: { label: 'Study Helper', description: 'Choose how the helper sounds and shows up.' },
      support: { label: 'Help & Privacy', description: 'Open help, feedback, privacy, and sign out.' },
    },
    common: {
      save: 'Save Changes',
      saving: 'Saving…',
      copy: 'Copy',
      copied: 'Copied',
      refresh: 'Refresh',
      enabled: 'Enabled',
      disabled: 'Disabled',
      browserOnly: 'Stored in this browser',
      synced: 'Synced to account',
      open: 'Open',
      backToSettings: 'Back to Settings',
      sessionExpired: 'Session expired. Please sign in again.',
    },
    account: {
      title: 'Account & Profile',
      description: 'Update the basics so your account feels like yours.',
      username: 'Username',
      bio: 'Bio',
      avatarUrl: 'Avatar URL',
      coverUrl: 'Cover URL',
      role: 'Account Role',
      save: 'Save Profile',
      saveSuccess: 'Profile updated.',
      saveFailed: 'Profile update failed.',
      coverPreview: 'Cover Preview',
      avatarPreview: 'Avatar Preview',
    },
    appearance: {
      title: 'Appearance & Language',
      description: 'Choose the theme and language that feel easiest to use.',
      theme: 'Theme Mode',
      language: 'Interface Language',
      system: 'System',
      light: 'Light',
      dark: 'Dark',
      chinese: '中文',
      english: 'English',
      save: 'Save Display Settings',
      saveSuccess: 'Display settings synced.',
    },
    learning: {
      title: 'Learning Preferences',
      description: 'Shape the learning pace that works best for you.',
      sound: { label: 'Sound Effects', hint: 'Play sound during answers and key interactions.' },
      haptics: { label: 'Haptic Feedback', hint: 'Enable tactile feedback on supported devices.' },
      autoplay: { label: 'Auto-play Lesson Audio', hint: 'Automatically start audio on supported content.' },
      hints: { label: 'Show Learning Hints', hint: 'Display guidance at key learning steps.' },
      dailyGoal: 'Daily Goal (minutes)',
      dailyGoalHint: 'Recommended range is 10 to 180 minutes.',
      minutesPerDay: 'min / day',
    },
    aiTutor: {
      title: 'Study Helper',
      description: 'Adjust how your helper guides you and how much presence it has on home.',
      personalityTitle: 'Helper tone',
      personalityHint: 'Choose the default guidance style. It affects the helper page and related home copy.',
      currentMode: 'Current persona',
      examplePrompt: 'Example opener',
      homeCompanion: {
        label: 'Show helper on home',
        hint: 'This only hides the home companion. The helper page and entry points stay available.',
      },
      saveSuccess: 'Study Helper settings updated.',
      provider: 'AI Provider',
      providerHint: 'Use the platform default or configure your own API key.',
      providerGoogle: 'Platform default (Google Gemini)',
      providerOpenAI: 'OpenAI',
      providerAnthropic: 'Anthropic',
      baseUrl: 'Custom Base URL',
      baseUrlHint: 'For OpenAI-compatible endpoints (e.g. proxies). Leave empty for default.',
      apiKey: 'API Key',
      apiKeyHint: 'Use your own API key. Leave empty to use the platform default.',
      apiKeyPlaceholder: 'sk-...',
    },
    notifications: {
      title: 'Notifications & Reminders',
      description: 'Decide when you want a nudge to come back.',
      master: { label: 'Enable Notifications', hint: 'Turn this off to stop receiving study pushes.' },
      dailyReminder: { label: 'Daily Study Reminder', hint: 'Send a reminder at a fixed time every day.' },
      reminderTime: 'Reminder Time',
      streak: { label: 'Streak Reminder', hint: 'Warn before your streak expires.' },
      achievement: { label: 'Achievement Alerts', hint: 'Notify when a new achievement is unlocked.' },
      save: 'Save Notification Settings',
      permissionDenied: 'Notification permission is blocked in your browser settings.',
      unsupported: 'This environment does not support browser push notifications.',
      enableSuccess: 'Browser notifications are connected.',
      disableSuccess: 'Browser notifications are disabled.',
      saveSuccess: 'Reminder settings synced.',
    },
    privacy: {
      title: 'Privacy & Data',
      description: 'Control who can see you and what this device remembers.',
      privateProfile: { label: 'Private Profile', hint: 'Only approved users can view your profile.' },
      shareLearningActivity: { label: 'Share Learning Activity', hint: 'Let other users see your progress updates.' },
      allowFollowers: { label: 'Allow Followers', hint: 'Turn this off to stop new follow requests.' },
      wifiOnlyDownloads: { label: 'Wi‑Fi Only Downloads', hint: 'Avoid large downloads on cellular networks.' },
      clearCache: 'Clear Local Cache',
      clearCacheHint: 'Removes temporary cache and AI key without deleting account data.',
      clearCacheDone: 'Local cache cleared.',
    },
    support: {
      title: 'Help & Privacy',
      description: 'Keep help, privacy, feedback, and sign out in one place.',
      help: 'Help Center',
      feedback: 'Send Feedback',
      privacy: 'Privacy Policy',
      terms: 'Terms of Service',
      versionLabel: 'Current version',
      signOut: 'Sign Out',
      signOutHint: 'You will need to sign in again to continue learning.',
      signOutConfirmTitle: 'Sign out now?',
      signOutConfirmBody: 'This clears the current login session on this device.',
    },
    supportPages: {
      help: {
        title: 'Help Center',
        subtitle: 'Start here for common questions and quick next steps.',
        blocks: [
          { title: 'Check first', body: 'If a course or message is not loading, first confirm your network, sign-in state, and whether the page finished refreshing.' },
          { title: 'Still stuck?', body: 'Bring the page name, time, and steps you took into the feedback page so we can follow it clearly.' },
        ],
      },
      feedback: {
        title: 'Send Feedback',
        subtitle: 'Tell us what felt unclear, too heavy, or not quite how you expected it to work.',
        blocks: [
          { title: 'Helpful details', body: 'Include the page, your current role, the time it happened, and the steps you took.' },
          { title: 'What matters most', body: 'Tell us where you hesitated, where there was too much information, or what felt off.' },
        ],
      },
      privacy: {
        title: 'Privacy Policy',
        subtitle: 'This explains what we keep, and why we keep it.',
        blocks: [
          { title: 'Account data', body: 'Your profile, role, and reminder settings stay with your account so your setup can follow you across devices.' },
          { title: 'Device data', body: 'Some temporary preferences and cache stay in this browser to help you return faster.' },
        ],
      },
      terms: {
        title: 'Terms of Service',
        subtitle: 'This explains what the current product supports and how it is meant to be used.',
        blocks: [
          { title: 'Current scope', body: 'Screens will keep improving, but your courses, materials, and learning records stay intact.' },
          { title: 'Reminder behavior', body: 'Reminders also depend on browser permissions and device settings.' },
        ],
      },
    },
  },
} as const;

export const settingsSectionOrder: SettingsSectionId[] = [
  'profile',
  'study',
  'assistant',
  'support',
];

export function getSettingsCopy(language: ViewerLanguage) {
  return settingsDictionary[language];
}
