import type { ViewerLanguage } from '@/shared/i18n/locale';

export type SettingsSectionId =
  | 'account'
  | 'appearance'
  | 'learning'
  | 'aiTutor'
  | 'notifications'
  | 'privacy'
  | 'parent'
  | 'support';

export type SupportPageId = 'help' | 'feedback' | 'privacy' | 'terms';

const settingsDictionary = {
  'zh-CN': {
    title: '设置中心',
    subtitle: '管理你的账号、学习偏好、通知与家长模式。',
    overviewEyebrow: 'Profile Settings',
    overviewRole: '当前身份',
    overviewJoined: '加入时间',
    overviewVersion: '版本信息',
    overviewActiveSection: '当前分区',
    sections: {
      account: { label: '账号与资料', description: '管理头像、封面、用户名和个人简介。' },
      appearance: { label: '显示与语言', description: '选择主题模式与界面语言。' },
      learning: { label: '学习偏好', description: '调整学习体验开关与每日目标。' },
      aiTutor: { label: 'AI 导师', description: '设置 AI 导师人格，以及是否在首页显示导师形象。' },
      notifications: { label: '通知与提醒', description: '控制浏览器推送权限与提醒时间。' },
      privacy: { label: '隐私与数据', description: '管理可见性、社交权限与本地数据行为。' },
      parent: { label: '家长模式', description: '切换角色并管理孩子绑定能力。' },
      support: { label: '支持与关于', description: '帮助、反馈、隐私和版本信息。' },
    },
    common: {
      save: '保存更改',
      saving: '保存中…',
      copy: '复制',
      copied: '已复制',
      refresh: '刷新',
      enabled: '已开启',
      disabled: '已关闭',
      browserOnly: '浏览器本地保存',
      synced: '已同步到账号',
      open: '打开',
      backToSettings: '返回设置',
      sessionExpired: '登录已过期，请重新登录。',
    },
    account: {
      title: '账号与资料',
      description: '头像和封面先沿用 React 版现有的 URL 方式；保存后同步到 `profiles`。',
      username: '用户名',
      bio: '个人简介',
      avatarUrl: '头像 URL',
      coverUrl: '封面 URL',
      role: '账号角色',
      save: '保存资料',
      saveSuccess: '资料已更新。',
      saveFailed: '资料保存失败。',
      coverPreview: '封面预览',
      avatarPreview: '头像预览',
    },
    appearance: {
      title: '显示与语言',
      description: '主题与语言会立即应用到当前设置页，同时同步到 `user_settings`。',
      theme: '主题模式',
      language: '界面语言',
      system: '跟随系统',
      light: '浅色',
      dark: '深色',
      chinese: '中文',
      english: 'English',
      save: '保存显示设置',
      saveSuccess: '显示设置已同步。',
    },
    learning: {
      title: '学习偏好',
      description: '这些开关保存在当前浏览器，用于还原 Flutter 版的学习体验偏好。',
      sound: { label: '声音反馈', hint: '答题与关键操作时播放音效。' },
      haptics: { label: '震动反馈', hint: '在支持设备上启用触觉反馈。' },
      autoplay: { label: '自动播放讲解音频', hint: '进入支持音频的内容时自动播放。' },
      hints: { label: '显示学习提示', hint: '在关键步骤展示引导提示。' },
      dailyGoal: '每日学习目标（分钟）',
      dailyGoalHint: '建议范围 10 到 180 分钟。',
      minutesPerDay: '分钟 / 天',
    },
    aiTutor: {
      title: 'AI 导师',
      description: '导师人格和首页导师形象会立即应用到当前设备，并同步到你的账号设置。',
      personalityTitle: '导师人格',
      personalityHint: '选择 AI 导师默认的引导风格。不同人格会影响 AI 导师页和首页相关文案。',
      currentMode: '当前人格',
      examplePrompt: '示例开场',
      homeCompanion: {
        label: '首页显示 AI 导师形象',
        hint: '关闭后仅隐藏首页浮动导师形象，AI 导师页面和入口仍然可用。',
      },
      saveSuccess: 'AI 导师设置已同步。',
    },
    notifications: {
      title: '通知与提醒',
      description: '启用通知会请求浏览器权限并注册 Web Push 订阅。每日提醒配置同步到 `user_settings`。',
      master: { label: '启用通知', hint: '关闭后不会继续接收学习推送。' },
      dailyReminder: { label: '每日学习提醒', hint: '每天固定时间提醒你继续学习。' },
      reminderTime: '提醒时间',
      streak: { label: '连击中断提醒', hint: '快要断连击时提醒你回来。' },
      achievement: { label: '成就解锁通知', hint: '解锁新成就时发送浏览器通知。' },
      save: '保存通知设置',
      permissionDenied: '通知权限被系统拒绝，请在浏览器设置中重新开启。',
      unsupported: '当前环境不支持浏览器推送通知。',
      enableSuccess: '浏览器通知已接通。',
      disableSuccess: '浏览器通知已关闭。',
      saveSuccess: '提醒设置已同步。',
    },
    privacy: {
      title: '隐私与数据',
      description: '这些选项保存在本地，用于控制 viewer 的展示和缓存行为。',
      privateProfile: { label: '私密资料页', hint: '仅授权用户可见你的资料页。' },
      shareLearningActivity: { label: '公开学习动态', hint: '允许他人看到你的进度变化。' },
      allowFollowers: { label: '允许被关注', hint: '关闭后新用户无法关注你。' },
      wifiOnlyDownloads: { label: '仅 Wi‑Fi 下载资源', hint: '避免在移动网络拉取大资源。' },
      clearCache: '清理本地缓存',
      clearCacheHint: '清除临时缓存和 AI Key，不影响账号数据。',
      clearCacheDone: '本地缓存已清理。',
    },
    parent: {
      title: '家长模式',
      descriptionLearner: '生成绑定码后，家长账号即可关联并查看你的学习报告。',
      descriptionParent: '你当前是家长账号，可以进入家长看板绑定孩子并查看学习报告。',
      currentRole: '当前模式',
      learner: '学习者',
      parent: '家长',
      switching: '切换中…',
      switchToParent: '切换为家长模式',
      switchToLearner: '切换为学习者模式',
      switchSuccessParent: '已切换为家长模式。',
      switchSuccessLearner: '已切换为学习者模式。',
      bindingCode: '孩子绑定码',
      bindingCodeEmpty: '尚未生成绑定码，点击下方按钮创建。',
      bindingCodeGenerate: '生成绑定码',
      bindingCodeRefresh: '刷新绑定码',
      bindingCodeCopied: '绑定码已复制。',
      bindingCodeExpires: '有效期至',
      openDashboard: '打开家长看板',
    },
    support: {
      title: '支持与关于',
      description: '迁移 Flutter 设置页时，把原先的占位入口都收敛成 viewer 内的正式页面。',
      help: '帮助中心',
      feedback: '提交反馈',
      privacy: '隐私政策',
      terms: '服务条款',
      versionLabel: '版本',
      signOut: '退出当前账号',
      signOutHint: '退出后需要重新登录才能继续学习。',
      signOutConfirmTitle: '确认退出？',
      signOutConfirmBody: '退出后当前设备的登录状态会被清除。',
    },
    supportPages: {
      help: {
        title: '帮助中心',
        subtitle: '这里会承接设置页中的产品帮助入口，当前提供 viewer 内部说明和联系落点。',
        blocks: [
          { title: '使用说明', body: '如果你在课程、AI 导师或家长模式中遇到问题，先回到对应页面确认登录状态与网络连接。' },
          { title: '反馈路径', body: '需要更详细协助时，请前往“提交反馈”页面记录问题、截图和复现步骤。' },
        ],
      },
      feedback: {
        title: '提交反馈',
        subtitle: '这里是设置中心的正式反馈落点，用于收集问题、建议和迁移阶段的体验反馈。',
        blocks: [
          { title: '建议附带信息', body: '推荐附上问题页面、账号角色、出现时间，以及能复现问题的操作步骤。' },
          { title: '当前占位说明', body: '该页面当前为 viewer 内占位页，后续可接工单系统或 Supabase feedback 表。' },
        ],
      },
      privacy: {
        title: '隐私政策',
        subtitle: '这里保留设置中心中的隐私政策入口，当前展示 viewer 侧的数据使用范围说明。',
        blocks: [
          { title: '账号数据', body: '账号资料、角色、提醒时间等设置会同步到 Supabase 中与你账户关联的表。' },
          { title: '本地数据', body: '学习偏好和部分临时缓存保留在当前浏览器，用于恢复你的 viewer 使用体验。' },
        ],
      },
      terms: {
        title: '服务条款',
        subtitle: '这里是设置中心的服务条款占位页，说明 viewer 当前的能力边界和环境依赖。',
        blocks: [
          { title: '功能边界', body: '部分功能仍处于 React 迁移阶段，界面与数据能力会逐步对齐 Flutter viewer。' },
          { title: '通知能力', body: '浏览器推送依赖设备权限、service worker 和部署环境中的 VAPID 配置。' },
        ],
      },
    },
  },
  en: {
    title: 'Settings Center',
    subtitle: 'Manage your account, preferences, notifications, and parent mode.',
    overviewEyebrow: 'Profile Settings',
    overviewRole: 'Role',
    overviewJoined: 'Joined',
    overviewVersion: 'Version',
    overviewActiveSection: 'Active Section',
    sections: {
      account: { label: 'Account & Profile', description: 'Manage avatar, cover image, username, and bio.' },
      appearance: { label: 'Appearance & Language', description: 'Choose theme mode and interface language.' },
      learning: { label: 'Learning Preferences', description: 'Tune learning experience switches and daily goals.' },
      aiTutor: { label: 'AI Tutor', description: 'Set tutor persona and whether the home companion appears.' },
      notifications: { label: 'Notifications & Reminders', description: 'Control browser push access and reminder timing.' },
      privacy: { label: 'Privacy & Data', description: 'Manage visibility, social permissions, and local cache behavior.' },
      parent: { label: 'Parent Mode', description: 'Switch roles and manage child binding capabilities.' },
      support: { label: 'Support & About', description: 'Help, feedback, privacy, and version information.' },
    },
    common: {
      save: 'Save Changes',
      saving: 'Saving…',
      copy: 'Copy',
      copied: 'Copied',
      refresh: 'Refresh',
      enabled: 'Enabled',
      disabled: 'Disabled',
      browserOnly: 'Stored in this browser',
      synced: 'Synced to account',
      open: 'Open',
      backToSettings: 'Back to Settings',
      sessionExpired: 'Session expired. Please sign in again.',
    },
    account: {
      title: 'Account & Profile',
      description: 'Avatar and cover still use the current React URL workflow and save into `profiles`.',
      username: 'Username',
      bio: 'Bio',
      avatarUrl: 'Avatar URL',
      coverUrl: 'Cover URL',
      role: 'Account Role',
      save: 'Save Profile',
      saveSuccess: 'Profile updated.',
      saveFailed: 'Profile update failed.',
      coverPreview: 'Cover Preview',
      avatarPreview: 'Avatar Preview',
    },
    appearance: {
      title: 'Appearance & Language',
      description: 'Theme and language apply to settings immediately and sync into `user_settings`.',
      theme: 'Theme Mode',
      language: 'Interface Language',
      system: 'System',
      light: 'Light',
      dark: 'Dark',
      chinese: '中文',
      english: 'English',
      save: 'Save Display Settings',
      saveSuccess: 'Display settings synced.',
    },
    learning: {
      title: 'Learning Preferences',
      description: 'These switches remain browser-local and mirror the Flutter viewer behavior.',
      sound: { label: 'Sound Effects', hint: 'Play sound during answers and key interactions.' },
      haptics: { label: 'Haptic Feedback', hint: 'Enable tactile feedback on supported devices.' },
      autoplay: { label: 'Auto-play Lesson Audio', hint: 'Automatically start audio on supported content.' },
      hints: { label: 'Show Learning Hints', hint: 'Display guidance at key learning steps.' },
      dailyGoal: 'Daily Goal (minutes)',
      dailyGoalHint: 'Recommended range is 10 to 180 minutes.',
      minutesPerDay: 'min / day',
    },
    aiTutor: {
      title: 'AI Tutor',
      description: 'Tutor persona and the home companion apply immediately on this device and sync to your account settings.',
      personalityTitle: 'Tutor Persona',
      personalityHint: 'Choose the default guidance style for AI Tutor. Persona affects the AI Tutor page and related home copy.',
      currentMode: 'Current persona',
      examplePrompt: 'Example opener',
      homeCompanion: {
        label: 'Show AI tutor on home',
        hint: 'Turning this off only hides the floating home companion. The AI Tutor page and entry points stay available.',
      },
      saveSuccess: 'AI Tutor settings synced.',
    },
    notifications: {
      title: 'Notifications & Reminders',
      description: 'Enabling notifications requests browser permission and registers a Web Push subscription.',
      master: { label: 'Enable Notifications', hint: 'Turn this off to stop receiving study pushes.' },
      dailyReminder: { label: 'Daily Study Reminder', hint: 'Send a reminder at a fixed time every day.' },
      reminderTime: 'Reminder Time',
      streak: { label: 'Streak Reminder', hint: 'Warn before your streak expires.' },
      achievement: { label: 'Achievement Alerts', hint: 'Notify when a new achievement is unlocked.' },
      save: 'Save Notification Settings',
      permissionDenied: 'Notification permission is blocked in your browser settings.',
      unsupported: 'This environment does not support browser push notifications.',
      enableSuccess: 'Browser notifications are connected.',
      disableSuccess: 'Browser notifications are disabled.',
      saveSuccess: 'Reminder settings synced.',
    },
    privacy: {
      title: 'Privacy & Data',
      description: 'These controls remain local to the viewer and affect visibility and cache behavior.',
      privateProfile: { label: 'Private Profile', hint: 'Only approved users can view your profile.' },
      shareLearningActivity: { label: 'Share Learning Activity', hint: 'Let other users see your progress updates.' },
      allowFollowers: { label: 'Allow Followers', hint: 'Turn this off to stop new follow requests.' },
      wifiOnlyDownloads: { label: 'Wi‑Fi Only Downloads', hint: 'Avoid large downloads on cellular networks.' },
      clearCache: 'Clear Local Cache',
      clearCacheHint: 'Removes temporary cache and AI key without deleting account data.',
      clearCacheDone: 'Local cache cleared.',
    },
    parent: {
      title: 'Parent Mode',
      descriptionLearner: 'Generate a binding code so a parent account can link to your learning report.',
      descriptionParent: 'You are using a parent account. Open the dashboard to manage linked children.',
      currentRole: 'Current Mode',
      learner: 'Learner',
      parent: 'Parent',
      switching: 'Switching…',
      switchToParent: 'Switch to Parent Mode',
      switchToLearner: 'Switch to Learner Mode',
      switchSuccessParent: 'Switched to parent mode.',
      switchSuccessLearner: 'Switched to learner mode.',
      bindingCode: 'Child Binding Code',
      bindingCodeEmpty: 'No active binding code yet. Generate one below.',
      bindingCodeGenerate: 'Generate Code',
      bindingCodeRefresh: 'Refresh Code',
      bindingCodeCopied: 'Binding code copied.',
      bindingCodeExpires: 'Expires at',
      openDashboard: 'Open Parent Dashboard',
    },
    support: {
      title: 'Support & About',
      description: 'These entries now land on formal in-viewer pages instead of temporary placeholders.',
      help: 'Help Center',
      feedback: 'Send Feedback',
      privacy: 'Privacy Policy',
      terms: 'Terms of Service',
      versionLabel: 'Version',
      signOut: 'Sign Out',
      signOutHint: 'You will need to sign in again to continue learning.',
      signOutConfirmTitle: 'Sign out now?',
      signOutConfirmBody: 'This clears the current login session on this device.',
    },
    supportPages: {
      help: {
        title: 'Help Center',
        subtitle: 'This page now serves as the in-viewer destination for help links from settings.',
        blocks: [
          { title: 'Usage Notes', body: 'If something breaks in courses, AI Tutor, or parent mode, first confirm network connectivity and sign-in state.' },
          { title: 'Escalation Path', body: 'When you need more support, continue to the feedback page with screenshots and reproduction steps.' },
        ],
      },
      feedback: {
        title: 'Send Feedback',
        subtitle: 'This page is the formal settings destination for issue reports and product suggestions.',
        blocks: [
          { title: 'Recommended Details', body: 'Include the page, active role, time, and the steps required to reproduce the issue.' },
          { title: 'Current Placeholder Scope', body: 'This is still an in-viewer placeholder page and can later connect to a real feedback queue.' },
        ],
      },
      privacy: {
        title: 'Privacy Policy',
        subtitle: 'This preserves the settings privacy entry and explains the current viewer data boundaries.',
        blocks: [
          { title: 'Account Data', body: 'Profile, role, and reminder settings sync into Supabase tables associated with your account.' },
          { title: 'Local Data', body: 'Learning preferences and some temporary cache remain in this browser to restore your viewer experience.' },
        ],
      },
      terms: {
        title: 'Terms of Service',
        subtitle: 'This page documents the current viewer capability boundaries and environment dependencies.',
        blocks: [
          { title: 'Capability Scope', body: 'Some flows are still being migrated from the Flutter viewer and will continue to evolve.' },
          { title: 'Notification Requirements', body: 'Browser push depends on permissions, service workers, and deployed VAPID configuration.' },
        ],
      },
    },
  },
} as const;

export const settingsSectionOrder: SettingsSectionId[] = [
  'account',
  'appearance',
  'learning',
  'aiTutor',
  'notifications',
  'privacy',
  'parent',
  'support',
];

export function getSettingsCopy(language: ViewerLanguage) {
  return settingsDictionary[language];
}
