import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import {
  CSS_VARIABLES,
  LEARNING_OBJECT_CSS,
  LEARNING_OBJECT_STYLE_VERSION,
  LO_CLASS_DESCRIPTIONS,
  PRIMORIA_PALETTE,
  PRIMORIA_PALETTE_JS,
  SERIES,
  SVG_CLASSES_CSS,
  SVG_STYLE_CLASSES,
  WIDGET_STYLE_PROMPT,
} from "../src/components/generative-ui/style-tokens";

// The style vocabulary is generated by @primoria/contracts/visual-style.
// These tests guard the old failure mode where graph.mjs and style-tokens.ts
// carried separate prose/value copies that could silently drift.

// The widget tool prompt moved out of graph.mjs into tools/visualization.mjs
// when the agent was split into modules.
const graphSource = readFileSync(
  fileURLToPath(new URL("../../agent/src/tools/visualization.mjs", import.meta.url)),
  "utf8",
);

const styleTokensSource = readFileSync(
  fileURLToPath(new URL("../src/components/generative-ui/style-tokens.ts", import.meta.url)),
  "utf8",
);

const widgetRendererSource = readFileSync(
  fileURLToPath(new URL("../src/components/generative-ui/widget-renderer.tsx", import.meta.url)),
  "utf8",
);

describe("style vocabulary single source", () => {
  it("the agent prompt imports the generated style guidance instead of hardcoding vocabulary", () => {
    expect(graphSource).toContain("@primoria/contracts/visual-style");
    expect(graphSource).toContain("WIDGET_STYLE_PROMPT");
    expect(graphSource).toContain("WIDGET_RENDERER_DESCRIPTION");
    expect(graphSource).not.toContain('class="lo-stage"');
    expect(graphSource).not.toContain("var(--series-amber)");
  });

  it("the web compatibility module re-exports tokens instead of redefining values", () => {
    expect(styleTokensSource).toContain("@primoria/contracts/visual-style");
    expect(styleTokensSource).not.toMatch(/#[0-9a-fA-F]{6}/);
  });

  it("the generated prompt carries the shared style version", () => {
    expect(WIDGET_STYLE_PROMPT).toContain(`STYLE_VERSION ${LEARNING_OBJECT_STYLE_VERSION}`);
  });

  it("every lo-* class in the generated prompt exists in LEARNING_OBJECT_CSS", () => {
    const names = new Set(WIDGET_STYLE_PROMPT.match(/(?<!-)\blo-[a-z]+(?:-[a-z]+)*\b/g) ?? []);
    expect(names.size).toBeGreaterThan(0);
    for (const name of names) {
      expect(LEARNING_OBJECT_CSS, `missing .${name}`).toContain(`.${name}`);
      expect(LO_CLASS_DESCRIPTIONS, `missing description for .${name}`).toHaveProperty(name);
    }
  });

  it("every c-* SVG class in the generated prompt exists in SVG_CLASSES_CSS", () => {
    const names = new Set(WIDGET_STYLE_PROMPT.match(/\bc-[a-z]+\b/g) ?? []);
    expect(names.size).toBeGreaterThan(0);
    for (const name of names) {
      expect(SVG_CLASSES_CSS, `missing .${name}`).toContain(`.${name}`);
      expect(SVG_STYLE_CLASSES, `missing source entry for .${name}`).toHaveProperty(name.slice(2));
    }
  });

  it("every CSS variable in the generated prompt exists in LEARNING_OBJECT_CSS", () => {
    const names = new Set(WIDGET_STYLE_PROMPT.match(/--(?:lo|series)-[a-z]+(?:-[a-z]+)*/g) ?? []);
    expect(names.size).toBeGreaterThan(0);
    for (const name of names) {
      expect(LEARNING_OBJECT_CSS, `missing ${name}`).toContain(`${name}:`);
      expect(CSS_VARIABLES, `missing source entry for ${name}`).toContain(name);
    }
  });

  it("every PRIMORIA.* key in the generated prompt exists in the palette global", () => {
    const keys = new Set(
      (WIDGET_STYLE_PROMPT.match(/PRIMORIA\.[a-zA-Z]+/g) ?? []).map((match) => match.split(".")[1]!),
    );
    expect(keys.size).toBeGreaterThan(0);
    for (const key of keys) {
      expect(PRIMORIA_PALETTE_JS, `missing PRIMORIA.${key}`).toContain(`${key}:`);
      expect(PRIMORIA_PALETTE, `missing source entry for PRIMORIA.${key}`).toHaveProperty(key);
    }
  });

  it("series values are identical across CSS variables, SVG classes, and palette keys", () => {
    expect(LEARNING_OBJECT_CSS).toContain(`--series-amber: ${SERIES.amber.stroke};`);
    expect(LEARNING_OBJECT_CSS).toContain(`--series-amber-fill: ${SERIES.amber.fill};`);
    expect(PRIMORIA_PALETTE_JS).toContain(`amber: "${SERIES.amber.stroke}"`);
    expect(PRIMORIA_PALETTE_JS).toContain(`amberFill: "${SERIES.amber.fill}"`);
    expect(SVG_CLASSES_CSS).toContain("svg .c-amber");
    expect(SVG_CLASSES_CSS).toContain(`fill: ${SERIES.amber.fill}; stroke: ${SERIES.amber.stroke};`);
    expect(SVG_CLASSES_CSS).toContain(`fill: ${SERIES.pine.fill}; stroke: ${SERIES.pine.stroke};`);
  });

  it("the shared styles are injected into the widget iframe shell", () => {
    expect(widgetRendererSource).toContain("PRIMORIA_PALETTE_JS");
    expect(widgetRendererSource).toContain("LEARNING_OBJECT_CSS");
    expect(widgetRendererSource).toContain("SVG_CLASSES_CSS");
  });
});
