#!/usr/bin/env tsx

import { readFileSync } from "node:fs";
import { join } from "node:path";

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(`assertion failed: ${message}`);
}

async function main() {
  const source = readFileSync(join(process.cwd(), "src/components/workspace/workspace-client.tsx"), "utf8");
  const workspaceClientState = readFileSync(join(process.cwd(), "src/components/workspace/workspace-client-state.ts"), "utf8");
  const navRail = readFileSync(join(process.cwd(), "src/components/tutor/nav-rail.tsx"), "utf8");
  const agentManager = readFileSync(join(process.cwd(), "src/components/workspace/workspace-agent-manager.tsx"), "utf8");
  const agentManagerPage = readFileSync(join(process.cwd(), "src/app/workspace/agents/page.tsx"), "utf8");
  const rootLayout = readFileSync(join(process.cwd(), "src/app/layout.tsx"), "utf8");
  const homePage = readFileSync(join(process.cwd(), "src/app/page.tsx"), "utf8");
  const coursePage = readFileSync(join(process.cwd(), "src/app/course/[id]/page.tsx"), "utf8");
  const workspacesRoute = readFileSync(join(process.cwd(), "src/app/api/workspaces/route.ts"), "utf8");
  const workspaceJoinRoute = readFileSync(join(process.cwd(), "src/app/api/workspaces/join/route.ts"), "utf8");
  const threadsRoute = readFileSync(join(process.cwd(), "src/app/api/workspaces/[id]/threads/route.ts"), "utf8");
  const messagesRoute = readFileSync(join(process.cwd(), "src/app/api/workspaces/[id]/messages/route.ts"), "utf8");
  const tasksRoute = readFileSync(join(process.cwd(), "src/app/api/workspaces/[id]/tasks/route.ts"), "utf8");
  const taskUpdateRoute = readFileSync(join(process.cwd(), "src/app/api/workspaces/[id]/tasks/[taskId]/route.ts"), "utf8");
  const membersRoute = readFileSync(join(process.cwd(), "src/app/api/workspaces/[id]/members/route.ts"), "utf8");
  const agentsRoute = readFileSync(join(process.cwd(), "src/app/api/workspaces/[id]/agents/route.ts"), "utf8");
  const agentProfileRoute = readFileSync(join(process.cwd(), "src/app/api/workspaces/[id]/agents/[profileId]/route.ts"), "utf8");
  const agentConnectionsRoute = readFileSync(join(process.cwd(), "src/app/api/workspaces/[id]/agent-connections/route.ts"), "utf8");
  const agentRunRoute = readFileSync(join(process.cwd(), "src/app/api/workspaces/[id]/agent-runs/[runId]/route.ts"), "utf8");
  const agentRunCancelRoute = readFileSync(join(process.cwd(), "src/app/api/workspaces/[id]/agent-runs/[runId]/cancel/route.ts"), "utf8");
  const agentRunRetryRoute = readFileSync(join(process.cwd(), "src/app/api/workspaces/[id]/agent-runs/[runId]/retry/route.ts"), "utf8");
  const agentApprovalRoute = readFileSync(join(process.cwd(), "src/app/api/workspaces/[id]/agent-approvals/[approvalId]/route.ts"), "utf8");
  const agentRuntimeHealthRoute = readFileSync(join(process.cwd(), "src/app/api/workspaces/agent-runtime/health/route.ts"), "utf8");
  const agentRuntime = readFileSync(join(process.cwd(), "src/lib/workspaces/agent-runtime.ts"), "utf8");
  const agentMemoryBulkArchiveRoute = readFileSync(join(process.cwd(), "src/app/api/workspaces/[id]/agent-memories/bulk-archive/route.ts"), "utf8");
  const agentMemoryRoute = readFileSync(join(process.cwd(), "src/app/api/workspaces/[id]/agent-memories/[memoryId]/route.ts"), "utf8");
  const agentSkillsRoute = readFileSync(join(process.cwd(), "src/app/api/workspaces/[id]/agent-skills/route.ts"), "utf8");
  const agentSkillStorage = readFileSync(join(process.cwd(), "src/lib/workspaces/agent-skill-storage.ts"), "utf8");
  const workspaceEventsRoute = readFileSync(join(process.cwd(), "src/app/api/workspaces/[id]/events/route.ts"), "utf8");
  const workspaceStore = readFileSync(join(process.cwd(), "src/lib/workspaces/store.ts"), "utf8");
  const agentProfileService = readFileSync(join(process.cwd(), "src/lib/workspaces/agent-profile-service.ts"), "utf8");
  const agentMemoryService = readFileSync(join(process.cwd(), "src/lib/workspaces/agent-memory-service.ts"), "utf8");
  const workspaceTaskService = readFileSync(join(process.cwd(), "src/lib/workspaces/workspace-task-service.ts"), "utf8");
  const workspaceAccessService = readFileSync(join(process.cwd(), "src/lib/workspaces/workspace-access-service.ts"), "utf8");
  const agentProfileGuardrails = readFileSync(join(process.cwd(), "src/lib/workspaces/agent-profile-guardrails.ts"), "utf8");
  const agentProfileRules = readFileSync(join(process.cwd(), "src/lib/workspaces/agent-profile-rules.ts"), "utf8");
  const agentProfilePersistence = readFileSync(join(process.cwd(), "src/lib/workspaces/agent-profile-persistence.ts"), "utf8");
  const styles = readFileSync(join(process.cwd(), "src/app/globals.css"), "utf8");
  const reviewPage = readFileSync(join(process.cwd(), "src/app/workspace/review/page.tsx"), "utf8");
  const artifactMigration = readFileSync(join(process.cwd(), "drizzle/0009_workspace_artifacts.sql"), "utf8");
  const packageJson = readFileSync(join(process.cwd(), "package.json"), "utf8");
  const workspaceAgentDoc = readFileSync(join(process.cwd(), "../../docs/workspace-agent-system.md"), "utf8");
  const workspaceAgentRuntimeHealthWorkflow = readFileSync(
    join(process.cwd(), "../../.github/workflows/workspace-agent-runtime-health.yml"),
    "utf8",
  );
  const deepAgentRuntimeE2e = readFileSync(join(process.cwd(), "tests/workspace-deepagent-runtime.e2e.mjs"), "utf8");
  const workspaceAgentApiE2e = readFileSync(join(process.cwd(), "tests/workspace-agent-api.e2e.mjs"), "utf8");
  const agentRuntimeHealthRouteUnit = readFileSync(join(process.cwd(), "tests/workspace-agent-runtime-health-route.unit.ts"), "utf8");

  assert(source.includes("AgentRunStatusChip"), "workspace chat renders compact agent run status");
  assert(!rootLayout.includes("CopilotKitProvider"), "root layout does not force CopilotKit onto workspace pages");
  assert(homePage.includes("CopilotKitProvider"), "home tutor page owns its CopilotKit provider");
  assert(coursePage.includes("CopilotKitProvider"), "course page owns its CopilotKit provider");
  assert(source.includes("AgentRunInlineDetail"), "workspace chat can expand compact agent run details inline");
  assert(source.includes("expandedAgentRunIds"), "workspace tracks which agent run details are expanded");
  assert(source.includes("mergeWorkspaceViews"), "workspace full-view refreshes merge with local state by id");
  assert(source.includes("setView((current) => mergeWorkspaceViews(current, data))"), "workspace stream updates do not blindly replace local merged state");
  assert(workspaceClientState.includes("if (current.workspace.id !== incoming.workspace.id) return incoming"), "workspace switching still replaces the full view");
  assert(source.includes("Run details"), "agent run detail is an opt-in inline disclosure");
  assert(source.includes("workspace-agent-run-events"), "agent run detail renders persisted run events");
  assert(agentRunRoute.includes("getWorkspaceAgentRunDetail"), "agent run detail has an explicit single-run API route");
  assert(agentRunRoute.includes("NextResponse.json(detail)"), "agent run detail route returns the store detail payload");
  assert(workspaceStore.includes("sourceRunId === run.id && !memory.archivedAt && isLocalWorkspaceAgentMemoryVisibleToOwner"), "local run detail filters linked memories by memory visibility");
  assert(workspaceStore.includes(".filter((memory) => isDbWorkspaceAgentMemoryVisibleToOwner(memory, ownerId))"), "DB run detail filters linked memories by owner visibility");
  assert(workspaceAgentDoc.includes("Single-run detail filters linked memories through the same user-scope owner visibility rules"), "workspace agent doc records run-detail memory visibility guardrails");
  assert(threadsRoute.includes("Thread request is invalid."), "thread create API returns explicit validation errors");
  assert(threadsRoute.includes("Thread update request is invalid."), "thread update API returns explicit validation errors");
  assert(messagesRoute.includes("Message request is invalid."), "message create API returns explicit validation errors");
  assert(tasksRoute.includes("Task request is invalid."), "task create API returns explicit validation errors");
  assert(workspacesRoute.includes("Workspace request is invalid."), "workspace create API returns explicit validation errors");
  assert(workspaceJoinRoute.includes("Workspace join request is invalid."), "workspace join API returns explicit validation errors");
  assert(workspaceJoinRoute.includes("Invite code not found."), "workspace join API returns explicit invite not-found errors");
  assert(taskUpdateRoute.includes("Task update request is invalid."), "task update API returns explicit validation errors");
  assert(taskUpdateRoute.includes("Task not found."), "task update API returns explicit not-found errors");
  assert(membersRoute.includes("Member request is invalid."), "member create API returns explicit validation errors");
  const workspaceApiRoutes = [
    workspacesRoute,
    workspaceJoinRoute,
    threadsRoute,
    messagesRoute,
    tasksRoute,
    taskUpdateRoute,
    membersRoute,
    agentsRoute,
    agentProfileRoute,
    agentConnectionsRoute,
    agentSkillsRoute,
    agentApprovalRoute,
    agentRunCancelRoute,
    agentMemoryBulkArchiveRoute,
    agentMemoryRoute,
  ];
  assert(
    workspaceApiRoutes.every((route) => !route.includes("safeParse(await request.json())")),
    "workspace API routes catch malformed JSON before validation",
  );
  assert(source.includes("readWorkspaceApiError"), "workspace client has a shared API error reader");
  assert(source.includes("response.clone().json()"), "workspace client can read JSON error responses without consuming success payloads");
  assert(source.includes('readWorkspaceApiError(response, "Agent approval could not be updated.")'), "agent approval UI preserves API JSON errors");
  assert(source.includes('readWorkspaceApiError(response, "Agent run could not be cancelled.")'), "agent cancel UI preserves API JSON errors");
  assert(source.includes('readWorkspaceApiError(response, "Agent run could not be retried.")'), "agent retry UI preserves API JSON errors");
  assert(source.includes('readWorkspaceApiError(response, "Agent could not be updated.")'), "agent profile editor preserves API JSON errors");
  assert(workspaceAgentDoc.includes("API JSON errors should survive to the workspace client"), "workspace agent doc records client error propagation");
  assert(source.includes("AgentApprovalCard"), "workspace chat renders compact inline agent approval controls");
  assert(source.includes("readWorkspaceApprovalDisplay"), "agent approval card derives calm display copy from persisted approval metadata");
  assert(source.includes("actionDescription"), "agent approval card can show product action descriptions from policy metadata");
  assert(source.includes("visibleLabel"), "agent approval card can prefer visible policy labels over raw tool names");
  assert(source.includes("approval.input"), "agent approval card can show the requested item from persisted tool input");
  assert(source.includes("Needs approval"), "agent approval card uses clear product approval copy");
  assert(source.includes("Requested action"), "agent approval card labels the action instead of only showing a tool name");
  assert(source.includes("Requested item"), "agent approval card summarizes the affected object when available");
  assert(source.includes("workspace-agent-approval-meta"), "agent approval card renders compact metadata rows");
  assert(!source.includes("JSON.stringify(pending.input"), "agent approval card does not dump raw approval input JSON by default");
  assert(source.includes("cancelAgentRun"), "workspace can cancel an agent run from inline details");
  assert(source.includes("Cancel run"), "agent run detail exposes a compact cancel action");
  assert(source.includes("/agent-runs/${run.id}/cancel"), "agent run cancel uses explicit run cancel API");
  assert(agentRunCancelRoute.includes("Agent run could not be cancelled"), "agent run cancel API returns explicit JSON errors");
  assert(source.includes("retryAgentRun"), "workspace can retry terminal agent runs from inline details");
  assert(source.includes("Retry run"), "agent run detail exposes a compact retry action");
  assert(source.includes("/agent-runs/${run.id}/retry"), "agent run retry uses explicit run retry API");
  assert(source.includes("outputMessageId"), "agent run status is attached to output messages");
  assert(source.includes("agentRunEventsByRunId"), "agent run status can summarize persisted run events");
  assert(source.includes("agentApprovalsByRunId"), "agent approvals are grouped by persisted run");
  assert(workspaceStore.includes("buildWorkspaceAgentProfileRunSnapshot"), "store snapshots agent profile state into run events");
  assert(workspaceStore.includes("agentProfileSnapshot: buildWorkspaceAgentProfileRunSnapshot"), "started run events carry profile snapshots for historical audit");
  assert(workspaceStore.includes("listDbVisibleWorkspaceThreadIds"), "DB workspace-level run listing is scoped to visible threads");
  assert(workspaceAgentDoc.includes("Workspace-level agent run listing is scoped to visible threads"), "workspace agent doc records run-list thread visibility guardrails");
  assert(source.includes("mergeAgentApprovals"), "agent approvals merge into workspace state without waiting for SSE");
  assert(agentApprovalRoute.includes("Agent approval could not be updated"), "agent approval API returns explicit JSON errors");
  assert(agentApprovalRoute.includes("Approval decision request is invalid."), "agent approval API returns explicit validation errors");
  assert(agentApprovalRoute.includes("Agent approval not found."), "agent approval API returns explicit not-found errors");
  assert(workspaceStore.includes("assertApprovalDecisionAllowedForRun"), "store rejects approval decisions after terminal run state");
  assert(workspaceAgentDoc.includes("Stale pending approval rows on terminal runs are rejected at the store boundary"), "workspace agent doc records terminal approval guardrail");
  assert(deepAgentRuntimeE2e.includes("pendingApproval"), "DeepAgent e2e covers live pending approvals");
  assert(workspaceAgentApiE2e.includes("terminal run approvals"), "agent API e2e covers stale terminal-run approval errors");
  assert(agentRunCancelRoute.includes("Agent run cancel request is invalid."), "agent run cancel API returns explicit validation errors");
  assert(agentRunCancelRoute.includes("Agent run not found."), "agent run cancel API returns explicit not-found errors");
  assert(agentRunRetryRoute.includes('message === "Agent run not found." ? 404'), "agent run retry only maps the missing-run error to 404");
  assert(workspaceAgentDoc.includes("Agent run retry API coverage now includes the unrecoverable-run path"), "workspace agent doc records unrecoverable retry API coverage");
  assert(source.includes("agentMemories?: WorkspaceAgentMemory[]"), "client can accept agent-created memories in API responses");
  assert(packageJson.includes("workspace:deepagent:e2e"), "package exposes a real DeepAgent runtime e2e script");
  assert(deepAgentRuntimeE2e.includes("PRIMORIA_WORKSPACE_DEEPAGENT_TEST_FAKE_MODEL"), "DeepAgent runtime e2e uses explicit fake-model env gating");
  assert(deepAgentRuntimeE2e.includes("PRIMORIA_WORKSPACE_DEEPAGENT_PERSISTENCE"), "DeepAgent runtime e2e exercises configured DeepAgent persistence");
  assert(deepAgentRuntimeE2e.includes("NEXT_DIST_DIR"), "DeepAgent runtime e2e uses an isolated Next distDir");
  assert(deepAgentRuntimeE2e.includes("/api/workspaces/agent-runtime/health"), "DeepAgent runtime e2e smokes the health dry-run endpoint");
  assert(agentRuntimeHealthRoute.includes("buildWorkspaceDeepAgentRuntimeHealth"), "workspace exposes a DeepAgent runtime health dry-run route");
  assert(agentRuntimeHealthRoute.includes("isWorkspaceDeepAgentOperatorAuthorized"), "DeepAgent runtime health route is protected by operator authorization");
  assert(agentRuntimeHealthRoute.includes("health.ok ? 200 : 503"), "DeepAgent runtime health route returns failing readiness as HTTP 503");
  assert(agentRuntimeHealthRouteUnit.includes("NODE_ENV: \"production\""), "DeepAgent runtime health route has production-mode smoke coverage");
  assert(agentRuntimeHealthRouteUnit.includes("unauthorized.status === 401"), "DeepAgent runtime health route smoke covers production auth rejection");
  assert(agentRuntimeHealthRouteUnit.includes("misconfigured.status === 503"), "DeepAgent runtime health route smoke covers failing production readiness");
  assert(agentRuntimeHealthRouteUnit.includes("ready.status === 200"), "DeepAgent runtime health route smoke covers passing production readiness");
  assert(agentRuntimeHealthRouteUnit.includes("secret-openai-key"), "DeepAgent runtime health route smoke asserts secrets are not leaked");
  assert(packageJson.includes("workspace:agent-runtime:health-route"), "package exposes production health route smoke script");
  assert(packageJson.includes('"workspace:agent:test"'), "package exposes a PR-safe workspace agent test bundle");
  assert(packageJson.includes("workspace.agent-triggers.unit.ts"), "workspace agent test bundle includes trigger policy tests");
  assert(packageJson.includes("workspace.agent-tools.unit.ts"), "workspace agent test bundle includes internal tool tests");
  assert(packageJson.includes("workspace.agent-mcp.unit.ts"), "workspace agent test bundle includes connection/MCP guard tests");
  assert(packageJson.includes("workspace.agent-skills.unit.ts"), "workspace agent test bundle includes skill storage tests");
  assert(packageJson.includes("workspace.agent-runtime.unit.ts"), "workspace agent test bundle includes runtime assembly tests");
  assert(packageJson.includes("workspace-client-merge.unit.ts"), "workspace agent test bundle includes client merge tests");
  assert(packageJson.includes("workspace-events.unit.ts"), "workspace agent test bundle includes realtime event hub tests");
  assert(packageJson.includes("workspace:agent:e2e:api"), "package exposes an agent API error contract e2e smoke");
  assert(packageJson.includes("workspace-agent-api.e2e.mjs"), "agent API error contract smoke is wired into package scripts");
  assert(packageJson.includes("workspace-ui-static.unit.ts"), "workspace agent test bundle includes UI/static contract tests");
  assert(packageJson.includes("workspace-agent-runtime-health-route.unit.ts"), "workspace agent test bundle includes health route contract tests");
  assert(packageJson.includes("workspace.unit.ts"), "workspace agent test bundle includes local store tests");
  assert(workspaceAgentDoc.includes("### CI Health Route Smoke"), "workspace agent doc includes deployment-facing health route CI guidance");
  assert(workspaceAgentDoc.includes("pnpm --filter @primoria/web workspace:agent-runtime:health-route"), "workspace agent doc includes the health route smoke command");
  assert(workspaceAgentDoc.includes("pnpm --filter @primoria/web workspace:agent:test"), "workspace agent doc includes the PR-safe agent test bundle command");
  assert(workspaceAgentDoc.includes("PRIMORIA_WORKSPACE_OPERATOR_TOKEN"), "workspace agent doc documents the operator token secret for production health checks");
  assert(workspaceAgentDoc.includes("PRIMORIA_WORKSPACE_DEEPAGENT_PERSISTENCE=postgres"), "workspace agent doc requires postgres persistence for production DeepAgent health checks");
  assert(workspaceAgentDoc.includes("DATABASE_URL"), "workspace agent doc documents database URL requirements for production DeepAgent health checks");
  assert(workspaceAgentDoc.includes("expected status contracts are `401`, `503`, and `200`"), "workspace agent doc documents the health route status contract");
  assert(workspaceAgentDoc.includes("PRIMORIA_WORKSPACE_DEEPAGENT_TEST_FAKE_MODEL"), "workspace agent doc warns that fake harness variables must not be present in production CI");
  assert(workspaceAgentDoc.includes("GitHub Actions"), "workspace agent doc includes a GitHub Actions CI example");
  assert(workspaceAgentDoc.includes("Do not print or persist the health JSON as an artifact"), "workspace agent doc warns against leaking diagnostic output");
  assert(workspaceAgentRuntimeHealthWorkflow.includes("pull_request:"), "workspace agent runtime health workflow runs on pull requests");
  assert(workspaceAgentRuntimeHealthWorkflow.includes("workflow_dispatch:"), "workspace agent runtime health workflow can be manually dispatched");
  assert(
    workspaceAgentRuntimeHealthWorkflow.includes("pnpm --filter @primoria/web workspace:agent-runtime:health-route"),
    "workspace agent runtime health workflow runs the production route health smoke",
  );
  assert(
    workspaceAgentRuntimeHealthWorkflow.includes("pnpm --filter @primoria/web workspace:agent:test"),
    "workspace agent runtime health workflow runs the broader PR-safe workspace agent test bundle",
  );
  assert(
    !workspaceAgentRuntimeHealthWorkflow.includes("PRIMORIA_WORKSPACE_DEEPAGENT_TEST_FAKE_MODEL"),
    "workspace agent runtime health workflow does not rely on DeepAgent fake harness env",
  );
  assert(source.includes("agentMemories: mergeAgentMemories(current.agentMemories, data.agentMemories ?? [])"), "client merges incoming agent memories by id");
  assert(source.includes("mergeMembers"), "workspace members merge into client state by id");
  assert(source.includes("mergeAgentProfiles"), "agent profiles merge into client state by id");
  assert(source.includes("mergeAgentConnections"), "agent connections merge into client state by id");
  assert(source.includes("members: mergeMembers(current.members"), "client uses member merge helper in mutation responses");
  assert(source.includes("agentProfiles: mergeAgentProfiles(current.agentProfiles"), "client uses profile merge helper in mutation responses");
  assert(source.includes("agentProfiles?: WorkspaceAgentProfile[]; agentMembers?: WorkspaceMember[]"), "agent picker can consume visible profiles from the agents API");
  assert(source.includes("members: mergeMembers(current.members, data.agentMembers ?? [])"), "agent picker merges visible agent members returned by the agents API");
  assert(source.includes("agentPickerSearchValues"), "agent picker builds searchable values from identity and capabilities");
  assert(source.includes("capability.path"), "agent picker search can match skill capability paths");
  assert(source.includes("skillLabelForPath(capability.path)"), "agent picker search can match product skill labels");
  assert(source.includes("capability.toolName"), "agent picker search can match tool and connection capability names");
  assert(source.includes("formatAgentLibraryMemory(memoryScope)"), "agent picker search can match product memory scope labels");
  assert(!source.includes("newThreadAgentTriggerMode"), "workspace create-chat form does not expose per-room agent trigger mode");
  assert(!source.includes("Agent mode"), "workspace create-chat form does not expose an agent mode selector");
  assert(!source.includes("formatAgentTriggerMode(activeThread.agentTriggerMode)"), "workspace room header does not surface the active agent mode");
  assert(!source.includes("updateThreadAgentMode"), "workspace does not expose an existing-room agent mode editor");
  assert(!source.includes("Room agent mode"), "workspace panel does not expose an agent mode editor");
  assert(!source.includes("updateThreadAllowedAgents"), "workspace does not expose an existing-room agent allowlist editor");
  assert(workspaceStore.includes("agents.slice(0, 1)"), "workspace run execution caps default visible agent responses at one per message");
  assert(!source.includes("WorkspaceRoomSettingsPanel"), "workspace no longer renders room settings as a dedicated visible panel");
  assert(!source.includes("Chat settings"), "workspace panel no longer carries room settings product copy");
  assert(!source.includes("Agent access"), "workspace panel no longer exposes agent access controls");
  assert(!source.includes("workspace-room-settings-panel"), "workspace room settings panel class hook is removed");
  assert(!source.includes("workspace-room-agent-access"), "workspace room agent access class hook is removed");
  assert(!source.includes("<details className=\"workspace-room-agent-allowlist\""), "workspace header no longer hides agent access in a nested details control");
  assert(!source.includes("formatRoomAllowedAgents(activeThread, agentMembers)"), "workspace room header does not summarize the active agent allowlist");
  assert(threadsRoute.includes("mention_only"), "thread API still supports mention-only room agent mode for compatibility");
  assert(threadsRoute.includes("quiet_review"), "thread API still supports quiet-review room agent mode for compatibility");
  assert(threadsRoute.includes("allowedAgentProfileIds"), "thread API accepts room agent allowlist updates");
  assert(threadsRoute.includes("export async function PATCH"), "thread API supports updating existing chat settings");
  assert(threadsRoute.includes("updateWorkspaceThread"), "thread API delegates setting updates to the workspace store");
  assert(workspaceStore.includes("assertWorkspaceThreadAllowedAgentProfileIdsForView"), "local store validates room agent allowlist profile ids before persistence");
  assert(workspaceStore.includes("assertDbWorkspaceThreadAllowedAgentProfileIds"), "DB store validates room agent allowlist profile ids before persistence");
  assert(workspaceStore.includes("Allowed agent must be a member of this workspace."), "room agent allowlist rejects non-member agent profiles");
  assert(agentProfileService.includes("isDbAgentProfileResolvableInWorkspace"), "DB store uses an explicit agent profile visibility resolver");
  assert(agentProfileService.includes("profile.visibility === \"private\""), "DB profile resolver treats private saved agents as owner-scoped");
  assert(workspaceStore.includes("memberProfileRows"), "DB workspace view loads profile records referenced by current workspace members");
  assert(agentProfileService.includes("memberProfileIds.has(profile.id)"), "DB profile resolver allows profiles already participating as workspace members");
  assert(workspaceStore.includes("if (member.agentProfileId) await requireWorkspaceAgentProfile(ownerId, input.workspaceId, member.agentProfileId);"), "member creation validates agent profile references before persistence");
  assert(agentRuntime.includes("workspaceId: input.thread.workspaceId"), "runtime skill resolution uses the current run workspace, not only the profile home workspace");
  assert(agentRuntime.includes("const workspaceId = options.workspaceId ?? profile.workspaceId"), "runtime subagent selection can be scoped to the current run workspace");
  assert(workspaceAgentDoc.includes("workspace-scoped skills are resolved against the current run workspace"), "workspace agent doc records cross-workspace personal agent skill scoping");
  assert(workspaceAgentDoc.includes("private saved agents cannot be added or edited by another workspace member via profile id"), "workspace agent doc records private profile id guardrails");
  assert(workspaceStore.includes("assertAgentSubagentCapabilities"), "store validates delegate subagent capabilities before profile persistence");
  assert(workspaceStore.includes("Agent cannot delegate to itself."), "store rejects self-delegating agent profiles");
  assert(workspaceAgentDoc.includes("subagent capabilities are validated before profile persistence"), "workspace agent doc records delegate capability persistence guardrails");
  assert(source.includes("agentConnections: mergeAgentConnections(current.agentConnections"), "client uses connection merge helper in mutation responses");
  assert(workspaceStore.includes("requireDbWorkspaceOwner"), "DB store has an explicit workspace owner permission helper");
  assert(workspaceAccessService.includes("Workspace owner permission is required."), "workspace-scoped connection writes require owner permission");
  assert(workspaceAgentDoc.includes("workspace-scoped agent connections require workspace-owner permission"), "workspace agent doc records workspace connection owner guardrails");
  assert(source.includes("mergeArtifacts"), "workspace artifacts merge into client state without waiting for SSE");
  assert(source.includes("artifacts: mergeArtifacts(current.artifacts"), "client merges incoming first-class artifacts by id");
  assert(source.includes("fallbackPollingInterval"), "workspace realtime fallback has a single named polling path");
  assert(source.includes("stopFallbackPolling"), "workspace realtime can cancel fallback polling when streaming recovers");
  assert(source.includes("scheduleStreamReconnect"), "workspace realtime retries EventSource after fallback starts");
  assert(source.includes("clearReconnectTimer"), "workspace realtime clears reconnect timers on recovery and cleanup");
  assert(source.includes("window.clearInterval(fallbackPollingInterval)"), "workspace realtime clears fallback polling interval explicitly");
  assert(source.includes("window.clearTimeout(reconnectTimeout)"), "workspace realtime clears reconnect timeout explicitly");
  assert(source.includes("workspaceIdRef"), "workspace ignores stale realtime payloads after switching workspaces");
  assert(source.includes("data.workspace.id !== workspaceIdRef.current"), "workspace stale realtime guard compares payload workspace id");
  assert(source.includes("pickWorkspaceThread"), "workspace chooses the active chat from recent message activity instead of blindly selecting the first room");
  assert(source.includes("readCachedActiveThreadId"), "workspace can restore the last active chat when it still has loaded activity");
  assert(source.includes("writeCachedActiveThreadId"), "workspace persists the user's active chat after real workspace data is ready");
  assert(!source.includes("threads[0]?.id"), "workspace no longer defaults active chat selection to the first thread");
  assert(workspaceStore.includes("getWorkspaceShellViewFromDb"), "workspace shell view has a dedicated DB loader");
  assert(workspaceStore.includes(".limit(MESSAGE_WINDOW_PER_THREAD)"), "workspace shell view includes a bounded recent message window");
  assert(workspaceEventsRoute.includes("view.artifacts.map"), "workspace stream version tracks first-class artifacts");
  assert(workspaceEventsRoute.includes("view.agentMemories.map"), "workspace stream version tracks reviewable agent memories");
  assert(workspaceEventsRoute.includes("view.agentConnections.map"), "workspace stream version tracks connection registry changes");
  assert(workspaceEventsRoute.includes("member.agentProfileId"), "workspace stream version tracks agent member profile bindings");
  assert(workspaceEventsRoute.includes("heartbeatHub"), "workspace stream uses a lightweight heartbeat instead of polling full views for keepalive");
  assert(!workspaceEventsRoute.includes("setInterval(() => void tickHub(hubKey), 3000)"), "workspace stream does not poll the full workspace view every 3 seconds");
  assert(source.includes("agentArtifacts?: WorkspaceArtifact[]"), "client can accept agent-created first-class artifacts in API responses");
  assert(source.includes("WorkspaceStartState"), "workspace has a real empty-start surface for workspaces with no chats");
  assert(source.includes("No private chats yet"), "workspace start state labels private-chat empty states accurately");
  assert(source.includes("Group rooms stay available for shared context."), "workspace start state avoids claiming the whole workspace is empty when only private chats are empty");
  assert(source.includes('onOpenMemberPicker("Person")'), "empty workspace first actions can open the People picker directly");
  assert(source.includes('onOpenMemberPicker("Agent")'), "empty workspace first actions can open the Agent picker directly");
  assert(source.includes("Add a person"), "empty workspace first actions include adding a person");
  assert(source.includes("Add an agent"), "empty workspace first actions include adding an agent");
  assert(source.includes("ActiveChatEmptyState"), "empty active chats use an actionable real-data empty state");
  assert(source.includes("onAddPerson"), "empty active chat can open the People picker");
  assert(source.includes("onAddAgent"), "empty active chat can open the Agent picker");
  assert(source.includes("onCreateTask"), "empty active chat can start a real task");
  assert(source.includes("workspace-empty-actions"), "empty chat first actions have a dedicated layout hook");
  assert(source.includes("agentCreateMode"), "agent picker supports template and custom agent creation modes");
  assert(source.includes("Custom agent"), "agent picker exposes a custom agent creation option");
  assert(source.includes("Agent purpose"), "custom agent creation captures agent purpose");
  assert(source.includes("Agent behavior"), "custom agent creation captures behavior instructions");
  assert(source.includes("Agent visibility"), "custom agent creation captures personal vs workspace visibility");
  assert(source.includes("Personal agent"), "agent builder can create personal/private agents");
  assert(source.includes("Workspace agent"), "agent builder can create workspace-visible agents");
  assert(source.includes("Save to my agents"), "personal agent creation can save to library without adding as a member");
  assert(source.includes("Agent saved to My agents"), "personal agent profile-only save gives clear success feedback");
  assert(source.includes("agentFeedback"), "agent picker tracks contextual success feedback separately from errors");
  assert(source.includes("workspace-agent-feedback"), "agent picker renders a dedicated non-error feedback row");
  assert(source.includes('agentVisibility === "private" ? "Save to my agents" : "Add"'), "agent picker submit copy makes personal-agent save behavior explicit");
  assert(source.includes("memberPickerQuery"), "shared + picker tracks a search query");
  assert(source.includes('aria-label="Search people or agents"'), "shared + picker exposes a search input");
  assert(source.includes("filteredAgentTemplates"), "agent template picker rows are filtered by the shared query");
  assert(source.includes("filteredSavedAgentProfiles"), "saved agent picker rows are filtered by the shared query");
  assert(source.includes("agentPickerMatchesQuery"), "agent picker search uses a dedicated match helper");
  assert(source.includes("filteredPeopleMembers"), "people picker lists existing non-agent members from real workspace data");
  assert(source.includes("startDirectChatWithPerson"), "people picker can start or reuse a private chat with an existing person");
  assert(source.includes("resetMemberPicker"), "shared + picker clears stale search and selection state after completing a pick");
  assert(source.includes("openMemberPicker"), "shared + picker opens through a reset helper instead of preserving stale query state");
  assert(source.includes("setSelectedAgentTemplateKey(\"\")"), "shared + picker reset clears stale selected template state");
  assert(source.includes("openMemberPicker(\"Person\")"), "header invite and empty states can explicitly open the People picker after an Agent flow");
  assert(source.includes("onClick={() => (memberPickerOpen ? resetMemberPicker() : openMemberPicker())}"), "member panel + button resets picker state when reopening");
  assert(source.includes("workspace-people-picker-list"), "people picker has a dedicated existing-member list hook");
  assert(source.includes("Private chat"), "people picker uses private chat product copy for existing members");
  assert(source.includes("Add existing agent"), "agent picker can add an existing saved agent profile");
  assert(source.includes("formatAgentPickerCapabilityHints(template.capabilities, template.memoryScope)"), "agent template picker rows show compact capability hints");
  assert(source.includes("formatAgentPickerCapabilityHints(profile.capabilities, profile.memoryScope)"), "saved agent picker rows show compact capability hints");
  assert(source.includes("workspace-agent-picker-hints"), "agent picker has a dedicated capability hint hook");
  assert(source.includes("agentAddTarget"), "agent picker tracks whether to add an agent to the workspace or start a direct chat");
  assert(source.includes("Start private chat"), "agent picker can start a private direct chat with the selected agent");
  assert(source.includes("createAgentDirectThread"), "agent picker creates a real direct thread for private agent chats");
  assert(source.includes("participantIds: [member.id]"), "agent direct-chat creation persists the selected agent member as a participant");
  assert(source.includes("ensureAgentInActiveRoom"), "agent picker can add a workspace agent to the active room allowlist");
  assert(source.includes('agentAddTarget === "workspace" && agentMember'), "agent picker updates room context only for workspace adds with real members");
  assert(source.includes("activeThread.allowedAgentProfileIds"), "agent active-room add respects room allowlist settings");
  assert(source.includes("agentProfiles.filter"), "agent picker derives saved agents from real workspace profiles");
  assert(source.includes("profileId: selectedExistingAgentProfileId"), "agent picker can POST an existing profile id instead of cloning a template");
  assert(source.includes("member?: WorkspaceMember"), "agent creation response handles profile-only personal agents without mock member data");
  assert(navRail.includes('href: "/workspace/agents"'), "primary navigation exposes the dedicated agent manager");
  assert(source.includes('href="/workspace/agents"'), "workspace member panel links to the dedicated agent manager");
  assert(agentManagerPage.includes("WorkspaceAgentManager"), "workspace agents route renders the dedicated agent manager");
  assert(agentManagerPage.includes("app-shell workspace-shell"), "workspace agents route uses the compact workspace shell on mobile");
  assert(agentManagerPage.includes("listWorkspaceAgentTemplates"), "workspace agents route loads template data on the server");
  assert(agentManagerPage.includes("getWorkspaceView"), "workspace agents route loads real workspace profiles and members");
  assert(agentManager.includes("Agent hub"), "agent manager presents a dedicated lightweight hub");
  assert(agentManager.includes("My agents"), "agent manager separates saved agent management into its own tab");
  assert(agentManager.includes("Store"), "agent manager separates templates and marketplace discovery into a store tab");
  assert(agentManager.includes("What should your agent do?"), "agent manager supports prompt-first agent creation");
  assert(agentManager.includes("AI create"), "agent manager can draft an agent from a natural-language prompt");
  assert(agentManager.includes("/agent-draft"), "agent manager uses the agent draft API for AI-assisted creation");
  assert(agentManager.includes("Customize"), "agent manager can apply store templates to the simple creator");
  assert(agentManager.includes("Install to workspace"), "agent store can install a template as a workspace agent");
  assert(agentManager.includes("Save to My agents"), "agent store can save a template as a personal agent");
  assert(agentManager.includes("selectedStoreTemplate"), "agent store keeps a selected template detail panel");
  assert(agentManager.includes("preservedCapabilities"), "agent manager preserves template and hidden capabilities while editing simple tool choices");
  assert(agentManager.includes("readPreservedCapabilityInputs(template.capabilities)"), "store customize keeps template skill capabilities");
  assert(agentManager.includes("readPreservedCapabilityInputs(profile.capabilities)"), "profile editing keeps non-visible or non-editable capabilities");
  assert(agentManager.includes("memoryScope"), "agent manager saves the selected memory scope instead of hardcoding thread memory");
  assert(agentManager.includes("findInstalledTemplateProfile"), "agent store detects installed templates before creating another copy");
  assert(agentManager.includes("aria-pressed"), "agent store cards expose selected state to assistive technology");
  assert(agentManager.includes("agentQuery"), "agent manager keeps My agents search separate from Store search");
  assert(agentManager.includes("storeQuery"), "agent manager keeps Store search separate from My agents search");
  assert(agentManager.includes("Save to my agents"), "agent manager can save private personal agents");
  assert(agentManager.includes("Add"), "agent manager can add existing saved agents to the workspace");
  assert(agentManager.includes('editingId ? "PATCH" : "POST"'), "agent manager can edit existing profiles through the agent API");
  assert(agentManager.includes("method: \"DELETE\""), "agent manager can delete saved agent profiles");
  assert(source.includes("dedupeVisibleAgentProfiles"), "agent library panel dedupes repeated template agent profiles before rendering");
  assert(!source.includes("<WorkspaceAgentLibraryPanel"), "workspace side panel does not render the agent library dashboard");
  assert(!source.includes("agentProfiles={visibleAgentProfiles}"), "workspace side panel no longer mounts agent library profile data");
  assert(!source.includes("agentRuns={view.agentRuns}"), "workspace side panel no longer mounts agent run history");
  assert(!source.includes("onMentionAgent={mentionAgentFromLibrary}"), "workspace side panel no longer exposes agent library mention actions");
  assert(!source.includes("<WorkspaceAgentConnectionPanel"), "workspace side panel does not render the connections dashboard");
  assert(source.includes("agentConnections: mergeAgentConnections(current.agentConnections, [data.connection])"), "connection creation merges real API data into workspace state");
  assert(source.includes("updateWorkspaceAgentConnectionStatus"), "workspace can disable or re-enable saved connections");
  assert(source.includes('status: connection.status === "disabled" ? "available" : "disabled"'), "connection toggle persists explicit status changes");
  assert(workspaceAgentDoc.includes("Disabling a connection must stop future profile allowlisting and runtime tool use"), "workspace agent doc captures disabled-connection runtime/profile semantics");
  assert(workspaceAgentDoc.includes("Disabled connections stay visible as registry/audit records"), "workspace agent doc captures disabled-connection audit visibility");
  assert(source.includes("/agent-connections"), "connections panel uses the explicit agent connections API");
  assert(source.includes("Allowed connection tools"), "connections panel captures an explicit tool allowlist");
  assert(source.includes("AgentConnectionControls"), "agent builder exposes per-agent connection tool controls");
  assert(source.includes("Connections this agent can use"), "agent builder labels external connection tools in product language");
  assert(source.includes("External connection tools always need approval before use."), "agent builder explains connection approval semantics before selection");
  assert(source.includes("External / approval required"), "agent builder labels each connection tool as external and approval-gated");
  assert(source.includes('connections.filter((connection) => connection.status !== "disabled" && connection.allowedToolNames.length)'), "agent builder hides disabled or empty connections from per-agent tool selection");
  assert(source.includes("agentConnectionToolKeys"), "new custom agent form tracks selected connection tools");
  assert(source.includes("agentEditConnectionToolKeys"), "agent editor tracks selected connection tools");
  assert(source.includes("selectedConnectionToolKeys"), "agent capability payload includes selected connection tools");
  assert(source.includes("readAgentConnectionToolKeys"), "agent editor reads existing mcp_tool capabilities into connection controls");
  assert(source.includes("filterAvailableAgentConnectionToolKeys"), "agent create/edit payloads drop revoked connection tool selections before saving");
  assert(source.includes("canPreserveHiddenAgentCapabilities"), "agent editor can save visible profile fields while preserving hidden capabilities");
  assert(source.includes("...(capabilityPayload ? { capabilities: capabilityPayload } : {})"), "agent editor omits capabilities when preserving hidden capability rows");
  assert(source.includes("connectionToolKey"), "agent builder uses stable connection tool selection keys");
  assert(source.includes("agentVisibility"), "new custom agent form tracks visibility explicitly");
  assert(source.includes("selectedExistingAgentProfileId"), "agent picker tracks selected existing saved agent profile");
  assert(source.includes("agentEditVisibility"), "agent editor tracks visibility explicitly");
  assert(source.includes("memoryScope"), "custom agent creation sends an explicit memory scope");
  assert(source.includes("editingAgentProfileId"), "member list supports editing an existing agent profile");
  assert(source.includes("saveAgentProfileEdit"), "agent profile edits are saved through the workspace agent API");
  assert(source.includes("Edit agent"), "agent members expose a compact edit action");
  assert(source.includes("Agent edit purpose"), "agent profile edit captures updated purpose");
  assert(source.includes("Agent edit behavior"), "agent profile edit captures updated behavior");
  assert(source.includes("Agent edit visibility"), "agent profile edit captures updated visibility");
  assert(source.includes("Allowed actions"), "agent builder exposes allowed action controls");
  assert(source.includes("AgentActionControls"), "agent builder uses a reusable grouped action control component");
  assert(source.includes("Context actions"), "agent action controls group read/context capabilities");
  assert(source.includes("Task actions"), "agent action controls group task capabilities");
  assert(source.includes("Learning artifact actions"), "agent action controls group artifact-producing capabilities");
  assert(source.includes("Memory actions"), "agent action controls group memory capabilities");
  assert(source.includes("workspace-agent-action-group"), "agent action groups have dedicated styling hooks");
  assert(source.includes("workspace-agent-edit-actions"), "agent edit footer uses a specific class instead of styling every direct div");
  assert(source.includes("Can search workspace messages"), "agent builder can toggle workspace message search tool");
  assert(source.includes("search_workspace_messages"), "agent capability payload can include workspace message search tool");
  assert(source.includes("Can summarize chat"), "agent builder can toggle read-only summarize tool");
  assert(source.includes("Can create tasks"), "agent builder can toggle task creation tool");
  assert(source.includes("Create task approval"), "agent builder can configure task creation approval");
  assert(source.includes("Can update tasks"), "agent builder can toggle task update tool");
  assert(source.includes("update_workspace_task"), "agent capability payload can include approved task update tool");
  assert(source.includes("function formatTaskAssigneeOption"), "task assignee labels can identify people and agents explicitly");
  assert(source.includes("Agent collaborator"), "task assignee picker exposes agents as task collaborators");
  assert(source.includes("Person collaborator"), "task assignee picker exposes people as task collaborators");
  assert(source.includes("Can share learning apps"), "agent builder can toggle learning app sharing tool");
  assert(source.includes("share_learning_app"), "agent capability payload can include approved app sharing tool");
  assert(source.includes("Can save reviewable memories"), "agent builder can toggle reviewable memory tool");
  assert(source.includes("save_agent_memory"), "agent capability payload can include the guarded memory tool");
  assert(workspaceStore.includes("function isAutomaticAgentRunMemoryScope"), "workspace store names the automatic run-memory scope boundary");
  assert(workspaceStore.includes('return scope === "thread" || scope === "workspace"'), "automatic run-summary memories are limited to thread and workspace scopes");
  assert(workspaceAgentDoc.includes("`user`-scope runs do not auto-write memory"), "workspace agent doc states user-scope runs cannot auto-write memory");
  assert(workspaceStore.includes("assertDbWorkspaceAgentMemorySourceVisibility"), "DB memory creation validates source run/message visibility");
  assert(agentMemoryService.includes("Memory source run must belong to the memory thread."), "memory provenance rejects mismatched thread source runs");
  assert(workspaceAgentDoc.includes("Memory source provenance is validated before persistence"), "workspace agent doc records memory source provenance guardrails");
  assert(agentMemoryService.includes("isDbWorkspaceAgentMemoryVisibleToOwner"), "DB workspace view filters user-scope memories to their owner");
  assert(workspaceAgentDoc.includes("User-scope memories are owner-visible only"), "workspace agent doc records user-scope memory visibility guardrails");
  assert(source.includes("Can create practice quizzes"), "agent builder can toggle quiz generation tool");
  assert(source.includes("create_quiz"), "agent capability payload can include quiz generation tool");
  assert(source.includes("Can generate course drafts"), "agent builder can toggle course generation tool");
  assert(source.includes("generate_course"), "agent capability payload can include approved course generation tool");
  assert(source.includes("Can render interactive widgets"), "agent builder can toggle interactive widget rendering tool");
  assert(source.includes("render_interactive_widget"), "agent capability payload can include approved widget rendering tool");
  assert(source.includes("Can save learning artifacts"), "agent builder can toggle artifact saving tool");
  assert(source.includes("save_learning_artifact"), "agent capability payload can include approved artifact saving tool");
  assert(source.includes("agentCanCreateQuiz"), "new custom agent form tracks quiz action capability");
  assert(source.includes("agentEditCanCreateQuiz"), "agent editor tracks quiz action capability");
  assert(source.includes("agentCanSearchMessages"), "new custom agent form tracks search action capability");
  assert(source.includes("agentEditCanSearchMessages"), "agent editor tracks search action capability");
  assert(source.includes("agentCanUpdateTasks"), "new custom agent form tracks task update action capability");
  assert(source.includes("agentEditCanUpdateTasks"), "agent editor tracks task update action capability");
  assert(source.includes("agentCanShareApps"), "new custom agent form tracks app sharing action capability");
  assert(source.includes("agentEditCanShareApps"), "agent editor tracks app sharing action capability");
  assert(source.includes("agentCanSaveMemory"), "new custom agent form tracks memory-write capability separately from memory scope");
  assert(source.includes("agentEditCanSaveMemory"), "agent editor tracks memory-write capability separately from memory scope");
  assert(agentsRoute.includes("profileId: z.string"), "agent API accepts existing profile ids for saved-agent add flow");
  assert(agentsRoute.includes("if (body.profileId)"), "agent API branches existing saved profile add flow before creating a new profile");
  assert(agentsRoute.includes("Agent profile not found"), "agent API rejects unknown saved agent profile ids");
  assert(agentsRoute.includes("Agent request is invalid."), "agent collection API returns explicit JSON validation errors");
  assert(agentsRoute.includes("Agent could not be saved."), "agent collection API returns explicit JSON persistence errors");
  assert(agentsRoute.includes("agentRouteErrorStatus"), "agent collection API maps store validation errors to explicit HTTP statuses");
  assert(agentsRoute.includes('lower.includes("approval")'), "agent collection API treats approval policy failures as validation errors");
  assert(agentProfileRoute.includes("Agent update request is invalid."), "agent profile API returns explicit JSON validation errors");
  assert(agentProfileRoute.includes("Agent could not be updated."), "agent profile API returns explicit JSON persistence errors");
  assert(agentProfileRoute.includes("agentRouteErrorStatus"), "agent profile API maps store validation errors to explicit HTTP statuses");
  assert(agentProfileRoute.includes('lower.includes("approval")'), "agent profile API treats approval policy failures as validation errors");
  assert(agentConnectionsRoute.includes("Connection request is invalid."), "agent connections API returns explicit JSON validation errors");
  assert(agentConnectionsRoute.includes("Connection could not be saved."), "agent connections API returns explicit JSON persistence errors");
  assert(agentConnectionsRoute.includes("Connection update request is invalid."), "agent connections API returns explicit JSON update validation errors");
  assert(agentConnectionsRoute.includes("Connection could not be updated."), "agent connections API returns explicit JSON update errors");
  assert(agentSkillsRoute.includes("Skill request is invalid."), "agent skills API returns explicit JSON validation errors");
  assert(agentSkillsRoute.includes("Skill could not be saved."), "agent skills API returns explicit JSON persistence errors");
  assert(agentSkillsRoute.includes("Skill update request is invalid."), "agent skills API returns explicit JSON update validation errors");
  assert(agentSkillsRoute.includes("Skill could not be updated."), "agent skills API returns explicit JSON update errors");
  assert(agentSkillsRoute.includes("Skill delete request is invalid."), "agent skills API returns explicit JSON delete validation errors");
  assert(agentsRoute.includes("existingMember"), "agent API reuses an existing member when the saved agent is already added");
  assert(agentsRoute.includes("agentProfiles: view.agentProfiles"), "agent API lists visible existing agent profiles");
  assert(agentsRoute.includes("agentMembers: view.members.filter"), "agent API lists visible agent members");
  assert(agentsRoute.includes('profile.visibility === "private"'), "agent API keeps private personal agents profile-only by default");
  assert(agentsRoute.includes("return NextResponse.json({ profile })"), "agent API can return profile-only personal agent payloads");
  assert(source.includes("agentDelegateProfileIds"), "agent builder tracks delegate agents for new custom agents");
  assert(source.includes("agentEditDelegateProfileIds"), "agent editor tracks delegate agents for existing profiles");
  assert(source.includes("Agents this agent can delegate to"), "agent builder exposes delegate-agent capability controls");
  assert(source.includes("toggleAgentDelegate"), "agent builder can toggle delegate-agent capabilities");
  assert(source.includes("readAgentDelegateProfileIds"), "agent editor reads existing subagent capabilities");
  assert(source.includes("AgentDelegateControls"), "agent builder renders delegate-agent controls");
  assert(source.includes("selectedDelegateProfileIds"), "agent capability payload includes selected delegate agents");
  assert(source.includes("buildAgentCapabilityInputs"), "agent create/edit payloads derive explicit capability inputs");
  assert(source.includes("Choose at least one way this agent can help."), "custom agent creation guards against empty capability selections");
  assert(!source.includes('`/skills/${slugifyAgentPath(input.name || "custom-agent")}`'), "custom agent creation does not invent a fake skill path when no skill is selected");
  assert(!source.includes('from "@/lib/workspaces/store"'), "client component must not import server workspace store code");
  assert(source.includes('from "@/lib/workspaces/agent-profile-guardrails"'), "client reads agent guardrail constants from a browser-safe module");
  assert(agentProfileRules.includes('from "./agent-profile-guardrails"'), "store reads agent guardrail constants from the shared module");
  assert(agentProfileGuardrails.includes("AGENT_PURPOSE_MAX_LENGTH"), "agent profile guardrail module exports purpose length");
  assert(agentProfileGuardrails.includes("AGENT_BEHAVIOR_MAX_LENGTH"), "agent profile guardrail module exports behavior length");
  assert(workspaceStore.includes("assertAgentProfileTextGuardrails"), "store validates custom agent purpose and behavior guardrails");
  assert(workspaceStore.includes("assertAgentSkillCapabilityPaths"), "store validates agent skill source/path guardrails before persistence");
  assert(workspaceStore.includes("assertAgentInternalToolCapabilities"), "store validates internal tool names before persistence");
  assert(workspaceStore.includes("assertAgentConnectionToolCapabilities"), "store validates external connection tool approval before persistence");
  assert(agentProfileRules.includes("Unknown internal tool capability."), "store rejects unknown internal tool capabilities");
  assert(agentProfileRules.includes("isWorkspaceInternalToolName(capability.toolName)"), "store uses the typed internal tool policy whitelist");
  assert(agentProfileRules.includes("approvalRank(capability.approval)"), "store compares configured approval against policy minimums");
  assert(agentProfileRules.includes("Internal tool approval cannot be weaker than policy."), "store rejects internal tool approval downgrades");
  assert(agentProfileRules.includes("External connection tools always require approval."), "store rejects external connection approval downgrades");
  assert(agentProfileRules.includes("WORKSPACE_INTERNAL_TOOL_POLICIES[capability.toolName]"), "store reads internal tool policy approval defaults");
  assert(agentProfileRules.includes("Skill source does not match path."), "store rejects mismatched agent skill source/path pairs");
  assert(agentProfileRules.includes("System skill not found."), "store rejects unknown system skill capabilities before persistence");
  assert(agentProfileRules.includes("resolveWorkspaceAgentSkillPath(capability.path)"), "store resolves system skill ids before persisting profile capabilities");
  assert(agentProfileRules.includes('capability.source === "system"'), "store validates system skill capabilities explicitly");
  assert(agentProfileRules.includes('capability.path.startsWith(`/workspace-skills/${workspaceId}/`)'), "store scopes workspace skill paths to the current workspace");
  assert(agentProfileRules.includes('capability.path.startsWith(`/user-skills/${ownerId}/`)'), "store scopes user skill paths to the current owner");
  assert(agentProfileRules.includes("AGENT_PURPOSE_MAX_LENGTH"), "store uses one explicit custom agent purpose length limit");
  assert(agentProfileRules.includes("AGENT_BEHAVIOR_MAX_LENGTH"), "store uses one explicit custom agent behavior length limit");
  assert(source.includes("maxLength={AGENT_PURPOSE_MAX_LENGTH}"), "agent purpose inputs expose the store-backed length limit");
  assert(source.includes("maxLength={AGENT_BEHAVIOR_MAX_LENGTH}"), "agent behavior inputs expose the store-backed length limit");
  assert(agentProfileRules.includes("Custom agents must include a purpose."), "custom agent creation rejects missing explicit purpose");
  assert(agentProfileRules.includes("Agent purpose is too long."), "custom agent creation rejects overlong purpose");
  assert(agentProfileRules.includes("Agent behavior cannot be blank."), "agent profile updates reject blank behavior text");
  assert(agentProfileRules.includes("Agent behavior is too long."), "agent profile updates reject overlong behavior text");
  assert(workspaceAgentDoc.includes("Custom agent purpose and behavior are now explicit guardrails"), "workspace agent doc records custom agent text guardrails");
  assert(workspaceAgentDoc.includes("Agent skill capability paths are validated before persistence"), "workspace agent doc records skill path/source guardrails");
  assert(workspaceAgentDoc.includes("Agent internal tool capabilities are validated against Primoria's typed tool policy map"), "workspace agent doc records internal tool whitelist guardrails");
  assert(workspaceAgentDoc.includes("Internal tool approval cannot be weaker than the tool policy default"), "workspace agent doc records approval downgrade guardrails");
  assert(workspaceAgentDoc.includes("External connection tool capabilities now require `always` approval before persistence"), "workspace agent doc records external connection approval guardrails");
  assert(workspaceAgentDoc.includes("must not invent a fake skill path"), "workspace agent doc captures the no-fake-skill custom agent guardrail");
  assert(workspaceAgentDoc.includes("The shared `+` add flow and inline profile editor are implemented"), "workspace agent doc records current add-flow/editor implementation status");
  assert(!workspaceAgentDoc.includes("The add flow and inline profile editor are partially implemented"), "workspace agent doc does not keep stale partial add-flow/editor status");
  assert(workspaceAgentDoc.includes("DB-backed workspace skills resolve by workspace scope for collaborators, while mutation stays owner-scoped"), "workspace agent doc records shared workspace skill read vs owner mutation semantics");
  assert(agentSkillStorage.includes("dbSkillMutationWhere"), "DB skill backend separates shared workspace skill reads from owner-scoped mutations");
  assert(workspaceAgentDoc.includes("Editing a saved personal agent from any workspace"), "workspace agent doc captures cross-workspace personal-agent edit semantics");
  assert(workspaceAgentDoc.includes("Shared workspace agent profile edits are owner/admin-scoped"), "workspace agent doc records shared workspace agent edit ownership");
  assert(workspaceStore.includes("assertCanManageWorkspaceAgentProfile"), "store gates shared workspace agent profile edits by owner/admin authority");
  assert(agentProfilePersistence.includes("ownerId: profileOwnerId"), "agent capability rows remain owned by the profile owner during delegated edits");
  assert(workspaceAgentDoc.includes("Capability rows remain owned by the profile owner"), "workspace agent doc records capability owner audit semantics");
  assert(workspaceStore.includes("filterAgentCapabilitiesByVisibleConnections"), "workspace views filter mcp_tool capability metadata by visible connections");
  assert(workspaceStore.includes("listDbVisibleAgentProfileIds"), "workspace capability views can filter delegate capabilities by visible profiles");
  assert(workspaceStore.includes("mergeHiddenReferenceCapabilityInputsForDbUpdate"), "profile updates preserve hidden reference capabilities owned by another visible profile owner");
  assert(workspaceAgentDoc.includes("Normal workspace views also filter `mcp_tool` profile capability metadata by the viewer's visible connections"), "workspace agent doc records hidden personal connection capability filtering");
  assert(workspaceAgentDoc.includes("Profile lookup and edit responses use the same visible-connection filter"), "workspace agent doc records hidden personal connection filtering for profile mutations");
  assert(workspaceAgentDoc.includes("Hidden delegate `subagent` capability rows follow the same rule"), "workspace agent doc records hidden private delegate capability filtering");
  assert(workspaceAgentDoc.includes("Capability edits preserve hidden personal-connection `mcp_tool` rows and hidden delegate `subagent` rows"), "workspace agent doc records non-destructive hidden reference capability edits");
  assert(workspaceAgentDoc.includes("The inline profile editor can save visible identity/purpose/behavior/scope fields"), "workspace agent doc records hidden-capability profile edit behavior");
  assert(workspaceAgentDoc.includes("memory review, approval decision, and run cancel APIs should return explicit JSON errors"), "workspace agent doc captures current API error contracts");
  assert(source.includes("AGENT_SKILL_OPTIONS"), "agent builder exposes learning skill presets");
  assert(source.includes("Ways this agent works"), "agent builder shows skills as ways the agent works");
  assert(source.includes("toggleAgentSkill"), "agent builder can toggle selected skills");
  assert(source.includes("selectedSkillPaths"), "agent capabilities include explicit selected skill paths");
  assert(source.includes("workspaceAgentSkills"), "agent builder keeps workspace/user skills in client state");
  assert(source.includes("loadWorkspaceAgentSkills"), "agent builder loads workspace/user skills from API");
  assert(source.includes("createWorkspaceAgentSkill"), "agent builder can create custom workspace/user skills");
  assert(source.includes("/agent-skills"), "agent skills use explicit workspace skill API");
  assert(source.includes("Custom skill name"), "agent builder captures custom skill name");
  assert(source.includes("Custom skill instructions"), "agent builder captures custom skill instructions");
  assert(source.includes("workspace-agent-skill-create"), "agent builder renders compact skill creation UI");
  assert(source.includes("customSkillSource"), "agent builder tracks workspace vs personal skill source for new agents");
  assert(source.includes("customEditSkillSource"), "agent profile editor tracks workspace vs personal skill source");
  assert(source.includes("Custom skill source"), "agent builder exposes a custom skill source selector");
  assert(source.includes("Personal skill"), "agent builder can create personal/user skills");
  assert(source.includes("Workspace skill"), "agent builder can create workspace-shared skills");
  assert(source.includes("formatWorkspaceAgentSkillSource"), "agent builder formats stored skill source labels");
  assert(source.includes("workspace-agent-skill-source"), "agent builder renders a source chip for stored skills");
  assert(source.includes("updateWorkspaceAgentSkill"), "agent builder can update custom skills");
  assert(source.includes("deleteWorkspaceAgentSkill"), "agent builder can delete custom skills");
  assert(source.includes("editingSkillPath"), "agent builder tracks custom skill edit state");
  assert(source.includes("Version"), "agent builder shows custom skill versions");
  assert(source.includes("Edit skill"), "agent builder exposes skill editing action");
  assert(source.includes("Delete skill"), "agent builder exposes skill deletion action");
  assert(source.includes("loadWorkspaceAgentSkillVersions"), "agent builder can load custom skill history");
  assert(source.includes("restoreWorkspaceAgentSkillVersion"), "agent builder can restore custom skill history");
  assert(source.includes("Skill history"), "agent builder exposes skill history review UI");
  assert(source.includes("Restore version"), "agent builder exposes skill version restore action");
  assert(!source.includes("<WorkspaceAgentSkillReviewPanel"), "workspace side panel does not render the skill review dashboard");
  assert(!source.includes("<WorkspaceAgentMemoryPanel"), "workspace side panel does not render the memory review dashboard");
  assert(!source.includes("agentMemories={view.agentMemories}"), "workspace side panel no longer mounts memory review data");
  assert(source.includes("archiveAgentMemory"), "workspace can archive reviewable agent memories from the details panel");
  assert(source.includes("/agent-memories/${memory.id}"), "agent memory archive uses explicit memory API route");
  assert(source.includes("Archive memory"), "agent memory cards expose an archive action");
  assert(agentMemoryBulkArchiveRoute.includes("archiveWorkspaceAgentMemories"), "agent memory API exposes bulk archive route");
  assert(source.includes("restoreAgentMemory"), "workspace can restore archived agent memories into local merged state");
  assert(reviewPage.includes("RestoreMemoryForm"), "workspace review page exposes archived memory restore forms");
  assert(reviewPage.includes("DeleteMemoryForm"), "workspace review page exposes permanent memory delete forms");
  assert(reviewPage.includes("?intent=restore"), "workspace review page posts restore intent to explicit memory API route");
  assert(reviewPage.includes("?intent=delete"), "workspace review page posts delete intent to explicit memory API route");
  assert(reviewPage.includes("Restore memory"), "workspace review page uses clear restore memory copy");
  assert(reviewPage.includes("Delete memory"), "workspace review page uses clear permanent memory delete copy");
  assert(reviewPage.includes("BulkArchiveMemoriesForm"), "workspace review page exposes bulk memory archive form");
  assert(reviewPage.includes("/agent-memories/bulk-archive"), "bulk memory archive form posts to explicit API route");
  assert(reviewPage.includes("Archive visible memories"), "bulk memory archive uses clear product copy");
  assert(agentMemoryBulkArchiveRoute.includes("Memory archive request is invalid."), "bulk memory archive API returns explicit validation errors");
  assert(agentMemoryBulkArchiveRoute.includes("Agent memory not found."), "bulk memory archive API returns explicit not-found errors");
  assert(agentMemoryRoute.includes("Unsupported memory action."), "memory review API returns explicit unsupported-action errors");
  assert(agentMemoryRoute.includes("Agent memory not found."), "memory review API returns explicit not-found errors");
  assert(source.includes("workspaceAgentMemoryScopeLabel"), "agent memory panel labels memory scopes in product language");
  assert(!source.includes("ArtifactLibraryPanel"), "workspace no longer renders the artifact review queue panel");
  assert(!source.includes("workspace-artifact-library"), "artifact review queue styling hook is removed from the workspace surface");
  assert(!source.includes("Artifact review queue"), "artifact review queue copy stays out of the workspace surface");
  assert(!source.includes("Review all"), "artifact review queue filters stay out of the workspace surface");
  assert(!source.includes("updateArtifactReviewStatus"), "workspace cannot update artifact review status from the removed queue");
  assert(!source.includes("Mark reviewed"), "artifact review status action is removed from the workspace surface");
  assert(!source.includes("Reopen review"), "artifact review reopen action is removed from the workspace surface");
  assert(!workspaceStore.includes("updateWorkspaceArtifactReview"), "artifact review status mutations are removed from the store");
  assert(workspaceStore.includes("assertDbWorkspaceTaskSourceVisibility"), "DB task creation validates source artifact/run visibility");
  assert(workspaceTaskService.includes("Task source run does not match source artifact."), "task source provenance rejects mismatched artifact/run ids");
  assert(workspaceAgentDoc.includes("Task creation validates source artifact and source run visibility"), "workspace agent doc records task source provenance guardrails");
  assert(source.includes("artifactsBySourceMessageId"), "chat artifact cards are keyed to first-class artifact records by source message");
  assert(source.includes("sourceArtifact={artifactsBySourceMessageId.get(message.id)}"), "chat artifact cards receive first-class artifact records when available");
  assert(source.includes("readWorkspaceArtifactDisplay"), "chat artifact cards normalize display from first-class artifacts");
  assert(source.includes("display.source === \"record\""), "chat artifact cards know when a first-class artifact record powered rendering");
  assert(source.includes("Artifact record"), "chat artifact cards expose first-class artifact provenance");
  assert(!source.includes('href="/workspace/review?tab=artifacts"'), "workspace details no longer link to the discarded artifact review page");
  assert(source.includes('href="/workspace/review?tab=skills"'), "workspace details link to the full skill review page");
  assert(source.includes('const kind = display.kind ?? workspaceMessageArtifactKind(displayPayload)'), "chat artifact cards only infer legacy kind as a fallback");
  assert(source.includes("const displayTitle = sourceArtifact?.title ?? artifact.title"), "chat artifact cards prefer first-class artifact title");
  assert(source.includes("const displayDescription = sourceArtifact?.description ?? artifact.description"), "chat artifact cards prefer first-class artifact description");
  assert(source.includes("payload: sourceArtifact?.payload ?? artifact"), "chat artifact cards prefer first-class artifact payload");
  assert(source.includes("workspaceMessageArtifactKind"), "chat artifact cards keep a fallback for legacy artifact payloads");
  assert(source.includes("workspace-artifact-message-card"), "chat artifact cards use semantic artifact styling hooks");
  assert(source.includes("Course artifact"), "chat artifact cards render generated courses as course artifacts");
  assert(source.includes("Saved artifact"), "chat artifact cards render saved artifacts with product wording");
  assert(source.includes("Task result"), "chat artifact cards render task outputs with product wording");
  assert(!source.includes(">Task card<"), "chat artifact cards no longer use the temporary Task card label");
  assert(artifactMigration.includes("INSERT INTO \"workspace_artifacts\""), "artifact migration backfills first-class artifact records from legacy message snapshots");
  assert(artifactMigration.includes("'wart_' || \"workspace_messages\".\"id\""), "artifact backfill uses source message ids for stable first-class artifact ids");
  assert(artifactMigration.includes("ON CONFLICT (\"source_message_id\") DO NOTHING"), "artifact backfill treats legacy message snapshots as compatibility input");
  assert(artifactMigration.includes("\"workspace_messages\".\"artifact\" IS NOT NULL"), "artifact backfill only imports legacy messages that actually have artifact snapshots");
  assert(reviewPage.includes("WorkspaceReviewPage"), "workspace has a dedicated review page for skills and memories");
  assert(!reviewPage.includes("Review artifacts"), "workspace review page no longer exposes artifact review");
  assert(!reviewPage.includes("ArtifactReviewStatusForm"), "workspace review page no longer exposes artifact review status forms");
  assert(!reviewPage.includes("formatWorkspaceArtifactReviewStatus"), "workspace review page no longer labels artifact review status");
  assert(reviewPage.includes("Review skills"), "workspace review page exposes skill review");
  assert(reviewPage.includes("skillVersionsByPath"), "workspace review page loads real skill version history for comparison");
  assert(reviewPage.includes("Compare latest"), "workspace review page exposes skill version comparison");
  assert(reviewPage.includes("formatSkillVersionCompare"), "workspace review page summarizes skill version differences");
  assert(reviewPage.includes("RestoreSkillVersionForm"), "workspace review page exposes skill version restore forms");
  assert(reviewPage.includes("restoreVersion"), "workspace review page posts selected skill version restore payloads");
  assert(reviewPage.includes("Restore v"), "workspace review page uses compact skill restore copy");
  assert(agentSkillsRoute.includes("restoreVersion"), "agent skill API accepts restore version payloads");
  assert(agentSkillsRoute.includes("intent") && agentSkillsRoute.includes("restore"), "agent skill API supports restore intent for review page forms");
  assert(reviewPage.includes("Review memories"), "workspace review page exposes memory review");
  assert(reviewPage.includes("view.agentMemories"), "workspace review page reads real persisted agent memory data");
  assert(reviewPage.includes("listWorkspaceAgentMemories"), "workspace review page can load archived memory audit records");
  assert(workspaceStore.includes("visibleThreadIds.has(memory.threadId)"), "memory audit list filters thread memories to visible threads");
  assert(workspaceAgentDoc.includes("Memory audit history also filters thread-scoped memories by visible threads"), "workspace agent doc records memory audit thread visibility guardrails");
  assert(reviewPage.includes("Archived memories"), "workspace review page exposes archived memory audit count");
  assert(reviewPage.includes("Recently archived"), "workspace review page shows recent archived memory audit entries");
  assert(reviewPage.includes("workspaceAgentMemoryScopeLabel"), "workspace review page labels memory scopes in product language");
  assert(reviewPage.includes('href="/workspace/review?tab=memories"'), "workspace review page has a dedicated memories tab");
  assert(reviewPage.includes("getWorkspaceView(ownerId"), "workspace review page reads real persisted workspace data");
  assert(reviewPage.includes("createWorkspaceAgentSkillBackend"), "workspace review page reads real persisted skill data");
  assert(reviewPage.includes("workspace-review-tabs"), "workspace review page has tabbed review navigation");
  assert(reviewPage.includes("workspace-review-grid"), "workspace review page uses a fuller grid layout");
  assert(!reviewPage.includes("No artifacts saved yet"), "workspace review page no longer carries artifact empty-state copy");
  assert(reviewPage.includes("No custom skills yet"), "workspace review page has a real empty skill state");
  assert(reviewPage.includes("No memories saved yet"), "workspace review page has a real empty memory state");
  assert(styles.includes(".workspace-agent-run-chip"), "agent run chip has dedicated styling");
  assert(!styles.includes(".workspace-room-settings-panel"), "workspace room settings panel styling is removed with the UI");
  assert(!styles.includes(".workspace-room-agent-access"), "workspace room agent access styling is removed with the UI");
  assert(styles.includes(".workspace-agent-run-detail"), "agent run detail has dedicated inline styling");
  assert(styles.includes(".workspace-agent-approval-card"), "agent approval card has dedicated styling");
  assert(styles.includes(".workspace-agent-approval-meta"), "agent approval metadata rows have dedicated styling");
  assert(styles.includes(".workspace-agent-custom-fields"), "custom agent fields have dedicated compact styling");
  assert(styles.includes(".workspace-agent-add-target"), "agent picker destination control has dedicated styling");
  assert(styles.includes(".workspace-agent-delegate-controls"), "delegate agent controls have dedicated compact styling");
  assert(styles.includes(".workspace-agent-edit-form"), "agent edit form has dedicated compact styling");
  assert(styles.includes(".workspace-agent-skill-controls"), "agent skill controls have dedicated compact styling");
  assert(styles.includes(".workspace-agent-skill-create"), "custom skill creation has dedicated compact styling");
  assert(styles.includes(".workspace-agent-skill-history"), "custom skill history has dedicated compact styling");
  assert(styles.includes(".workspace-agent-skill-review-panel"), "skill review panel has dedicated styling");
  assert(styles.includes(".workspace-agent-skill-review-card"), "skill review cards have dedicated styling");
  assert(styles.includes(".workspace-agent-memory-panel"), "agent memory review panel has dedicated styling");
  assert(styles.includes(".workspace-agent-memory-card"), "agent memory cards have dedicated styling");
  assert(styles.includes(".workspace-agent-memory-scope"), "agent memory scope labels have dedicated styling");
  assert(styles.includes(".workspace-agent-memory-actions"), "agent memory archive actions have dedicated styling");
  assert(styles.includes(".workspace-memory-restore"), "workspace review restore memory action has dedicated styling");
  assert(styles.includes(".workspace-memory-delete"), "workspace review permanent memory delete action has dedicated styling");
  assert(styles.includes(".workspace-agent-skill-source"), "custom skill source chip has dedicated compact styling");
  assert(styles.includes(".workspace-agent-library-panel"), "agent library panel has dedicated styling");
  assert(styles.includes(".workspace-agent-library-capabilities"), "agent library capability summary has dedicated styling");
  assert(styles.includes(".workspace-agent-picker-hints"), "agent picker capability hints have dedicated styling");
  assert(styles.includes(".workspace-member-picker-search"), "shared + picker search has dedicated styling");
  assert(styles.includes(".workspace-agent-connection-panel"), "connections panel has dedicated styling");
  assert(styles.includes(".workspace-agent-connection-card"), "connection cards have dedicated styling");
  assert(styles.includes(".workspace-agent-connection-controls"), "agent connection controls have dedicated styling");
  assert(styles.includes(".workspace-agent-action-group"), "agent action groups have dedicated styling");
  assert(styles.includes(".workspace-agent-action-group > strong"), "agent action group headings have dedicated styling");
  assert(styles.includes(".workspace-agent-edit-actions"), "agent edit footer has dedicated styling");
  assert(!styles.includes(".workspace-agent-edit-form > div"), "agent edit form does not override nested grouped action controls");
  assert(!styles.includes(".workspace-artifact-library"), "artifact review queue styling has been removed");
  assert(!styles.includes(".workspace-artifact-review-filter"), "artifact review filter styling has been removed");
  assert(!styles.includes(".workspace-artifact-review-meta"), "artifact review metadata styling has been removed");
  assert(!styles.includes(".workspace-artifact-review-status"), "artifact review status styling has been removed");
  assert(!styles.includes(".workspace-artifact-card"), "artifact review card styling has been removed");
  assert(!styles.includes(".workspace-artifact-kind"), "artifact review kind chip styling has been removed");
  assert(styles.includes(".workspace-artifact-message-card"), "semantic chat artifact cards have dedicated styling");
  assert(styles.includes(".workspace-artifact-message-card.course"), "course chat artifacts have dedicated styling");
  assert(styles.includes(".workspace-artifact-message-card.task_result"), "task result chat artifacts have dedicated styling");
  assert(styles.includes(".workspace-review-page"), "workspace review page has dedicated styling");
  assert(styles.includes(".workspace-review-tabs"), "workspace review tabs have dedicated styling");
  assert(styles.includes(".workspace-review-grid"), "workspace review grid has dedicated styling");
  assert(styles.includes(".workspace-skill-version-compare"), "workspace skill version compare has dedicated styling");
  assert(styles.includes(".workspace-skill-version-restore"), "workspace skill version restore area has dedicated styling");
  assert(styles.includes(".workspace-skill-restore"), "workspace skill restore forms have dedicated styling");

  process.stdout.write("[workspace-ui-static.unit] ALL UI STATIC CHECKS PASSED\n");
}

void main().catch((error) => {
  process.stderr.write(`[workspace-ui-static.unit] FAILED: ${(error as Error).message}\n`);
  process.exit(1);
});
