#!/usr/bin/env python3
"""A-Level Chemistry — CIE 9701 coverage."""
import os
from kg_en_builder import build

T = [
 ("che_atomic","Atomic Structure",[
   ("che_subatomic","Subatomic Particles","Protons, neutrons, electrons and their properties."),
   ("che_isotopes","Isotopes","Atoms of an element differing in neutron number."),
   ("che_electron_config","Electronic Configuration","Filling of subshells and orbitals."),
   ("che_ionisation","Ionisation Energy","Energy to remove electrons and periodic trends."),
 ]),
 ("che_stoichiometry","Atoms, Molecules and Stoichiometry",[
   ("che_mole","The Mole and Avogadro Constant","Amount of substance and the Avogadro constant."),
   ("che_formulae","Empirical and Molecular Formulae","Determining formulae from composition."),
   ("che_reacting_masses","Reacting Masses and Gas Volumes","Calculations from balanced equations."),
   ("che_titration","Concentration and Titration","Solution concentration and titrimetric analysis."),
 ]),
 ("che_bonding","Chemical Bonding",[
   ("che_ionic","Ionic Bonding","Electron transfer forming ions and lattices."),
   ("che_covalent","Covalent Bonding","Shared electron pairs and dative bonds."),
   ("che_metallic","Metallic Bonding","Lattice of cations in delocalised electrons."),
   ("che_vsepr","Shapes of Molecules (VSEPR)","Predicting shapes from electron-pair repulsion."),
   ("che_electronegativity","Electronegativity and Polarity","Bond polarity and dipole moments."),
   ("che_imf","Intermolecular Forces","Van der Waals, dipole and hydrogen bonding."),
 ]),
 ("che_states","States of Matter",[
   ("che_gas_laws","Ideal Gas Behaviour","pV=nRT and assumptions of the ideal gas."),
   ("che_solids","Solid Structures","Giant ionic, covalent, metallic and molecular solids."),
 ]),
 ("che_energetics","Chemical Energetics",[
   ("che_enthalpy","Enthalpy Changes","Exo/endothermic reactions and standard enthalpies."),
   ("che_hess","Hess's Law","Enthalpy as a state function via energy cycles."),
   ("che_bond_enthalpy","Bond Enthalpy","Estimating reaction enthalpy from bond energies."),
   ("che_calorimetry","Calorimetry","Measuring enthalpy change experimentally."),
 ]),
 ("che_kinetics","Reaction Kinetics",[
   ("che_rate","Rate of Reaction","Defining and measuring reaction rate."),
   ("che_collision","Collision Theory","Effective collisions and activation energy."),
   ("che_boltzmann","Maxwell-Boltzmann Distribution","Energy distribution and effect of temperature."),
   ("che_catalysis","Catalysis","Lowering activation energy via alternative pathways."),
   ("che_rate_equation","Rate Equations and Orders","Rate laws and reaction orders."),
   ("che_rds","Rate-Determining Step","Slowest step controlling overall rate."),
 ]),
 ("che_equilibrium","Chemical Equilibria",[
   ("che_dynamic_eq","Dynamic Equilibrium","Forward and reverse rates equal."),
   ("che_le_chatelier","Le Chatelier's Principle","Response of equilibrium to changes."),
   ("che_kc_kp","Equilibrium Constants Kc and Kp","Quantifying equilibrium position."),
 ]),
 ("che_acids","Acids, Bases and Buffers",[
   ("che_bronsted","Brønsted-Lowry Theory","Proton donors and acceptors."),
   ("che_strong_weak","Strong and Weak Acids","Degree of dissociation."),
   ("che_ph_ka","pH and Acid Dissociation Constant","pH calculations and Ka/pKa."),
   ("che_buffers","Buffers","Resisting pH change with conjugate pairs."),
   ("che_ksp","Solubility Product","Ksp and the common-ion effect."),
 ]),
 ("che_redox","Redox and Electrochemistry",[
   ("che_oxidation_number","Oxidation Numbers","Assigning oxidation states."),
   ("che_redox_equations","Redox Equations","Balancing half-equations."),
   ("che_electrode_potential","Electrode Potentials","Standard electrode potentials and the series."),
   ("che_cells","Electrochemical Cells","EMF of galvanic cells."),
   ("che_electrolysis","Electrolysis","Decomposition by electric current and Faraday's laws."),
 ]),
 ("che_thermodynamics","Lattice Energy and Thermodynamics",[
   ("che_born_haber","Lattice Energy and Born-Haber Cycles","Determining lattice energy via energy cycles."),
   ("che_entropy","Entropy","Disorder and entropy change of reactions."),
   ("che_gibbs","Gibbs Free Energy","ΔG=ΔH−TΔS and feasibility."),
 ]),
 ("che_periodicity","Periodicity",[
   ("che_periodic_trends","Periodic Trends","Trends in radius, ionisation energy and electronegativity."),
   ("che_period3","Period 3 Elements and Oxides","Reactions and properties across Period 3."),
 ]),
 ("che_groups","Inorganic Group Chemistry",[
   ("che_group2","Group 2 Chemistry","Reactions and trends of alkaline earth metals."),
   ("che_group17","Group 17 Halogens","Trends, displacement and disproportionation."),
   ("che_nitrogen_sulfur","Nitrogen and Sulfur","Key reactions and environmental chemistry."),
 ]),
 ("che_transition","Transition Elements",[
   ("che_transition_props","Transition Element Properties","Variable oxidation states and characteristics."),
   ("che_complex_ions","Complex Ions and Ligands","Ligand bonding and ligand exchange."),
   ("che_colour_catalysis","Colour and Catalysis","Origin of colour and catalytic behaviour."),
 ]),
 ("che_organic_basics","Introduction to Organic Chemistry",[
   ("che_nomenclature","Nomenclature","IUPAC naming of organic compounds."),
   ("che_isomerism","Isomerism","Structural and stereoisomerism."),
   ("che_bond_fission","Bond Fission and Reactive Species","Homolytic/heterolytic fission; radicals, nucleophiles, electrophiles."),
   ("che_mechanism_types","Reaction Mechanism Types","Addition, substitution, elimination overview."),
 ]),
 ("che_hydrocarbons","Hydrocarbons",[
   ("che_alkanes","Alkanes","Saturated hydrocarbons and free-radical substitution."),
   ("che_alkenes","Alkenes","Unsaturated hydrocarbons and electrophilic addition."),
   ("che_addition_polymer","Addition Polymerisation","Polymers from alkene monomers."),
 ]),
 ("che_halogenoalkanes","Halogen Compounds",[
   ("che_nucleophilic_sub","Nucleophilic Substitution","Substitution of halogenoalkanes."),
   ("che_elimination","Elimination Reactions","Forming alkenes from halogenoalkanes."),
 ]),
 ("che_alcohols","Hydroxy Compounds",[
   ("che_alcohol_reactions","Alcohols and Their Reactions","Properties and reactions of alcohols."),
   ("che_alcohol_oxidation","Oxidation of Alcohols","Forming aldehydes, ketones and carboxylic acids."),
 ]),
 ("che_carbonyls","Carbonyl and Carboxylic Compounds",[
   ("che_aldehydes_ketones","Aldehydes and Ketones","Carbonyl reactions and tests."),
   ("che_carboxylic_acids","Carboxylic Acids","Acidity and reactions of -COOH."),
   ("che_esters","Esters and Acyl Chlorides","Esterification and acyl derivatives."),
 ]),
 ("che_nitrogen_org","Nitrogen Compounds and Polymers",[
   ("che_amines","Amines","Basicity and reactions of amines."),
   ("che_amino_acids","Amino Acids and Proteins","Zwitterions and peptide bonds."),
   ("che_condensation_polymer","Condensation Polymers","Polyesters and polyamides."),
 ]),
 ("che_arenes","Arenes",[
   ("che_benzene","Benzene Structure","Delocalised bonding and stability of benzene."),
   ("che_electrophilic_sub","Electrophilic Substitution","Reactions of the benzene ring."),
 ]),
 ("che_analysis","Analytical Techniques",[
   ("che_mass_spec","Mass Spectrometry","Relative mass and fragmentation patterns."),
   ("che_ir","Infrared Spectroscopy","Identifying bonds from IR absorption."),
   ("che_nmr","NMR Spectroscopy","Proton/carbon environments from NMR."),
   ("che_chromatography","Chromatography","Separating mixtures by chromatography."),
 ]),
]

EDGES = [
 ("che_electron_config","che_ionisation","hard"),
 ("che_electron_config","che_ionic","hard"),
 ("che_electron_config","che_covalent","hard"),
 ("che_covalent","che_vsepr","hard"),
 ("che_electronegativity","che_imf","hard"),
 ("che_covalent","che_electronegativity","hard"),
 ("che_mole","che_formulae","hard"),
 ("che_mole","che_reacting_masses","hard"),
 ("che_reacting_masses","che_titration","hard"),
 ("che_ionic","che_solids","hard"),
 ("che_reacting_masses","che_enthalpy","soft"),
 ("che_enthalpy","che_hess","hard"),
 ("che_enthalpy","che_bond_enthalpy","hard"),
 ("che_enthalpy","che_calorimetry","hard"),
 ("che_rate","che_collision","hard"),
 ("che_collision","che_boltzmann","hard"),
 ("che_collision","che_catalysis","hard"),
 ("che_rate","che_rate_equation","hard"),
 ("che_rate_equation","che_rds","hard"),
 ("che_dynamic_eq","che_le_chatelier","hard"),
 ("che_dynamic_eq","che_kc_kp","hard"),
 ("che_titration","che_kc_kp","soft"),
 ("che_dynamic_eq","che_bronsted","soft"),
 ("che_bronsted","che_strong_weak","hard"),
 ("che_strong_weak","che_ph_ka","hard"),
 ("che_ph_ka","che_buffers","hard"),
 ("che_kc_kp","che_ksp","hard"),
 ("che_oxidation_number","che_redox_equations","hard"),
 ("che_redox_equations","che_electrode_potential","hard"),
 ("che_electrode_potential","che_cells","hard"),
 ("che_redox_equations","che_electrolysis","hard"),
 ("che_hess","che_born_haber","hard"),
 ("che_ionic","che_born_haber","hard"),
 ("che_entropy","che_gibbs","hard"),
 ("che_enthalpy","che_gibbs","hard"),
 ("che_ionisation","che_periodic_trends","hard"),
 ("che_periodic_trends","che_period3","hard"),
 ("che_periodic_trends","che_group2","hard"),
 ("che_periodic_trends","che_group17","hard"),
 ("che_oxidation_number","che_group17","soft"),
 ("che_electron_config","che_transition_props","hard"),
 ("che_transition_props","che_complex_ions","hard"),
 ("che_complex_ions","che_colour_catalysis","hard"),
 ("che_covalent","che_nomenclature","hard"),
 ("che_nomenclature","che_isomerism","hard"),
 ("che_nomenclature","che_alkanes","hard"),
 ("che_mechanism_types","che_alkanes","soft"),
 ("che_alkanes","che_alkenes","hard"),
 ("che_alkenes","che_addition_polymer","hard"),
 ("che_alkenes","che_nucleophilic_sub","soft"),
 ("che_nucleophilic_sub","che_elimination","hard"),
 ("che_nucleophilic_sub","che_alcohol_reactions","hard"),
 ("che_alcohol_reactions","che_alcohol_oxidation","hard"),
 ("che_alcohol_oxidation","che_aldehydes_ketones","hard"),
 ("che_aldehydes_ketones","che_carboxylic_acids","hard"),
 ("che_carboxylic_acids","che_esters","hard"),
 ("che_nucleophilic_sub","che_amines","hard"),
 ("che_carboxylic_acids","che_amino_acids","hard"),
 ("che_esters","che_condensation_polymer","hard"),
 ("che_amines","che_condensation_polymer","soft"),
 ("che_covalent","che_benzene","hard"),
 ("che_benzene","che_electrophilic_sub","hard"),
 ("che_mechanism_types","che_electrophilic_sub","soft"),
 ("che_isomerism","che_nmr","soft"),
 ("che_mole","che_mass_spec","soft"),
]

spec = {"id":"alevel_chem","subject":"A-Level Chemistry (CIE 9701)",
        "topics":[{"id":i,"name":n,"concepts":c} for (i,n,c) in T],"edges":EDGES}

if __name__ == "__main__":
    build(spec, os.path.join(os.path.dirname(__file__), "a_level_chemistry.json"))
