// AUTO-GENERATED by scripts/build-topic-graph.mjs. Do not edit by hand.
// Run `pnpm build:topic-graph all` after adding/removing a data/knowledge-graphs/source/*.json graph.
import type { TopicGraph } from "../topic-graph";

import g0 from "./topic-graph.a_level_biology.json";
import g1 from "./topic-graph.a_level_chemistry.json";
import g2 from "./topic-graph.a_level_mathematics.json";
import g3 from "./topic-graph.a_level_physics.json";
import g4 from "./topic-graph.artificial_intelligence.json";
import g5 from "./topic-graph.computer_architecture.json";
import g6 from "./topic-graph.computer_network.json";
import g7 from "./topic-graph.computer_systems.json";
import g8 from "./topic-graph.data_structures_and_algorithms.json";
import g9 from "./topic-graph.deep_learning.json";
import g10 from "./topic-graph.discrete_math_and_probability.json";
import g11 from "./topic-graph.information_theory.json";
import g12 from "./topic-graph.introduction_to_computer_science.json";
import g13 from "./topic-graph.linear_algebra.json";
import g14 from "./topic-graph.machine_learning.json";
import g15 from "./topic-graph.mit_calculus.json";
import g16 from "./topic-graph.numerical_analysis.json";
import g17 from "./topic-graph.python_fundamentals.json";
import g18 from "./topic-graph.sicp_cs61a.json";
import g19 from "./topic-graph.software_construction.json";
import g20 from "./topic-graph.web_applications.json";

export const DEFAULT_TOPIC_GRAPH_ID = "mit_calculus";

export const TOPIC_GRAPHS: Record<string, TopicGraph> = {
  "a_level_biology": g0 as unknown as TopicGraph,
  "a_level_chemistry": g1 as unknown as TopicGraph,
  "a_level_mathematics": g2 as unknown as TopicGraph,
  "a_level_physics": g3 as unknown as TopicGraph,
  "artificial_intelligence": g4 as unknown as TopicGraph,
  "computer_architecture": g5 as unknown as TopicGraph,
  "computer_network": g6 as unknown as TopicGraph,
  "computer_systems": g7 as unknown as TopicGraph,
  "data_structures_and_algorithms": g8 as unknown as TopicGraph,
  "deep_learning": g9 as unknown as TopicGraph,
  "discrete_math_and_probability": g10 as unknown as TopicGraph,
  "information_theory": g11 as unknown as TopicGraph,
  "introduction_to_computer_science": g12 as unknown as TopicGraph,
  "linear_algebra": g13 as unknown as TopicGraph,
  "machine_learning": g14 as unknown as TopicGraph,
  "mit_calculus": g15 as unknown as TopicGraph,
  "numerical_analysis": g16 as unknown as TopicGraph,
  "python_fundamentals": g17 as unknown as TopicGraph,
  "sicp_cs61a": g18 as unknown as TopicGraph,
  "software_construction": g19 as unknown as TopicGraph,
  "web_applications": g20 as unknown as TopicGraph,
};
