import { DEFAULT_VIEWER_LANGUAGE, type ViewerLanguage } from '@/shared/i18n/locale';
import { useProductLanguage } from '@/shared/i18n/useProductLanguage';

const viewerCatalog = {
  'zh-CN': {
    brand: {
      name: 'Primoria',
      tagline: '由 Flutter viewer 重构而来的 React 学习应用。',
    },
    language: {
      label: '产品语言',
      zh: '中文',
      en: 'English',
    },
    common: {
      loading: '加载中…',
      retry: '重试',
      reload: '重新加载',
      save: '保存更改',
      cancel: '取消',
      search: '搜索',
      send: '发送',
      back: '返回',
      statusSoon: '即将上线',
      statusDisabled: '暂时不可用',
      empty: '暂时还没有内容。',
      protectedHint: '请先登录后继续。',
      errorTitle: '需要恢复',
      errorFallback: '请求没有成功完成，请再试一次。',
      fatalTitle: '应用遇到了无法恢复的错误。',
      fatalMessage: '请重新加载应用；如果问题持续，请检查开关配置和错误日志。',
    },
    nav: {
      home: '首页',
      library: '课程库',
      community: '社区',
      aiTutor: 'AI导师',
      builder: 'Builder',
      profile: '我的',
    },
    landing: {
      eyebrow: 'Primoria',
      announcement: 'AI 驱动学习，现已上线',
      title: '掌握任何学科',
      accentTitle: '每天都能升级进步',
      subtitle:
        '互动式 STEM 课程、实时 AI 指导，以及学习伙伴社区。别再只看视频，现在就动手学习。',
      primaryCta: '免费开始学习',
      secondaryCta: '探索课程',
      registerCta: '立即开始',
      loginCta: '登录',
      learnerAppBadge: '学习应用',
      topNav: ['功能', '学习流程', 'AI 导师', '社区'],
      trustSignals: ['免费起步', '无需信用卡', '随时取消'],
      courseCardTitle: '物理 101',
      courseCardProgress: '72%',
      courseCardMeta: '第 8 / 11 课',
      streakValue: '12',
      streakLabel: '天连击',
      xpLabel: '+50 XP',
      tutorPrompt: '为什么 E = mc²?',
      featureTitle: '一套真正能学起来的系统',
      featureSubtitle: '课程、反馈、AI 和同伴支持，放在同一个学习闭环里。',
      features: [
        '交互式课程，不再只是被动看视频',
        '清晰的学习流程，知道下一步该做什么',
        'AI 导师实时协助总结、答疑和延伸讲解',
        '和同伴一起学习、讨论、保持进度',
      ],
    },
    auth: {
      loginTitle: '欢迎回来',
      loginSubtitle: '登录后继续你的学习流程。',
      registerTitle: '创建你的学习账号',
      registerSubtitle: '注册后可直接进入课程库、课程页和学习流程。',
      newHere: '第一次来？',
      createAccount: '创建账号',
      alreadyHaveAccount: '已有账号？',
      signInLink: '去登录',
      emailSectionTitle: '使用邮箱登录',
      registerEmailSectionTitle: '使用邮箱创建账号',
      forgotModeTitle: '重设你的密码',
      toggleForgot: '忘记密码？',
      backToLogin: '返回登录',
      keepExploring: '继续逛逛',
      returnToLanding: '返回首页',
      backToLanding: '回到首页',
      landingLabel: '首页',
      email: '邮箱地址',
      password: '密码',
      confirmPassword: '确认密码',
      displayName: '昵称',
      emailPlaceholder: 'learner@primoria.dev',
      passwordPlaceholder: '输入你的密码',
      createPasswordPlaceholder: '创建密码',
      confirmPasswordPlaceholder: '再次输入密码',
      displayNamePlaceholder: '输入你的显示名称',
      forgotPassword: '忘记密码？',
      sendReset: '发送重置链接',
      signIn: '登录',
      signUp: '创建账号',
      createWithEmail: '使用邮箱创建',
      hideEmailForm: '收起邮箱表单',
      google: '使用 Google 继续',
      apple: '使用 Apple 继续',
      wechat: '使用微信继续',
      soon: '即将上线',
      or: '或',
      wechatSoon: '微信登录还在开发中。',
      verifyTitle: '请检查你的邮箱',
      verifyMessage: '我们已经发出验证邮件，确认邮箱后再回来登录。',
      resetSuccess: '重置链接已发送，请查看邮箱。',
      registerSuccess: '账号已创建，请验证邮箱后继续登录。',
      accountCreated: '账号已创建',
      verifyAndLaunch: '验证后再开始。',
      verifySummaryPrefix: '我们已经向以下邮箱发送了确认链接：',
      verifySummarySuffix: '请先验证账号，再回到登录页继续。',
      registrationSupport: '邮箱注册后可直接进入课程库、课时和个人页。',
      hidePassword: '隐藏密码',
      showPassword: '显示密码',
    },
    home: {
      title: '首页',
      subtitle: '继续你的学习进度，回到正在进行的课程，并保持节奏。',
      continueLabel: '继续学习',
      libraryCta: '浏览课程',
      openCourse: '打开课程',
      previousCourse: '上一门课程',
      nextCourse: '下一门课程',
    },
    library: {
      title: '课程库',
      subtitle: '搜索课程、按学科筛选，并进入你的学习路径。',
      allCourses: '全部课程',
      ownedCourses: '自有课程',
      allSubjects: '全部',
      searchPlaceholder: '搜索课程...',
      noResults: '没有匹配的课程。',
      openDifficulty: '开放',
      updatingResults: '正在更新结果…',
      expandOwnedCourses: '展开自有课程',
      collapseOwnedCourses: '折叠自有课程',
    },
    course: {
      pageTitle: '课程',
      loading: '正在加载课程详情…',
      unavailable: '课程详情暂时不可用。',
      enrolled: '已报名',
      enroll: '立即报名',
      enrolling: '报名中…',
      startLesson: '开始本课',
      locked: '报名后解锁课时列表。',
      difficulty: '难度',
      estimated: '预计时长',
      subject: '学科',
      noteLabel: '课程提示',
      noteBody: '先浏览一次课程结构，再决定是否现在开始第一节。已报名用户可以直接进入学习流程。',
      backToLibrary: '返回课程库',
      lessonList: '课时列表',
      lessonLabel: '第 {index} 课',
      minutes: '{count} 分钟',
      openDuration: '灵活安排',
    },
    lesson: {
      titleFallback: '课程内容',
      check: '下一步',
      next: '下一页',
      prev: '上一页',
      askAi: '问AI',
      aiTitle: '问AI',
      aiEmpty: '基于当前页已经显示出来的内容提问，我会只围绕这些内容回答。',
      aiPlaceholder: '基于当前页面问点什么…',
      aiThinking: 'AI 正在思考…',
      complete: '完成',
      exit: '退出课程',
      completionTitle: '课程完成',
      unsupported: '这种区块类型暂时还不能在 React viewer 中交互。',
      loadingRuntime: '正在加载学习运行时…',
      unavailable: '课程内容暂时不可用。',
      noSnapshot: '当前路由没有解析到课时快照。',
      runtimeSubtitle: '课时运行、门控和完成流转',
      finalizing: '正在完成本次课时…',
    },
    result: {
      title: '结果总结',
      primary: '返回首页',
      secondary: '回到课程',
      finishedPrefix: '已完成：',
      xpAwarded: '获得 XP',
      correctAnswers: '答对题目',
      pagesCompleted: '完成页数',
      unlockedAchievements: '解锁成就',
      courseCompleted: '这节课已经完成了当前课程进度。',
    },
    community: {
      title: '社区',
      sections: ['总览', '一起学习', '消息', '热门讨论', '笔记'],
      send: '发送',
      sending: '发送中…',
      createRoom: '创建学习房间',
      creatingRoom: '创建中…',
      addNote: '添加笔记',
      disabled: '社区功能当前被发布开关暂时关闭。',
    },
    aiTutor: {
      title: 'AI 导师',
      subtitle: '围绕你的课程、笔记和问题进行整理、总结、测验和演示生成。',
      deskEyebrow: 'AI 学习桌',
      welcomeTitle: '你好，欢迎来到你的 AI 导师',
      welcomeBody:
        '很高兴认识你。我可以帮你整理笔记、总结长内容，并把想法转成清晰的知识结构。你可以从一个简单问题开始，我会一步步引导你。',
      placeholder: '开始输入…',
      send: '发送',
      mindMap: '思维导图',
      report: '报告',
      quiz: '测验',
      presentation: '演示',
      materials: '资料',
      expandWorkspace: '展开工作台',
      collapseWorkspace: '折叠工作台',
      expandMaterials: '展开资料',
      collapseMaterials: '折叠资料',
      expandNotebook: '展开笔记本',
      collapseNotebook: '折叠笔记本',
      uploadMaterials: '上传资料',
      materialsEmptyTitle: '还没有上传资料',
      materialsEmptyBody: '上传 PDF 或 DOCX 后，就能勾选它们来生成测验课程。',
      materialsLoading: '正在加载资料…',
      materialsUnavailable: '资料功能后端尚未部署到当前项目，请先应用最新的 Supabase 数据库迁移。',
      materialsProtected: '请先登录后再上传资料。',
      materialsSelected: '已选 {count} 份资料',
      deleteMaterial: '删除资料',
      materialChars: '{count} 字符',
      materialUploading: '提取中…',
      unsupportedPpt: 'PPT/PPTX 暂不支持直接解析，请先导出为 PDF 再上传。',
      unsupportedDoc: 'DOC 暂不支持直接解析，请另存为 DOCX 或 PDF 后再上传。',
      unsupportedFile: '暂不支持这种文件类型，请上传 PDF 或 DOCX。',
      materialUploaded: '资料已上传，可用于生成测验。',
      quizConfigTitle: '生成测验课程',
      quizConfigBody: '基于当前勾选资料创建一门未发布课程，生成后会出现在自有课程里。',
      questionCount: '题目数量',
      createQuizCourse: '创建测验课程',
      quizPreparing: '正在创建测验课程…',
      quizCreated: '测验已创建，已跳转到自有课程。',
      quizRequiresMaterials: '请先勾选至少一份资料。',
      quizRequiresUpload: '先上传并勾选资料后再生成测验。',
      quizPendingUploads: '资料仍在提取中，请稍后再生成。',
      quizUnavailable: '测验生成服务尚未部署到当前项目，请先部署 viewer-ai-quiz-from-docs 后重试。',
      quizOpenCourse: '打开课程',
      quizReady: '草稿课程已创建',
      openLatest: '打开最近结果',
      regenerate: '重新生成',
      generating: '生成中…',
      generatedReady: '最近结果已保存',
      failed: '生成失败',
      retryGeneration: '重试生成',
      noArtifactsTitle: '还没有生成内容',
      noArtifactsBody: '先从右侧工作台生成一份导图、报告、测验课程或演示，结果会在这里保留。',
      reportReady: '报告已更新，可在右侧继续查看。',
      reportPreparing: '正在生成学习报告…',
      responsePreparing: '正在整理回复…',
      responseReady: '回复已更新。',
      closeDialog: '关闭',
      apiKeyStored: 'Gemini key 已保存在本地。',
      missingKey:
        'AI 导师当前未完成环境配置。请配置服务端密钥，或使用 /apikey <your-key> 临时覆盖。',
      disabled: 'AI 导师当前已被发布开关暂时关闭。',
      prompts: [
        '你好！可以帮我规划今天的学习任务吗？',
        '我是新用户，你能怎么帮我做笔记？',
        '可以把我的笔记总结成简单的思维导图吗？',
      ],
      notebook: {
        generated: '已生成',
        pending: '尚未生成',
        playback: '演化回放',
        refreshedToday: '4 个来源 - 今日更新',
        reviewedTwoHoursAgo: '12 张卡片 - 2 小时前复习',
        syncedSummary: '摘要已同步',
      },
    },
    profile: {
      title: '我的',
      achievements: '成就墙',
      settings: '设置中心',
      pinned: '精选成就',
      stats: '学习概览',
    },
    settings: {
      title: '设置中心',
      subtitle: '管理你的账号、学习偏好与隐私选项。',
      signOut: '退出登录',
      generateBindingCode: '生成绑定码',
    },
    achievements: {
      title: '成就馆',
      manage: '管理精选',
      done: '完成整理',
    },
    parent: {
      title: '家长看板',
      subtitle: '查看已绑定的学习者、切换孩子，并查看最新学习报告。',
      bind: '使用绑定码关联孩子',
      binding: '关联中…',
      unbind: '解除关联',
      unbinding: '解除中…',
    },
    accountMenu: {
      open: '打开账号菜单',
      settings: '设置',
      help: '帮助',
      about: '关于',
      signOut: '退出登录',
    },
    dashboard: {
      home: '首页',
      course: '课程管理',
      data: '数据中心',
      fans: '粉丝管理',
      settings: '设置',
      account: '账号',
      workflow: '工作流',
      notifications: '通知',
    },
  },
  en: {
    brand: {
      name: 'Primoria',
      tagline: 'A React learner app rebuilt from the Flutter viewer.',
    },
    language: {
      label: 'Product language',
      zh: '中文',
      en: 'English',
    },
    common: {
      loading: 'Loading…',
      retry: 'Retry',
      reload: 'Reload',
      save: 'Save changes',
      cancel: 'Cancel',
      search: 'Search',
      send: 'Send',
      back: 'Back',
      statusSoon: 'Coming soon',
      statusDisabled: 'Temporarily disabled',
      empty: 'Nothing to show yet.',
      protectedHint: 'Sign in to continue.',
      errorTitle: 'Recovery needed',
      errorFallback: 'The request could not be completed. Try again.',
      fatalTitle: 'The app hit an unrecoverable error.',
      fatalMessage: 'Reload the app. If the problem persists, inspect the feature flags and error logs.',
    },
    nav: {
      home: 'Home',
      library: 'Library',
      community: 'Community',
      aiTutor: 'AI Tutor',
      builder: 'Builder',
      profile: 'Me',
    },
    landing: {
      eyebrow: 'Primoria',
      announcement: 'AI-powered learning is live',
      title: 'Master any subject',
      accentTitle: 'with momentum every day',
      subtitle:
        'Interactive STEM courses, real-time AI guidance, and a learning community built into one system. Stop only watching videos and start learning by doing.',
      primaryCta: 'Start learning free',
      secondaryCta: 'Explore courses',
      registerCta: 'Get started',
      loginCta: 'Log in',
      learnerAppBadge: 'Learner app',
      topNav: ['Features', 'Workflow', 'AI Tutor', 'Community'],
      trustSignals: ['Free to start', 'No credit card', 'Cancel anytime'],
      courseCardTitle: 'Physics 101',
      courseCardProgress: '72%',
      courseCardMeta: 'Lesson 8 / 11',
      streakValue: '12',
      streakLabel: 'day streak',
      xpLabel: '+50 XP',
      tutorPrompt: 'Why is E = mc²?',
      featureTitle: 'A system that actually gets you learning',
      featureSubtitle: 'Courses, feedback, AI, and peer support in one learning loop.',
      features: [
        'Interactive lessons instead of passive video watching',
        'A clear learning flow so the next step is always obvious',
        'An AI tutor for summaries, Q&A, and follow-up explanations',
        'Community support to keep your pace and discuss ideas',
      ],
    },
    auth: {
      loginTitle: 'Welcome back',
      loginSubtitle: 'Sign in to resume your learner flow.',
      registerTitle: 'Create your learner account',
      registerSubtitle: 'Register once and continue directly into library, courses, and lessons.',
      newHere: 'New here?',
      createAccount: 'Create an account',
      alreadyHaveAccount: 'Already have an account?',
      signInLink: 'Sign in',
      emailSectionTitle: 'Sign in with email',
      registerEmailSectionTitle: 'Create with email',
      forgotModeTitle: 'Reset your password',
      toggleForgot: 'Forgot password?',
      backToLogin: 'Back to sign in',
      keepExploring: 'Keep exploring',
      returnToLanding: 'Return to landing',
      backToLanding: 'Back to landing',
      landingLabel: 'Landing',
      email: 'Email address',
      password: 'Password',
      confirmPassword: 'Confirm password',
      displayName: 'Display name',
      emailPlaceholder: 'learner@primoria.dev',
      passwordPlaceholder: 'Enter your password',
      createPasswordPlaceholder: 'Create a password',
      confirmPasswordPlaceholder: 'Repeat your password',
      displayNamePlaceholder: 'Your display name',
      forgotPassword: 'Forgot password?',
      sendReset: 'Send reset link',
      signIn: 'Sign in',
      signUp: 'Create account',
      createWithEmail: 'Create with email',
      hideEmailForm: 'Hide email form',
      google: 'Continue with Google',
      apple: 'Continue with Apple',
      wechat: 'Continue with WeChat',
      soon: 'Soon',
      or: 'or',
      wechatSoon: 'WeChat sign-in is still coming soon.',
      verifyTitle: 'Check your email',
      verifyMessage: 'We sent a verification email. Confirm it, then come back to sign in.',
      resetSuccess: 'Reset link sent. Check your inbox.',
      registerSuccess: 'Account created. Verify your email, then sign in to continue.',
      accountCreated: 'Account created',
      verifyAndLaunch: 'Verify and launch.',
      verifySummaryPrefix: 'We sent a confirmation link to',
      verifySummarySuffix: 'Open it, verify the account, and return to sign in.',
      registrationSupport: 'Email registration continues directly into library, lessons, and profile.',
      hidePassword: 'Hide password',
      showPassword: 'Show password',
    },
    home: {
      title: 'Home',
      subtitle: 'Resume your learning path, jump back into in-progress courses, and keep the rhythm.',
      continueLabel: 'Continue learning',
      libraryCta: 'Browse library',
      openCourse: 'Open course',
      previousCourse: 'Previous course',
      nextCourse: 'Next course',
    },
    library: {
      title: 'Library',
      subtitle: 'Search courses, filter by subject, and enter your learning path.',
      allCourses: 'All Courses',
      ownedCourses: 'Owned Courses',
      allSubjects: 'All',
      searchPlaceholder: 'Search courses...',
      noResults: 'No matching courses found.',
      openDifficulty: 'Open',
      updatingResults: 'Updating results…',
      expandOwnedCourses: 'Expand owned courses',
      collapseOwnedCourses: 'Collapse owned courses',
    },
    course: {
      pageTitle: 'Course',
      loading: 'Loading course detail…',
      unavailable: 'Course detail is unavailable.',
      enrolled: 'Enrolled',
      enroll: 'Enroll now',
      enrolling: 'Enrolling…',
      startLesson: 'Start lesson',
      locked: 'Enroll to unlock the lesson list.',
      difficulty: 'Difficulty',
      estimated: 'Estimated',
      subject: 'Subject',
      noteLabel: 'Course note',
      noteBody: 'Review the course structure first, then decide whether to begin the first lesson now. Enrolled learners can jump straight into the lesson flow.',
      backToLibrary: 'Back to library',
      lessonList: 'Lesson list',
      lessonLabel: 'Lesson {index}',
      minutes: '{count} min',
      openDuration: 'Flexible pacing',
    },
    lesson: {
      titleFallback: 'Lesson',
      check: 'Next step',
      next: 'Next page',
      prev: 'Previous page',
      askAi: 'Ask AI',
      aiTitle: 'Ask AI',
      aiEmpty: 'Ask about the visible content on this page. I will stay grounded in what is already shown.',
      aiPlaceholder: 'Ask about this page…',
      aiThinking: 'AI is thinking…',
      complete: 'Complete',
      exit: 'Exit lesson',
      completionTitle: 'Lesson complete',
      unsupported: 'This block type is not interactive in the React viewer yet.',
      loadingRuntime: 'Loading learner runtime…',
      unavailable: 'Lesson content is unavailable.',
      noSnapshot: 'No lesson snapshot could be resolved for this route.',
      runtimeSubtitle: 'Lesson runtime, gating, and completion flow',
      finalizing: 'Finalizing lesson completion…',
    },
    result: {
      title: 'Result summary',
      primary: 'Back home',
      secondary: 'Return to course',
      finishedPrefix: 'Finished: ',
      xpAwarded: 'XP awarded',
      correctAnswers: 'Correct answers',
      pagesCompleted: 'Pages completed',
      unlockedAchievements: 'Unlocked achievements',
      courseCompleted: 'This lesson completed the current course enrollment.',
    },
    community: {
      title: 'Community',
      sections: ['Dashboard', 'Study Rooms', 'Messages', 'Trending', 'Notes'],
      send: 'Send',
      sending: 'Sending…',
      createRoom: 'Create study room',
      creatingRoom: 'Creating…',
      addNote: 'Add note',
      disabled: 'Community features are temporarily disabled by the release flag.',
    },
    aiTutor: {
      title: 'AI Tutor',
      subtitle: 'Organize notes, summarize lessons, generate quizzes, and turn ideas into structured outputs.',
      deskEyebrow: 'AI study desk',
      welcomeTitle: 'Hello, welcome to your AI tutor',
      welcomeBody:
        'I can help organize notes, summarize long material, and turn ideas into clear knowledge structures. Start with a simple question and I will guide the next step.',
      placeholder: 'Start typing…',
      send: 'Send',
      mindMap: 'Mind map',
      report: 'Report',
      quiz: 'Quiz',
      presentation: 'Presentation',
      materials: 'Materials',
      expandWorkspace: 'Expand workspace',
      collapseWorkspace: 'Collapse workspace',
      expandMaterials: 'Expand materials',
      collapseMaterials: 'Collapse materials',
      expandNotebook: 'Expand notebook',
      collapseNotebook: 'Collapse notebook',
      uploadMaterials: 'Upload materials',
      materialsEmptyTitle: 'No materials uploaded yet',
      materialsEmptyBody: 'Upload a PDF or DOCX, then select it to generate a quiz course.',
      materialsLoading: 'Loading materials…',
      materialsUnavailable: 'The materials backend is not deployed on this Supabase project yet. Apply the latest database migration first.',
      materialsProtected: 'Sign in before uploading materials.',
      materialsSelected: '{count} selected',
      deleteMaterial: 'Delete material',
      materialChars: '{count} chars',
      materialUploading: 'Extracting…',
      unsupportedPpt: 'PPT/PPTX is not supported directly yet. Export it to PDF first.',
      unsupportedDoc: 'Legacy DOC is not supported yet. Save it as DOCX or PDF first.',
      unsupportedFile: 'This file type is not supported yet. Upload a PDF or DOCX.',
      materialUploaded: 'Material uploaded and ready for quiz generation.',
      quizConfigTitle: 'Create quiz course',
      quizConfigBody: 'Build an unpublished course draft from the selected materials. It will appear in owned courses.',
      questionCount: 'Question count',
      createQuizCourse: 'Create quiz course',
      quizPreparing: 'Creating quiz course…',
      quizCreated: 'Quiz course created. Redirecting to owned courses.',
      quizRequiresMaterials: 'Select at least one material first.',
      quizRequiresUpload: 'Upload and select materials before generating a quiz.',
      quizPendingUploads: 'Some materials are still being extracted. Try again in a moment.',
      quizUnavailable: 'The quiz generation service is not deployed on this Supabase project yet. Deploy viewer-ai-quiz-from-docs and try again.',
      quizOpenCourse: 'Open course',
      quizReady: 'Draft course created',
      openLatest: 'Open latest result',
      regenerate: 'Generate again',
      generating: 'Generating…',
      generatedReady: 'Latest result saved',
      failed: 'Generation failed',
      retryGeneration: 'Retry',
      noArtifactsTitle: 'Nothing generated yet',
      noArtifactsBody: 'Generate a mind map, report, quiz course, or presentation from the workspace and it will stay here.',
      reportReady: 'Report updated. You can reopen it from the workspace.',
      reportPreparing: 'Generating study report…',
      responsePreparing: 'Preparing reply…',
      responseReady: 'Reply updated.',
      closeDialog: 'Close',
      apiKeyStored: 'Gemini key stored locally.',
      missingKey:
        'AI Tutor is not fully configured yet. Configure the server key, or use /apikey <your-key> to override it temporarily.',
      disabled: 'AI Tutor is temporarily disabled by the release flag.',
      prompts: [
        'Can you help me plan today’s study tasks?',
        'I am a new learner. How can you help me take notes?',
        'Can you turn my notes into a simple mind map?',
      ],
      notebook: {
        generated: 'Generated',
        pending: 'Not generated',
        playback: 'Playback',
        refreshedToday: '4 sources · refreshed today',
        reviewedTwoHoursAgo: '12 cards · reviewed 2 hours ago',
        syncedSummary: 'Summary synced',
      },
    },
    profile: {
      title: 'Me',
      achievements: 'Achievements',
      settings: 'Settings',
      pinned: 'Pinned achievements',
      stats: 'Learning overview',
    },
    settings: {
      title: 'Settings Center',
      subtitle: 'Manage your account, learning preferences, and privacy options.',
      signOut: 'Sign out',
      generateBindingCode: 'Generate binding code',
    },
    achievements: {
      title: 'Achievement Hall',
      manage: 'Manage pinned',
      done: 'Done',
    },
    parent: {
      title: 'Parent dashboard',
      subtitle: 'Review linked learners, switch active child, and inspect the latest report.',
      bind: 'Bind child with code',
      binding: 'Binding…',
      unbind: 'Unbind',
      unbinding: 'Unbinding…',
    },
    accountMenu: {
      open: 'Open account menu',
      settings: 'Settings',
      help: 'Help',
      about: 'About',
      signOut: 'Sign out',
    },
    dashboard: {
      home: 'Home',
      course: 'Course Management',
      data: 'Data Center',
      fans: 'Fan Management',
      settings: 'Settings',
      account: 'Account',
      workflow: 'Workflow',
      notifications: 'Notifications',
    },
  },
} as const;

type DeepWiden<T> =
  T extends string ? string
  : T extends readonly (infer U)[] ? readonly DeepWiden<U>[]
  : T extends object ? { [K in keyof T]: DeepWiden<T[K]> }
  : T;

export type ViewerCopy = DeepWiden<(typeof viewerCatalog)['zh-CN']>;

export function getViewerCopy(language: ViewerLanguage = DEFAULT_VIEWER_LANGUAGE): ViewerCopy {
  return viewerCatalog[language] as ViewerCopy;
}

export function useViewerCopy() {
  return getViewerCopy(useProductLanguage());
}

export const viewerCopy = getViewerCopy();
