export const viewerCopy = {
  brand: {
    name: 'Primoria',
    tagline: 'A React learner app rebuilt from the Flutter viewer.',
  },
  common: {
    loading: 'Loading…',
    retry: 'Retry',
    reload: 'Reload viewer',
    save: 'Save changes',
    cancel: 'Cancel',
    search: 'Search',
    statusSoon: 'Coming soon',
    statusDisabled: 'Temporarily disabled',
    empty: 'Nothing to show yet.',
    protectedHint: 'Sign in to continue.',
    errorTitle: 'Recovery needed',
    errorFallback: 'The viewer could not finish that request. Try again.',
    fatalTitle: 'The viewer hit an unrecoverable error.',
    fatalMessage: 'Reload the app. If the problem persists, roll the feature flag back and inspect Sentry.',
  },
  nav: {
    home: '首页',
    library: '课程库',
    community: '社区',
    aiTutor: 'AI导师',
    builder: 'Builder',
    profile: '我的',
  },
  landing: {
    eyebrow: 'Primoria',
    announcement: 'AI驱动学习，现已上线',
    title: '掌握任何学科',
    accentTitle: '每天都能升级进步',
    subtitle:
      '互动式 STEM 课程、实时 AI 指导，以及学习伙伴社区。别再只看视频，现在就动手学习。',
    primaryCta: '免费开始学习',
    secondaryCta: '探索课程',
    loginCta: '登录',
    topNav: ['功能', '学习流程', 'AI导师', '社区'],
    trustSignals: ['免费起步', '无需信用卡', '随时取消'],
    courseCardTitle: '物理 101',
    courseCardProgress: '72%',
    courseCardMeta: '第 8 / 11 课',
    streakValue: '12',
    streakLabel: '天连击',
    xpLabel: '+50 XP',
    tutorPrompt: '为什么 E = mc²?',
    featureTitle: '一套真正能学起来的系统',
    featureSubtitle: '课程、反馈、AI 和同伴支持，放在同一个学习闭环里。',
    features: [
      '交互式课程，不再只是被动看视频',
      '清晰的学习流程，知道下一步该做什么',
      'AI 导师实时协助总结、答疑和延伸讲解',
      '和同伴一起学习、讨论、保持进度',
    ],
  },
  auth: {
    loginTitle: 'Welcome back',
    loginSubtitle: 'Sign in to resume your learner flow.',
    registerTitle: 'Create your learner account',
    registerSubtitle: 'Start studying published lessons from the new React viewer.',
    email: 'Email address',
    password: 'Password',
    confirmPassword: 'Confirm password',
    displayName: 'Display name',
    forgotPassword: 'Forgot password?',
    sendReset: 'Send reset link',
    signIn: 'Sign in',
    signUp: 'Create account',
    google: 'Continue with Google',
    apple: 'Continue with Apple',
    wechat: 'Continue with WeChat',
    wechatSoon: 'WeChat sign-in is still coming soon.',
    backToLogin: 'Back to sign in',
    verifyTitle: 'Check your email',
    verifyMessage: 'Verify your email address, then sign in to continue.',
    resetSuccess: 'Reset link sent. Check your inbox.',
    demoLearner: 'Use demo learner',
    demoParent: 'Use demo parent',
  },
  home: {
    title: '首页',
    subtitle: '继续你的学习进度，回到正在进行的课程，并保持节奏。',
    continueLabel: '继续学习',
    libraryCta: '浏览课程',
    openCourse: '打开课程',
  },
  library: {
    title: '课程库',
    subtitle: '搜索课程、按学科筛选，并进入你的学习路径。',
    allSubjects: '全部',
    noResults: '没有匹配的课程。',
  },
  course: {
    enroll: 'Enroll now',
    enrolled: 'Enrolled',
    startLesson: 'Start lesson',
    locked: 'Enroll to unlock the lesson list.',
  },
  lesson: {
    titleFallback: 'Lesson',
    check: 'Check',
    next: 'Next',
    prev: 'Prev',
    complete: 'Complete',
    exit: 'Exit lesson',
    completionTitle: 'Lesson complete',
    unsupported: 'This block type is not interactive in the React viewer yet.',
  },
  result: {
    title: 'Result summary',
    primary: 'Back home',
    secondary: 'Return to course',
  },
  community: {
    title: '社区',
    sections: ['Dashboard', 'Our Study', 'Messages', 'Trending', 'Notes'],
    send: '发送',
    createRoom: '创建学习房间',
    addNote: '添加笔记',
    disabled: '社区能力当前已被发布开关暂时关闭。',
  },
  aiTutor: {
    title: 'AI导师',
    subtitle: '围绕你的课程、笔记和问题进行整理、总结、测验和演示生成。',
    placeholder: '开始输入…',
    mindMap: '思维导图',
    quiz: '测验',
    presentation: '演示',
    missingKey:
      'AI 导师当前未完成环境配置。请配置服务端密钥，或使用 /apikey <your-key> 临时覆盖。',
    disabled: 'AI 导师当前已被发布开关暂时关闭。',
  },
  profile: {
    title: '我的',
    achievements: '成就墙',
    settings: '设置中心',
    pinned: '精选成就',
    stats: '学习概览',
  },
  settings: {
    title: '设置中心',
    subtitle: '管理你的账号、学习偏好与隐私选项。',
    signOut: '退出登录',
    generateBindingCode: '生成绑定码',
  },
  achievements: {
    title: '成就馆',
    manage: '管理精选',
    done: '完成整理',
  },
  parent: {
    title: 'Parent dashboard',
    subtitle: 'Review linked learners, switch active child, and inspect the latest report.',
    bind: 'Bind child with code',
    unbind: 'Unbind',
  },
} as const;
