import { DEFAULT_VIEWER_LANGUAGE, type ViewerLanguage } from '@/shared/i18n/locale';
import { useProductLanguage } from '@/shared/i18n/useProductLanguage';

const landingCopy = {
  'zh-CN': {
    eyebrow: 'Primoria',
    header: {
      loginCta: '登录',
      registerCta: '创建账号',
    },
    authPanel: {
      badge: '平台入口',
      title: '把创作、学习、AI 与家长报告放进同一条产品链路',
      features: [
        '同一应用内覆盖课程发现、学习运行时、AI Tutor 与个人中心',
        'Builder 负责课程管理、编辑、发布与作者工作流',
        '家长模式、双语界面与共享 schema 构成完整平台闭环',
      ],
    },
    nav: {
      product: '产品闭环',
      learner: '学习流程',
      tutor: 'AI 导师',
      community: '社区',
      builder: 'Builder',
      family: '家长模式',
    },
    hero: {
      announcement: '平台级互动课程系统',
      title: '从创作到学习',
      accentTitle: '把互动课程真正跑起来',
      subtitle:
        'Primoria 把 Builder、学习运行时、AI Tutor、社区和家长报告放进一个连续产品闭环里。作者能发布结构化互动课程，学习者能在同一应用里学习、提问、讨论并持续升级。',
      primaryCta: '创建账号',
      secondaryCta: '登录',
      trustSignals: [
        'Builder 与 Viewer 已经并入同一 React 应用',
        '课程、Lesson、Result 学习链路已经打通',
        'Schema 兼容历史 pages 键并支持发布校验',
      ],
      cards: [
        {
          eyebrow: 'Creator workflow',
          title: 'Builder Dashboard',
          meta: 'Home / Course Management / Data Center / Fan Management',
        },
        {
          eyebrow: 'Learner runtime',
          title: 'Lesson Runtime',
          meta: 'Library / Course / Lesson / Result',
        },
        {
          eyebrow: 'AI layer',
          title: 'AI Tutor',
          meta: 'Chat / Mind Map / Quiz / Presentation',
        },
        {
          eyebrow: 'Family view',
          title: 'Parent Dashboard',
          meta: 'Binding code / child reports',
        },
      ],
    },
    platform: {
      eyebrow: '产品闭环',
      title: '一个产品把课程生产、学习执行与回流连接起来',
      subtitle:
        'Primoria 不是把功能散落在多个站点里，而是把创作者、学习者、AI 和家长模式收进一个连续路径。',
      lanes: [
        {
          eyebrow: 'Builder side',
          title: '创作者先搭课，再进入发布与分析',
          description:
            'Builder Dashboard 负责课程管理、数据中心与粉丝管理；编辑器负责 block 编排、保存、发布、导入导出和 AI draft。',
        },
        {
          eyebrow: 'Learner side',
          title: '学习者沿着真实课程链路前进',
          description:
            '学习者从课程库进入课程页、再进入 Lesson Runtime，完成答题、解锁、结果总结与 XP 回流，而不是停留在静态内容页。',
        },
        {
          eyebrow: 'Family side',
          title: '家长模式接住监督与复盘场景',
          description:
            '学习者生成绑定码后，家长账号可进入看板查看孩子列表、切换孩子并读取最新学习报告。',
        },
      ],
      foundations: [
        '统一 React 应用与共享认证',
        '共享 schema 与导入迁移兼容',
        '中英文双语切换',
        '受保护路由、功能开关与恢复路径',
      ],
    },
    learner: {
      eyebrow: '学习流程',
      title: 'Learner journey 不是一页介绍，而是一条完整运行时',
      subtitle:
        '首页需要讲清楚学习者真正会经历什么：发现课程、报名进入、完成 Lesson Runtime，再把结果回流到成长体系。',
      steps: [
        {
          step: '01',
          route: '/library',
          title: 'Course discovery in Library',
          description: '按主题搜索课程、切换筛选、进入课程详情页并判断是否开始当前学习路径。',
        },
        {
          step: '02',
          route: '/course/:courseId',
          title: 'Enroll and inspect course detail',
          description: '课程页展示难度、时长、课时列表与报名状态；报名后才能解锁进入课时。',
        },
        {
          step: '03',
          route: '/lesson/:lessonId',
          title: 'Run the gated lesson flow',
          description:
            'Lesson Runtime 负责 Prev / Check / Next、题目判定、按正确性解锁 block，以及与 AI 助手的上下文问答。',
        },
        {
          step: '04',
          route: '/lesson/:lessonId/result',
          title: 'Return XP, progress, and achievements',
          description: 'Result 页回收正确率、完成页数、XP 奖励与新成就，把学习势能继续推回首页与个人页。',
        },
      ],
      sideTitle: '真实产品表面，而不是抽象营销插画',
      sideBody:
        '新的 landing 会直接借用课程封面、进度条、结果卡和学习状态语言，让用户一眼看出产品已经具备完整路径。',
      sideHighlights: ['课程封面与报名入口', 'Lesson 运行时门控', 'Result 与 XP 回流'],
    },
    tutor: {
      eyebrow: 'AI 导师',
      title: 'AI Tutor 不是一句“在线”，而是一套可操作工作台',
      subtitle:
        '页面需要明确展示：对话答疑、跟进解释、`/apikey` 临时覆盖、材料上传、以及导图/测验/演示等 Studio tools。',
      capabilities: [
        {
          title: 'Grounded chat',
          description: '围绕课程、页面上下文与学习问题持续对话，而不是离开学习链路单独聊天。',
        },
        {
          title: '/apikey override',
          description: '开发或个人使用时可通过命令临时覆盖服务端 key，而不需要改动正式环境配置。',
        },
        {
          title: 'Tool outputs',
          description: '在同一工作台里生成 mind map、report、quiz course 和 presentation，并保留最近结果。',
        },
        {
          title: 'Materials pipeline',
          description: '上传 PDF / DOCX 后可继续提取、选择资料并生成测验课程草稿，闭环连接到课程系统。',
        },
      ],
      conversation: [
        '帮我把这节课的关键点整理成一张简短思维导图。',
        '可以。我会先提炼 lesson 中已经出现的概念，再补一份适合复习的导图结构。',
        '顺手再生成 5 道小测验，并把结果存到最近输出里。',
      ],
      tools: ['Mind Map', 'Report', 'Quiz Course', 'Presentation', 'Materials'],
      footer: 'Studio tools 会和对话工作流共存，而不是跳出到另一套产品。',
    },
    community: {
      eyebrow: '社区',
      title: 'Community 覆盖消息、学习房间、Trending 与 Notes',
      subtitle:
        '新的 landing 要把社区写得足够具体，说明它既能承接同伴协作，也能承接学习过程中的讨论与知识沉淀。',
      pillars: [
        {
          title: 'Messages',
          description: '直连会话与房间对话都可持久化，未读数和线程内容会跟随当前学习关系更新。',
        },
        {
          title: 'Study Rooms',
          description: '创建、加入、删除学习房间，围绕特定课程或主题组织一个临时学习小队。',
        },
        {
          title: 'Trending',
          description: '讨论、评论与互动信号沉淀成公开热点，让社区不只停留在私聊。',
        },
        {
          title: 'Notes',
          description: '学习者可写个人或房间笔记，让课程知识、AI 输出和同伴讨论汇到同一个空间。',
        },
      ],
      noteTitle: '社区在产品里承担的角色',
      noteBody: '它不是单独的论坛，而是学习流程中的协作层，让课程、讨论和笔记形成回流。',
    },
    growth: {
      eyebrow: '成长体系',
      title: 'XP、连击、成就、账号设置与提醒一起维持学习节奏',
      subtitle:
        '成长系统不只是榜单皮肤，而是把结果页、成就墙、设置中心、提醒与个人资料连接起来，持续拉回学习者。',
      cards: [
        {
          title: 'XP progression',
          description: '课时完成、测验结果与活动都会回流到 XP 进度与个人概览。',
        },
        {
          title: 'Streak momentum',
          description: '连续学习天数会直接成为首页状态语言和提醒机制的一部分。',
        },
        {
          title: 'Achievement wall',
          description: '成就墙独立存在，用户可以管理 pinned achievements，而不是只在结果页一闪而过。',
        },
        {
          title: 'Profile & settings',
          description: '头像、简介、主题、语言、AI persona、隐私和每日目标都在正式设置中心里维护。',
        },
      ],
      achievementLabels: ['First Lesson', 'Hot Streak', 'Perfect Score', 'Study Buddy'],
      accountCards: [
        {
          title: 'Notifications',
          description: '浏览器推送、每日提醒和连击中断提醒会跟随设置中心与 Web Push 状态同步。',
        },
        {
          title: 'Privacy & support',
          description: 'Support、Privacy、Terms 与反馈入口保留在产品里，构成真实可访问的配套页面。',
        },
      ],
    },
    family: {
      eyebrow: '家长模式',
      title: '家长模式不抢首页主叙事，但必须清楚可见',
      subtitle:
        '它负责把学习者的绑定码、已关联孩子列表与学习报告汇总成单独视角，让监督与复盘不需要脱离产品。',
      cards: [
        {
          title: 'Binding code flow',
          description: '学习者在设置中心生成绑定码，家长账号输入后建立关系。',
        },
        {
          title: 'Child switching',
          description: '家长看板可以切换当前孩子，避免报告只覆盖单一账户。',
        },
        {
          title: 'Latest report view',
          description: '绑定后即可读取当前孩子的学习报告、概览指标与最新动态。',
        },
      ],
    },
    builderDashboard: {
      eyebrow: 'Builder Dashboard',
      title: 'Builder Dashboard 负责把课程经营面与作者工作流收在一起',
      subtitle:
        '它不是简单后台导航，而是 Home、Course Management、Data Center、Fan Management 四个核心域的统一工作台。',
      strips: ['4 个核心 Tab', '课程动作与 analytics 聚合', '搜索 / 筛选 / 发布在同一工作台'],
      tabs: [
        {
          title: 'Home',
          description: '显示问候语、快捷操作、学习概览 KPI、趋势和最近活动，让作者先看到整个工作台状态。',
        },
        {
          title: 'Course Management',
          description: '创建课程、编辑元数据、复制、删除、添加课时、搜索筛选和直接打开编辑器都在这里完成。',
        },
        {
          title: 'Data Center',
          description: '课程规模、已发布浏览量、完成率、学习趋势和收入预估集中呈现。',
        },
        {
          title: 'Fan Management',
          description: '粉丝 KPI、增长趋势、标签、互动时间线和未来消息入口都保留在同一层级。',
        },
      ],
    },
    builderEditor: {
      eyebrow: 'Builder Editor',
      title: '编辑器围绕 block、schema 与 learner preview 搭建课程生产链路',
      subtitle:
        '这里需要把编辑能力讲具体：块级编辑、课时结构、保存发布、导入导出、AI draft、以及跟学习端一致的 preview。',
      capabilities: [
        'Block 增删改排与拖拽排序',
        'text / code-block / code-playground 内联编辑',
        '保存、发布、复制、导入、导出',
        'AI course draft 预览与后续落地',
        '图片上传与编辑器侧资源接入',
        '按学习端流程运行的 learner preview',
      ],
      blockTypes: ['text', 'image', 'code-block', 'code-playground', 'multiple-choice', 'matching', 'video'],
      schema: [
        '`lessons` 为规范顶层键',
        '历史 `pages` 导入会自动迁移',
        '可见性规则支持 `always` 与 `afterPreviousCorrect`',
        '发布 / 导出阶段启用更严格校验',
      ],
      previewTitle: '同一套 schema 进入编辑器，也进入学习运行时',
      previewBody: '这让 landing 能自然说明：Primoria 不是拆开的 Builder 和 Viewer，而是共享数据契约的同一平台。',
    },
    featureAtlas: {
      eyebrow: 'Feature Atlas',
      title: '底部矩阵补齐次级能力，但不打断主叙事',
      subtitle:
        '这些功能不必都占据主视觉区块，但必须让用户知道它们已经存在于产品里，而不是未来路线图。',
      items: [
        '邮箱 / OAuth 认证与受保护路由',
        '中英文产品语言切换',
        'Settings Center',
        'Support / Feedback / Privacy / Terms',
        'Achievement Wall',
        'Schema 兼容与导入迁移',
        'Feature flags 与恢复路径',
        'Parent binding codes',
      ],
    },
    finalCta: {
      title: '先进入 Primoria，再沿着真实产品路径继续探索',
      subtitle:
        '登录与注册入口保持不变，但新的首页会把平台全貌讲清楚，让学习者、创作者和家长都知道自己会进入什么系统。',
      primaryCta: '创建账号',
      secondaryCta: '登录',
    },
  },
  en: {
    eyebrow: 'Primoria',
    header: {
      loginCta: 'Log in',
      registerCta: 'Create account',
    },
    authPanel: {
      badge: 'Platform access',
      title: 'One product loop for creation, learning, AI guidance, and parent reporting',
      features: [
        'A single app now covers discovery, lesson runtime, AI Tutor, and profile surfaces',
        'Builder owns course operations, editing, publishing, and author workflows',
        'Parent mode, bilingual UI, and shared schema complete the platform loop',
      ],
    },
    nav: {
      product: 'Product',
      learner: 'Learner',
      tutor: 'AI Tutor',
      community: 'Community',
      builder: 'Builder',
      family: 'Family',
    },
    hero: {
      announcement: 'Interactive course platform',
      title: 'From course creation to active learning',
      accentTitle: 'run the full loop inside one product',
      subtitle:
        'Primoria connects Builder, learner runtime, AI Tutor, community, and parent reports into one continuous system. Authors publish structured interactive courses, and learners move through courses, questions, discussion, and progress without leaving the app.',
      primaryCta: 'Create account',
      secondaryCta: 'Log in',
      trustSignals: [
        'Builder and Viewer now live in one React app',
        'Course, lesson, and result routes are already connected',
        'The schema keeps legacy `pages` imports compatible',
      ],
      cards: [
        {
          eyebrow: 'Creator workflow',
          title: 'Builder Dashboard',
          meta: 'Home / Course Management / Data Center / Fan Management',
        },
        {
          eyebrow: 'Learner runtime',
          title: 'Lesson Runtime',
          meta: 'Library / Course / Lesson / Result',
        },
        {
          eyebrow: 'AI layer',
          title: 'AI Tutor',
          meta: 'Chat / Mind Map / Quiz / Presentation',
        },
        {
          eyebrow: 'Family view',
          title: 'Parent Dashboard',
          meta: 'Binding code / child reports',
        },
      ],
    },
    platform: {
      eyebrow: 'Product Loop',
      title: 'One platform connects course production, learner execution, and feedback loops',
      subtitle:
        'Primoria does not scatter capability across separate products. It turns authors, learners, AI tools, and family reporting into one continuous path.',
      lanes: [
        {
          eyebrow: 'Builder side',
          title: 'Authors create first, then publish and analyze',
          description:
            'Builder Dashboard covers course management, analytics, and fan operations; the editor handles block composition, save/publish, import/export, and AI draft workflows.',
        },
        {
          eyebrow: 'Learner side',
          title: 'Learners move through the real course runtime',
          description:
            'The path starts in Library, continues through course detail, enters Lesson Runtime, and returns into result, XP, and achievement flows instead of stopping at static content.',
        },
        {
          eyebrow: 'Family side',
          title: 'Parent mode closes the supervision and review loop',
          description:
            'Learners can generate binding codes, and parent accounts can enter a dedicated dashboard to inspect linked children and the latest reports.',
        },
      ],
      foundations: [
        'Unified React app and auth shell',
        'Shared schema with migration compatibility',
        'Bilingual product UI',
        'Protected routes, feature flags, and recovery paths',
      ],
    },
    learner: {
      eyebrow: 'Learner Journey',
      title: 'The learner story is a runtime, not a single marketing promise',
      subtitle:
        'The landing page should explain what the learner actually does: discover a course, enroll, complete the lesson runtime, and feed the result back into growth systems.',
      steps: [
        {
          step: '01',
          route: '/library',
          title: 'Discover courses in Library',
          description: 'Search by subject, apply filters, inspect a course detail page, and decide whether to begin that path now.',
        },
        {
          step: '02',
          route: '/course/:courseId',
          title: 'Enroll and inspect course detail',
          description: 'The course page exposes difficulty, pacing, lesson list, and enrollment state before the learner enters the runtime.',
        },
        {
          step: '03',
          route: '/lesson/:lessonId',
          title: 'Run the gated lesson flow',
          description:
            'Lesson Runtime handles Prev / Check / Next, answer validation, gated block reveal, and page-grounded AI assistance in the same flow.',
        },
        {
          step: '04',
          route: '/lesson/:lessonId/result',
          title: 'Return XP, progress, and achievements',
          description: 'The result screen rolls correctness, completed pages, XP, and unlocked achievements back into home and profile surfaces.',
        },
      ],
      sideTitle: 'Real product surfaces instead of generic illustrations',
      sideBody:
        'The redesign should reuse actual course covers, progress language, result cards, and learner state cues so the page feels grounded in the current app.',
      sideHighlights: ['Course cover + enroll entry', 'Lesson runtime gating', 'Result + XP feedback'],
    },
    tutor: {
      eyebrow: 'AI Tutor',
      title: 'AI Tutor is a working desk, not a single “AI is online” claim',
      subtitle:
        'The page needs to show chat guidance, follow-up explanation, `/apikey` overrides, material uploads, and Studio tools for mind maps, quizzes, and presentations.',
      capabilities: [
        {
          title: 'Grounded chat',
          description: 'Conversations stay attached to courses, page context, and current study questions instead of drifting into a disconnected chatbot.',
        },
        {
          title: '/apikey override',
          description: 'A local command can temporarily override the server key for development or personal usage without changing production wiring.',
        },
        {
          title: 'Tool outputs',
          description: 'Mind map, report, quiz course, and presentation outputs live beside the conversation so the workflow stays coherent.',
        },
        {
          title: 'Materials pipeline',
          description: 'Upload PDF or DOCX material, select it, and generate quiz-course drafts that connect back into the course system.',
        },
      ],
      conversation: [
        'Turn this lesson into a concise revision mind map.',
        'Sure. I will ground the map in the concepts already present in the lesson and shape it for quick review.',
        'Then generate five quiz questions and keep the output in the recent artifacts panel.',
      ],
      tools: ['Mind Map', 'Report', 'Quiz Course', 'Presentation', 'Materials'],
      footer: 'Studio tools stay inside the same tutor workflow instead of becoming a separate product.',
    },
    community: {
      eyebrow: 'Community',
      title: 'Community covers messages, study rooms, trending threads, and notes',
      subtitle:
        'The landing page should describe community concretely enough that users understand it as a collaboration layer inside the learning loop.',
      pillars: [
        {
          title: 'Messages',
          description: 'Direct conversations and room-linked threads persist, refresh unread state, and stay tied to active study relationships.',
        },
        {
          title: 'Study Rooms',
          description: 'Create, join, and manage focused study rooms around a shared topic or course path.',
        },
        {
          title: 'Trending',
          description: 'Discussions, comments, and social signals create a visible public layer instead of leaving everything in private threads.',
        },
        {
          title: 'Notes',
          description: 'Personal notes and room notes keep course insights, AI output, and peer discussion in the same workspace.',
        },
      ],
      noteTitle: 'What community does in the product',
      noteBody: 'It is not a detached forum. It is the collaboration layer that lets course learning, discussion, and note taking feed into each other.',
    },
    growth: {
      eyebrow: 'Growth System',
      title: 'XP, streaks, achievements, settings, and reminders all support learner momentum',
      subtitle:
        'Growth is not just cosmetic ranking. It connects result screens, achievement management, reminders, profile data, and settings into an ongoing return loop.',
      cards: [
        {
          title: 'XP progression',
          description: 'Lesson completion, quiz results, and activity flow back into visible XP progress and learner overview surfaces.',
        },
        {
          title: 'Streak momentum',
          description: 'Consecutive study days become homepage status language and reminder logic instead of a hidden metric.',
        },
        {
          title: 'Achievement wall',
          description: 'Achievements have a dedicated surface where learners manage pinned badges instead of only seeing them on result screens.',
        },
        {
          title: 'Profile & settings',
          description: 'Avatar, bio, theme, language, AI persona, privacy, and daily goals all live in a formal settings center.',
        },
      ],
      achievementLabels: ['First Lesson', 'Hot Streak', 'Perfect Score', 'Study Buddy'],
      accountCards: [
        {
          title: 'Notifications',
          description: 'Browser push, daily reminders, and streak risk alerts stay connected to settings and Web Push state.',
        },
        {
          title: 'Privacy & support',
          description: 'Support, privacy, terms, and feedback pages already exist as product surfaces, not loose footer placeholders.',
        },
      ],
    },
    family: {
      eyebrow: 'Parent Mode',
      title: 'Parent mode stays secondary in the layout, but must stay explicit',
      subtitle:
        'It turns learner binding codes, linked-child lists, and report access into a dedicated review view without fragmenting the product.',
      cards: [
        {
          title: 'Binding code flow',
          description: 'Learners generate a binding code in settings and parent accounts use it to establish the relationship.',
        },
        {
          title: 'Child switching',
          description: 'The parent dashboard switches between children instead of collapsing reporting into one ambiguous account.',
        },
        {
          title: 'Latest report view',
          description: 'Once linked, the parent route exposes current study reports and the latest child activity summary.',
        },
      ],
    },
    builderDashboard: {
      eyebrow: 'Builder Dashboard',
      title: 'Builder Dashboard keeps the operating layer of the platform in one place',
      subtitle:
        'It is not a thin admin shell. It is a unified workspace for Home, Course Management, Data Center, and Fan Management.',
      strips: ['4 core tabs', 'course actions + analytics', 'search / filter / publish in one workspace'],
      tabs: [
        {
          title: 'Home',
          description: 'Greeting, quick actions, KPI summaries, trends, and recent activity give authors an immediate working overview.',
        },
        {
          title: 'Course Management',
          description: 'Create courses, edit metadata, duplicate, delete, add lessons, search, filter, and jump directly into the editor.',
        },
        {
          title: 'Data Center',
          description: 'Course scale, published viewers, completion quality, trend views, and revenue placeholders sit in one analytics layer.',
        },
        {
          title: 'Fan Management',
          description: 'Fan KPIs, growth, labels, and interaction history stay grouped at the same product level.',
        },
      ],
    },
    builderEditor: {
      eyebrow: 'Builder Editor',
      title: 'The editor is built around blocks, schema rules, and learner preview fidelity',
      subtitle:
        'This section needs concrete editing detail: block-level authoring, lesson structure, save/publish, import/export, AI draft, and preview behavior that matches the learner runtime.',
      capabilities: [
        'Add, remove, reorder, and sort blocks',
        'Inline editing for text, code-block, and code-playground',
        'Save, publish, duplicate, import, and export flows',
        'AI course draft previews',
        'Image upload and asset wiring',
        'Learner preview aligned with the real runtime',
      ],
      blockTypes: ['text', 'image', 'code-block', 'code-playground', 'multiple-choice', 'matching', 'video'],
      schema: [
        '`lessons` is the canonical top-level key',
        'Legacy `pages` imports are normalized automatically',
        'Visibility rules support `always` and `afterPreviousCorrect`',
        'Publish and export use stricter validation',
      ],
      previewTitle: 'The same schema drives editing and learner playback',
      previewBody: 'That lets the landing page explain Primoria as one platform with a shared data contract instead of separate Builder and Viewer islands.',
    },
    featureAtlas: {
      eyebrow: 'Feature Atlas',
      title: 'A compact matrix rounds out the platform without breaking the main story',
      subtitle:
        'These capabilities do not need a hero-sized section each, but they should still be clearly discoverable on the landing page.',
      items: [
        'Email / OAuth auth and protected routes',
        'Bilingual product language switching',
        'Settings Center',
        'Support / Feedback / Privacy / Terms',
        'Achievement Wall',
        'Schema compatibility and import migration',
        'Feature flags and recovery paths',
        'Parent binding codes',
      ],
    },
    finalCta: {
      title: 'Enter Primoria first, then continue through the real product path',
      subtitle:
        'The auth entry points stay the same, but the new landing page explains the full platform so learners, creators, and parents know what system they are entering.',
      primaryCta: 'Create account',
      secondaryCta: 'Log in',
    },
  },
} as const;

const viewerCatalog = {
  'zh-CN': {
    brand: {
      name: 'Primoria',
      tagline: '由 Flutter viewer 重构而来的 React 学习应用。',
    },
    language: {
      label: '产品语言',
      zh: '中文',
      en: 'English',
    },
    common: {
      loading: '加载中…',
      retry: '重试',
      reload: '重新加载',
      save: '保存更改',
      cancel: '取消',
      search: '搜索',
      send: '发送',
      back: '返回',
      statusSoon: '即将上线',
      statusDisabled: '暂时不可用',
      empty: '暂时还没有内容。',
      protectedHint: '请先登录后继续。',
      errorTitle: '需要恢复',
      errorFallback: '请求没有成功完成，请再试一次。',
      fatalTitle: '应用遇到了无法恢复的错误。',
      fatalMessage: '请重新加载应用；如果问题持续，请检查开关配置和错误日志。',
    },
    nav: {
      home: '继续学习',
      library: '找课程',
      community: '一起学',
      aiTutor: '学习助手',
      builder: '创作台',
      profile: '我的',
    },
    landing: landingCopy['zh-CN'],
    auth: {
      loginTitle: '欢迎回来',
      loginSubtitle: '登录后继续你的学习流程。',
      registerTitle: '创建你的学习账号',
      registerSubtitle: '注册后可直接进入课程库、课程页和学习流程。',
      newHere: '第一次来？',
      createAccount: '创建账号',
      alreadyHaveAccount: '已有账号？',
      signInLink: '去登录',
      emailSectionTitle: '使用邮箱登录',
      registerEmailSectionTitle: '使用邮箱创建账号',
      forgotModeTitle: '重设你的密码',
      toggleForgot: '忘记密码？',
      backToLogin: '返回登录',
      keepExploring: '继续逛逛',
      returnToLanding: '返回首页',
      backToLanding: '回到首页',
      landingLabel: '首页',
      email: '邮箱地址',
      password: '密码',
      confirmPassword: '确认密码',
      displayName: '昵称',
      emailPlaceholder: 'learner@primoria.dev',
      passwordPlaceholder: '输入你的密码',
      createPasswordPlaceholder: '创建密码',
      confirmPasswordPlaceholder: '再次输入密码',
      displayNamePlaceholder: '输入你的显示名称',
      forgotPassword: '忘记密码？',
      sendReset: '发送重置链接',
      signIn: '登录',
      signUp: '创建账号',
      createWithEmail: '使用邮箱创建',
      hideEmailForm: '收起邮箱表单',
      google: '使用 Google 继续',
      apple: '使用 Apple 继续',
      wechat: '使用微信继续',
      soon: '即将上线',
      or: '或',
      wechatSoon: '微信登录还在开发中。',
      verifyTitle: '请检查你的邮箱',
      verifyMessage: '我们已经发出验证邮件，确认邮箱后再回来登录。',
      resetSuccess: '重置链接已发送，请查看邮箱。',
      registerSuccess: '账号已创建，请验证邮箱后继续登录。',
      accountCreated: '账号已创建',
      verifyAndLaunch: '验证后再开始。',
      verifySummaryPrefix: '我们已经向以下邮箱发送了确认链接：',
      verifySummarySuffix: '请先验证账号，再回到登录页继续。',
      registrationSupport: '邮箱注册后可直接进入课程库、课时和个人页。',
      hidePassword: '隐藏密码',
      showPassword: '显示密码',
    },
    home: {
      title: '继续学习',
      subtitle: '从你上次停下的地方继续，今天少想一点，先开始就好。',
      continueLabel: '继续学习',
      libraryCta: '去找课程',
      openCourse: '打开课程',
      previousCourse: '上一门课程',
      nextCourse: '下一门课程',
    },
    library: {
      title: '找课程',
      subtitle: '看看现在适合学什么，选一门愿意开始的就行。',
      allCourses: '全部课程',
      ownedCourses: '自有课程',
      allSubjects: '全部',
      searchPlaceholder: '搜索课程...',
      noResults: '没有匹配的课程。',
      openDifficulty: '开放',
      updatingResults: '正在更新结果…',
      expandOwnedCourses: '展开自有课程',
      collapseOwnedCourses: '折叠自有课程',
    },
    course: {
      pageTitle: '课程',
      loading: '正在加载课程详情…',
      unavailable: '课程详情暂时不可用。',
      enrolled: '已报名',
      enroll: '立即报名',
      enrolling: '报名中…',
      startLesson: '开始本课',
      locked: '报名后解锁课时列表。',
      difficulty: '难度',
      estimated: '预计时长',
      subject: '学科',
      noteLabel: '课程提示',
      noteBody: '先浏览一次课程结构，再决定是否现在开始第一节。已报名用户可以直接进入学习流程。',
      backToLibrary: '返回课程库',
      lessonList: '课时列表',
      lessonLabel: '第 {index} 课',
      minutes: '{count} 分钟',
      openDuration: '灵活安排',
    },
    lesson: {
      titleFallback: '课程内容',
      check: '下一步',
      next: '下一页',
      prev: '上一页',
      askAi: '问AI',
      aiTitle: '问AI',
      aiEmpty: '基于当前页已经显示出来的内容提问，我会只围绕这些内容回答。',
      aiPlaceholder: '基于当前页面问点什么…',
      aiThinking: 'AI 正在思考…',
      complete: '完成',
      exit: '退出课程',
      completionTitle: '课程完成',
      unsupported: '这种区块类型暂时还不能在 React viewer 中交互。',
      loadingRuntime: '正在加载学习运行时…',
      unavailable: '课程内容暂时不可用。',
      noSnapshot: '当前路由没有解析到课时快照。',
      runtimeSubtitle: '课时运行、门控和完成流转',
      finalizing: '正在完成本次课时…',
    },
    result: {
      title: '结果总结',
      primary: '返回首页',
      secondary: '回到课程',
      finishedPrefix: '已完成：',
      xpAwarded: '获得 XP',
      correctAnswers: '答对题目',
      pagesCompleted: '完成页数',
      unlockedAchievements: '解锁成就',
      courseCompleted: '这节课已经完成了当前课程进度。',
      wrongReviewTitle: '错题回顾',
      yourAnswer: '你的答案',
      correctAnswer: '正确答案',
      wrongSelections: '错选答案',
      missedCorrectAnswers: '漏选答案',
      explanation: '解析',
      matchingPromptFallback: '匹配题',
      correctMatch: '正确匹配',
    },
    community: {
      title: '一起学',
      sections: ['学习小组', '聊天', '讨论', '我的笔记'],
      send: '发送',
      sending: '发送中…',
      createRoom: '创建学习房间',
      creatingRoom: '创建中…',
      addNote: '添加笔记',
      disabled: '一起学暂时还没开放，请稍后再来。',
    },
    aiTutor: {
      title: '学习助手',
      subtitle: '陪你拆问题、理资料，再把重点整理成更容易复习的结果。',
      deskEyebrow: 'AI 学习桌',
      welcomeTitle: '你好，我们慢慢把这件事理顺。',
      welcomeBody:
        '你可以把问题、资料或没想清楚的地方都先丢给我。我会先帮你收小任务，再一起往下走。',
      placeholder: '开始输入…',
      send: '发送',
      mindMap: '思维导图',
      quiz: '测验',
      materials: '资料',
      workspaceTitle: '我可以帮你',
      notebookTitle: '最近生成',
      expandWorkspace: '展开我可以帮你',
      collapseWorkspace: '折叠我可以帮你',
      expandMaterials: '展开资料',
      collapseMaterials: '折叠资料',
      expandNotebook: '展开最近生成',
      collapseNotebook: '折叠最近生成',
      uploadMaterials: '上传资料',
      materialsEmptyTitle: '还没有上传资料',
      materialsEmptyBody: '上传 PDF 或 DOCX 后，就能勾选它们来生成思维导图或测验。',
      materialsLoading: '正在加载资料…',
      materialsUnavailable: '现在还不能读取资料，请稍后再试。',
      materialsProtected: '请先登录后再上传资料。',
      materialsSelected: '已选 {count} 份资料',
      deleteMaterial: '删除资料',
      editMaterialTitle: '编辑资料标题',
      materialTitlePlaceholder: '输入资料标题',
      materialTitleSaved: '资料标题已更新。',
      materialTitleUnavailable: '现在还不能修改资料标题，请稍后再试。',
      materialChars: '{count} 字符',
      materialUploading: '提取中…',
      unsupportedPpt: 'PPT/PPTX 暂不支持直接解析，请先导出为 PDF 再上传。',
      unsupportedDoc: 'DOC 暂不支持直接解析，请另存为 DOCX 或 PDF 后再上传。',
      unsupportedFile: '暂不支持这种文件类型，请上传 PDF 或 DOCX。',
      materialUploaded: '资料已上传，可用于生成思维导图或测验。',
      mindMapConfigTitle: '生成思维导图',
      mindMapConfigBody: '基于当前勾选资料生成一张只读思维导图。你可以补充 Prompt，约束导图的组织方式或关注重点。',
      mindMapPromptLabel: '附加 Prompt（可选）',
      mindMapPromptPlaceholder: '例如：更偏向考试复习结构；突出因果关系；按章节组织；尽量简洁。',
      createMindMap: '生成思维导图',
      mindMapPreparing: '正在生成思维导图…',
      mindMapCreated: '思维导图已经准备好了，可以直接打开查看。',
      mindMapRequiresUpload: '先上传并勾选资料后再生成思维导图。',
      mindMapUnavailable: '现在还不能生成思维导图，请稍后再试。',
      quizConfigTitle: '生成测验课程',
      quizConfigBody: '基于当前勾选资料创建一门未发布课程，生成后会出现在自有课程里。',
      questionCount: '题目数量',
      quizLanguage: '题目语言',
      quizLanguageEnglish: 'English',
      quizLanguageChinese: '简体中文',
      createQuizCourse: '创建测验课程',
      quizPreparing: '正在创建测验课程…',
      quizCreated: '测验已经准备好了，可以直接去看。',
      quizRequiresMaterials: '请先勾选至少一份资料。',
      quizRequiresUpload: '先上传并勾选资料后再生成测验。',
      quizPendingUploads: '资料仍在提取中，请稍后再生成。',
      quizUnavailable: '现在还不能生成测验，请稍后再试。',
      quizGeneratingTitle: '正在生成测验课程…',
      quizGeneratingBody: '这可能需要一点时间',
      quizOpenCourse: '打开课程',
      quizReady: '草稿课程已创建',
      regenerate: '重新生成',
      generating: '生成中…',
      generatedReady: '最近结果已保存',
      failed: '生成失败',
      retryGeneration: '重试生成',
      noArtifactsTitle: '还没有最近结果',
      noArtifactsBody: '先生成一份导图或小测，这里会帮你留好最近结果。',
      responsePreparing: '正在整理回复…',
      responseReady: '回复已更新。',
      apiKeyStored: 'Gemini key 已保存在本地。',
      missingKey: '学习助手暂时还没准备好，请稍后再试。',
      disabled: '学习助手暂时还没开放，请稍后再来。',
      prompts: [
        '你好！可以帮我规划今天的学习任务吗？',
        '我是新用户，你能怎么帮我做笔记？',
        '可以把我的笔记总结成简单的思维导图吗？',
      ],
      notebook: {
        generated: '已生成',
        pending: '尚未生成',
        playback: '演化回放',
        refreshedToday: '4 个来源 - 今日更新',
        reviewedTwoHoursAgo: '12 张卡片 - 2 小时前复习',
        syncedSummary: '摘要已同步',
      },
    },
    profile: {
      title: '我的',
      achievements: '成就墙',
      settings: '账号设置',
      pinned: '精选成就',
      stats: '学习概览',
    },
    settings: {
      title: '账号设置',
      subtitle: '把资料、学习偏好、提醒和家长查看整理在一起。',
      signOut: '退出登录',
      generateBindingCode: '生成绑定码',
    },
    achievements: {
      title: '成就馆',
      manage: '管理精选',
      done: '完成整理',
    },
    parent: {
      title: '家长查看',
      subtitle: '查看已绑定的学习者、切换孩子，并查看最新学习报告。',
      bind: '使用绑定码关联孩子',
      binding: '关联中…',
      unbind: '解除关联',
      unbinding: '解除中…',
    },
    accountMenu: {
      open: '打开账号菜单',
      settings: '设置',
      help: '帮助',
      about: '关于',
      signOut: '退出登录',
    },
    dashboard: {
      home: '概览',
      course: '课程',
      data: '学习表现',
      fans: '学习表现',
      settings: '设置',
      account: '账号',
      workflow: '工作流',
      notifications: '通知',
    },
  },
  en: {
    brand: {
      name: 'Primoria',
      tagline: 'A React learner app rebuilt from the Flutter viewer.',
    },
    language: {
      label: 'Product language',
      zh: '中文',
      en: 'English',
    },
    common: {
      loading: 'Loading…',
      retry: 'Retry',
      reload: 'Reload',
      save: 'Save changes',
      cancel: 'Cancel',
      search: 'Search',
      send: 'Send',
      back: 'Back',
      statusSoon: 'Coming soon',
      statusDisabled: 'Temporarily disabled',
      empty: 'Nothing to show yet.',
      protectedHint: 'Sign in to continue.',
      errorTitle: 'Recovery needed',
      errorFallback: 'The request could not be completed. Try again.',
      fatalTitle: 'The app hit an unrecoverable error.',
      fatalMessage: 'Reload the app. If the problem persists, inspect the feature flags and error logs.',
    },
    nav: {
      home: 'Continue',
      library: 'Discover',
      community: 'Together',
      aiTutor: 'Helper',
      builder: 'Studio',
      profile: 'Me',
    },
    landing: landingCopy.en,
    auth: {
      loginTitle: 'Welcome back',
      loginSubtitle: 'Sign in to resume your learner flow.',
      registerTitle: 'Create your learner account',
      registerSubtitle: 'Register once and continue directly into library, courses, and lessons.',
      newHere: 'New here?',
      createAccount: 'Create an account',
      alreadyHaveAccount: 'Already have an account?',
      signInLink: 'Sign in',
      emailSectionTitle: 'Sign in with email',
      registerEmailSectionTitle: 'Create with email',
      forgotModeTitle: 'Reset your password',
      toggleForgot: 'Forgot password?',
      backToLogin: 'Back to sign in',
      keepExploring: 'Keep exploring',
      returnToLanding: 'Return to landing',
      backToLanding: 'Back to landing',
      landingLabel: 'Landing',
      email: 'Email address',
      password: 'Password',
      confirmPassword: 'Confirm password',
      displayName: 'Display name',
      emailPlaceholder: 'learner@primoria.dev',
      passwordPlaceholder: 'Enter your password',
      createPasswordPlaceholder: 'Create a password',
      confirmPasswordPlaceholder: 'Repeat your password',
      displayNamePlaceholder: 'Your display name',
      forgotPassword: 'Forgot password?',
      sendReset: 'Send reset link',
      signIn: 'Sign in',
      signUp: 'Create account',
      createWithEmail: 'Create with email',
      hideEmailForm: 'Hide email form',
      google: 'Continue with Google',
      apple: 'Continue with Apple',
      wechat: 'Continue with WeChat',
      soon: 'Soon',
      or: 'or',
      wechatSoon: 'WeChat sign-in is still coming soon.',
      verifyTitle: 'Check your email',
      verifyMessage: 'We sent a verification email. Confirm it, then come back to sign in.',
      resetSuccess: 'Reset link sent. Check your inbox.',
      registerSuccess: 'Account created. Verify your email, then sign in to continue.',
      accountCreated: 'Account created',
      verifyAndLaunch: 'Verify and launch.',
      verifySummaryPrefix: 'We sent a confirmation link to',
      verifySummarySuffix: 'Open it, verify the account, and return to sign in.',
      registrationSupport: 'Email registration continues directly into library, lessons, and profile.',
      hidePassword: 'Hide password',
      showPassword: 'Show password',
    },
    home: {
      title: 'Continue Learning',
      subtitle: 'Pick up where you left off and start with the next clear step.',
      continueLabel: 'Continue learning',
      libraryCta: 'Find a course',
      openCourse: 'Open course',
      previousCourse: 'Previous course',
      nextCourse: 'Next course',
    },
    library: {
      title: 'Find Courses',
      subtitle: 'Browse what feels right for today and start with one course.',
      allCourses: 'All Courses',
      ownedCourses: 'Owned Courses',
      allSubjects: 'All',
      searchPlaceholder: 'Search courses...',
      noResults: 'No matching courses found.',
      openDifficulty: 'Open',
      updatingResults: 'Updating results…',
      expandOwnedCourses: 'Expand owned courses',
      collapseOwnedCourses: 'Collapse owned courses',
    },
    course: {
      pageTitle: 'Course',
      loading: 'Loading course detail…',
      unavailable: 'Course detail is unavailable.',
      enrolled: 'Enrolled',
      enroll: 'Enroll now',
      enrolling: 'Enrolling…',
      startLesson: 'Start lesson',
      locked: 'Enroll to unlock the lesson list.',
      difficulty: 'Difficulty',
      estimated: 'Estimated',
      subject: 'Subject',
      noteLabel: 'Course note',
      noteBody: 'Review the course structure first, then decide whether to begin the first lesson now. Enrolled learners can jump straight into the lesson flow.',
      backToLibrary: 'Back to library',
      lessonList: 'Lesson list',
      lessonLabel: 'Lesson {index}',
      minutes: '{count} min',
      openDuration: 'Flexible pacing',
    },
    lesson: {
      titleFallback: 'Lesson',
      check: 'Next step',
      next: 'Next page',
      prev: 'Previous page',
      askAi: 'Ask AI',
      aiTitle: 'Ask AI',
      aiEmpty: 'Ask about the visible content on this page. I will stay grounded in what is already shown.',
      aiPlaceholder: 'Ask about this page…',
      aiThinking: 'AI is thinking…',
      complete: 'Complete',
      exit: 'Exit lesson',
      completionTitle: 'Lesson complete',
      unsupported: 'This block type is not interactive in the React viewer yet.',
      loadingRuntime: 'Loading learner runtime…',
      unavailable: 'Lesson content is unavailable.',
      noSnapshot: 'No lesson snapshot could be resolved for this route.',
      runtimeSubtitle: 'Lesson runtime, gating, and completion flow',
      finalizing: 'Finalizing lesson completion…',
    },
    result: {
      title: 'Result summary',
      primary: 'Back home',
      secondary: 'Return to course',
      finishedPrefix: 'Finished: ',
      xpAwarded: 'XP awarded',
      correctAnswers: 'Correct answers',
      pagesCompleted: 'Pages completed',
      unlockedAchievements: 'Unlocked achievements',
      courseCompleted: 'This lesson completed the current course enrollment.',
      wrongReviewTitle: 'Review wrong answers',
      yourAnswer: 'Your answer',
      correctAnswer: 'Correct answer',
      wrongSelections: 'Incorrect selections',
      missedCorrectAnswers: 'Missed correct answers',
      explanation: 'Explanation',
      matchingPromptFallback: 'Matching question',
      correctMatch: 'Correct match',
    },
    community: {
      title: 'Study Together',
      sections: ['Study Rooms', 'Chat', 'Discussions', 'My Notes'],
      send: 'Send',
      sending: 'Sending…',
      createRoom: 'Create study room',
      creatingRoom: 'Creating…',
      addNote: 'Add note',
      disabled: 'Study Together is not available right now. Check back soon.',
    },
    aiTutor: {
      title: 'Study Helper',
      subtitle: 'Break things down, sort your materials, and turn them into something easier to review.',
      deskEyebrow: 'AI study desk',
      welcomeTitle: 'Hello. Let’s make this feel lighter first.',
      welcomeBody:
        'Bring me the question, the notes, or the part that feels messy. I will help shrink it into the next step.',
      placeholder: 'Start typing…',
      send: 'Send',
      mindMap: 'Mind map',
      quiz: 'Quiz',
      materials: 'Materials',
      workspaceTitle: 'How I can help',
      notebookTitle: 'Recent results',
      expandWorkspace: 'Expand how I can help',
      collapseWorkspace: 'Collapse how I can help',
      expandMaterials: 'Expand materials',
      collapseMaterials: 'Collapse materials',
      expandNotebook: 'Expand recent results',
      collapseNotebook: 'Collapse recent results',
      uploadMaterials: 'Upload materials',
      materialsEmptyTitle: 'No materials uploaded yet',
      materialsEmptyBody: 'Upload a PDF or DOCX, then select it to generate a mind map or quiz.',
      materialsLoading: 'Loading materials…',
      materialsUnavailable: 'Materials are unavailable right now. Try again later.',
      materialsProtected: 'Sign in before uploading materials.',
      materialsSelected: '{count} selected',
      deleteMaterial: 'Delete material',
      editMaterialTitle: 'Edit material title',
      materialTitlePlaceholder: 'Enter a material title',
      materialTitleSaved: 'Material title updated.',
      materialTitleUnavailable: 'Material titles cannot be changed right now. Try again later.',
      materialChars: '{count} chars',
      materialUploading: 'Extracting…',
      unsupportedPpt: 'PPT/PPTX is not supported directly yet. Export it to PDF first.',
      unsupportedDoc: 'Legacy DOC is not supported yet. Save it as DOCX or PDF first.',
      unsupportedFile: 'This file type is not supported yet. Upload a PDF or DOCX.',
      materialUploaded: 'Material uploaded and ready for mind maps or quizzes.',
      mindMapConfigTitle: 'Generate mind map',
      mindMapConfigBody: 'Generate a read-only mind map from the selected materials. Add an optional prompt to shape the structure or emphasis.',
      mindMapPromptLabel: 'Additional prompt (optional)',
      mindMapPromptPlaceholder: 'For example: focus on exam revision, highlight cause and effect, organize by chapter, keep it concise.',
      createMindMap: 'Generate mind map',
      mindMapPreparing: 'Generating mind map…',
      mindMapCreated: 'Your mind map is ready to open.',
      mindMapRequiresUpload: 'Upload and select materials before generating a mind map.',
      mindMapUnavailable: 'Mind maps are unavailable right now. Try again later.',
      quizConfigTitle: 'Create quiz course',
      quizConfigBody: 'Build an unpublished course draft from the selected materials. It will appear in owned courses.',
      questionCount: 'Question count',
      quizLanguage: 'Quiz language',
      quizLanguageEnglish: 'English',
      quizLanguageChinese: 'Chinese (Simplified)',
      createQuizCourse: 'Create quiz course',
      quizPreparing: 'Creating quiz course…',
      quizCreated: 'Your quiz is ready to open.',
      quizRequiresMaterials: 'Select at least one material first.',
      quizRequiresUpload: 'Upload and select materials before generating a quiz.',
      quizPendingUploads: 'Some materials are still being extracted. Try again in a moment.',
      quizUnavailable: 'Quizzes are unavailable right now. Try again later.',
      quizGeneratingTitle: 'Generating quiz course…',
      quizGeneratingBody: 'This may take a little time',
      quizOpenCourse: 'Open course',
      quizReady: 'Draft course created',
      regenerate: 'Generate again',
      generating: 'Generating…',
      generatedReady: 'Latest result saved',
      failed: 'Generation failed',
      retryGeneration: 'Retry',
      noArtifactsTitle: 'No recent results yet',
      noArtifactsBody: 'Generate a mind map or quiz and it will stay here for later.',
      responsePreparing: 'Preparing reply…',
      responseReady: 'Reply updated.',
      apiKeyStored: 'Gemini key stored locally.',
      missingKey: 'Study Helper is not ready right now. Please try again later.',
      disabled: 'Study Helper is not available right now. Check back soon.',
      prompts: [
        'Can you help me plan today’s study tasks?',
        'I am a new learner. How can you help me take notes?',
        'Can you turn my notes into a simple mind map?',
      ],
      notebook: {
        generated: 'Generated',
        pending: 'Not generated',
        playback: 'Playback',
        refreshedToday: '4 sources · refreshed today',
        reviewedTwoHoursAgo: '12 cards · reviewed 2 hours ago',
        syncedSummary: 'Summary synced',
      },
    },
    profile: {
      title: 'Me',
      achievements: 'Achievements',
      settings: 'Account Settings',
      pinned: 'Pinned achievements',
      stats: 'Learning overview',
    },
    settings: {
      title: 'Account Settings',
      subtitle: 'Keep your profile, study habits, reminders, and family access in one place.',
      signOut: 'Sign out',
      generateBindingCode: 'Generate binding code',
    },
    achievements: {
      title: 'Achievement Hall',
      manage: 'Manage pinned',
      done: 'Done',
    },
    parent: {
      title: 'Family View',
      subtitle: 'Review linked learners, switch active child, and inspect the latest report.',
      bind: 'Bind child with code',
      binding: 'Binding…',
      unbind: 'Unbind',
      unbinding: 'Unbinding…',
    },
    accountMenu: {
      open: 'Open account menu',
      settings: 'Settings',
      help: 'Help',
      about: 'About',
      signOut: 'Sign out',
    },
    dashboard: {
      home: 'Overview',
      course: 'Courses',
      data: 'Learning Performance',
      fans: 'Learning Performance',
      settings: 'Settings',
      account: 'Account',
      workflow: 'Workflow',
      notifications: 'Notifications',
    },
  },
} as const;

type DeepWiden<T> =
  T extends string ? string
  : T extends readonly (infer U)[] ? readonly DeepWiden<U>[]
  : T extends object ? { [K in keyof T]: DeepWiden<T[K]> }
  : T;

export type ViewerCopy = DeepWiden<(typeof viewerCatalog)['zh-CN']>;

export function getViewerCopy(language: ViewerLanguage = DEFAULT_VIEWER_LANGUAGE): ViewerCopy {
  return viewerCatalog[language] as ViewerCopy;
}

export function useViewerCopy() {
  return getViewerCopy(useProductLanguage());
}

export const viewerCopy = getViewerCopy();
